"""MQ — materiallar qarshiligi mavzulari uchun interaktiv chizmalar."""

from __future__ import annotations

from content.curriculum.figures.base import fc, fig, fp, fr

FIGURES = {
 "mq-01": [
  fig("Zaxira koeffitsienti va ruxsat etilgan kuchlanish",
      "Oqish chegarasi zaxiraga bo'linadi — shundan ruxsat etilgan qiymat chiqadi.",
      params=[fp("sy", "Oqish chegarasi σᵧ", 150, 900, 350, 10, "MPa")],
      curves=[fc("[σ] = σᵧ/n", "sy/x", "tension"),
              fc("Oqish chegarasi", "sy", "rule", dashed=True)],
      x=("zaxira koeffitsienti n", "[σ], MPa"), x_min="1", x_max="5",
      readouts=[fr("[σ] (n=1,5)", "sy/1.5", "MPa", "tension"),
                fr("[σ] (n=2,5)", "sy/2.5", "MPa", "compress"),
                fr("Zaxira 2 dan 3 ga", "sy/2 - sy/3", "MPa kamayadi", "mark")],
      note="Zaxira noaniqlikni qoplaydi: material tarqoqligi, yuk oshib ketishi, hisob soddalashtirishlari."),
  fig("Sterjen kesimi va kuchlanish",
      "σ = N/A — kesim yuzasi ikki barobar oshsa kuchlanish ikki barobar kamayadi.",
      params=[fp("N", "O'qiy kuch", 5, 500, 100, 5, "kN")],
      curves=[fc("σ = N/A", "N*1000/(x*1e-4)/1e6", "tension"),
              fc("[σ] = 160 MPa", "160", "rule", dashed=True)],
      x=("kesim yuzasi A, sm²", "kuchlanish σ, MPa"), x_min="1", x_max="40",
      readouts=[fr("σ (A=10 sm²)", "N*1000/(10e-4)/1e6", "MPa", "tension"),
                fr("Kerakli A ([σ]=160)", "N*1000/160e6*1e4", "sm²", "compress")],
      note="Loyihalash teskari yo'nalishda boradi: kerakli yuza A ≥ N/[σ] dan topiladi."),
 ],
 "mq-02": [
  fig("Kesim usuli: ichki kuch epyurasi",
      "Har bir bo'lakda ichki kuch tashqi kuchlar yig'indisiga teng.",
      params=[fp("F1", "Birinchi kuch", -100, 100, 60, 5, "kN"),
              fp("F2", "Ikkinchi kuch", -100, 100, -40, 5, "kN")],
      curves=[fc("N(x) birinchi bo'lak", "F1 + 0*x", "tension"),
              fc("N(x) ikkinchi bo'lak", "F1 + F2 + 0*x", "compress", dashed=True),
              fc("Nol", "0", "rule", dashed=True)],
      x=("sterjen bo'ylab x, m", "o'qiy kuch N, kN"), x_min="0", x_max="4",
      readouts=[fr("N birinchi bo'lakda", "F1", "kN", "tension"),
                fr("N ikkinchi bo'lakda", "F1 + F2", "kN", "compress"),
                fr("Sakrash", "F2", "kN", "mark")],
      note="Epyura har bir to'plangan kuch joyida aynan shu kuchga teng SAKRASH qiladi."),
  fig("Kuchlanish — ichki kuchning zichligi",
      "Bir xil kuch turli yuzada turli kuchlanish beradi.",
      params=[fp("N", "Ichki kuch", 10, 400, 120, 5, "kN"),
              fp("A", "Kesim yuzasi", 2, 60, 12, 1, "sm²")],
      curves=[fc("σ(A) = N/A", "N*10/x", "tension"),
              fc("Joriy yuza", "N*10/A", "mark", dashed=True)],
      x=("yuza A, sm²", "σ, MPa"), x_min="2", x_max="60",
      readouts=[fr("Joriy σ", "N*10/A", "MPa", "tension"),
                fr("Yuza 2× bo'lsa", "N*10/(2*A)", "MPa", "compress"),
                fr("Ichki kuch", "N", "kN", "rule")],
      note="Ichki kuch kesimga bog'liq emas, kuchlanish esa bog'liq — shuning uchun mustahkamlik yuzaga qarab hisoblanadi."),
 ],
 "mq-03": [
  fig("Guk qonuni: kuchlanish va deformatsiya",
      "Chiziqli soha tugagach qonun buziladi.",
      params=[fp("E", "Elastiklik moduli", 70, 220, 210, 5, "GPa"),
              fp("sy", "Oqish chegarasi", 150, 600, 250, 10, "MPa")],
      curves=[fc("σ = Eε (chiziqli)", "E*1000*x", "tension"),
              fc("Oqish chegarasi", "sy", "rule", dashed=True)],
      x=("nisbiy deformatsiya ε, ‰", "σ, MPa"), x_min="0", x_max="3",
      readouts=[fr("Chiziqlilik chegarasi ε", "sy/(E*1000)", "‰", "mark"),
                fr("σ (ε=1‰)", "E*1000*0.001*1000", "MPa", "tension"),
                fr("Po'lat uchun ε_y", "250/210000*1000", "‰", "compress")],
      note="Po'lat atigi 0,12% deformatsiyagacha elastik — shuning uchun konstruksiyalar juda kam deformatsiyalanadi."),
  fig("Uzayish: uzunlik, yuza va modul ta'siri",
      "Δl = Nl/(EA) — to'rtta kattalikning birgalikdagi ta'siri.",
      params=[fp("N", "Kuch", 10, 500, 100, 5, "kN"),
              fp("A", "Yuza", 2, 50, 10, 1, "sm²"),
              fp("E", "Modul", 70, 220, 210, 5, "GPa")],
      curves=[fc("Δl(l) = Nl/(EA)", "N*1000*x/(E*1e9*A*1e-4)*1000", "tension")],
      x=("uzunlik l, m", "uzayish Δl, mm"), x_min="0", x_max="10",
      readouts=[fr("Δl (l=3 m)", "N*1000*3/(E*1e9*A*1e-4)*1000", "mm", "tension"),
                fr("Bikrlik EA/l (l=3)", "E*1e9*A*1e-4/3/1e6", "MN/m", "compress"),
                fr("Nisbiy deformatsiya", "N*1000/(E*1e9*A*1e-4)*1000", "‰", "mark")],
      note="Alyuminiy uchun E uch barobar kichik — shu sababli bir xil kuchda uch barobar ko'p uzayadi."),
 ],
 "mq-04": [
  fig("Cho'zilish diagrammasi: xarakterli nuqtalar",
      "Proporsionallik, oqish, mustahkamlik chegaralari ketma-ket keladi.",
      params=[fp("E", "Modul E", 70, 220, 210, 5, "GPa"),
              fp("sy", "Oqish σᵧ", 150, 600, 250, 10, "MPa"),
              fp("su", "Mustahkamlik σᵤ", 200, 900, 420, 10, "MPa")],
      curves=[fc("Elastik soha", "E*1000*x", "tension", when="1"),
              fc("Oqish maydoni", "sy", "compress", dashed=True),
              fc("Mustahkamlik chegarasi", "su", "mark", dashed=True)],
      x=("deformatsiya ε, ‰", "σ, MPa"), x_min="0", x_max="4",
      readouts=[fr("ε oqishda", "sy/(E*1000)", "‰", "compress"),
                fr("Mustahkamlik zaxirasi", "su/sy", "marta", "mark"),
                fr("Elastik energiya", "sy^2/(2*E*1000)", "kJ/m³", "tension")],
      note="σᵤ/σᵧ nisbati plastiklik zaxirasini ko'rsatadi: 1,5 dan katta bo'lsa material ishonchli."),
  fig("Mo'rt va plastik material",
      "Bir xil mustahkamlikda uzilishgacha bo'lgan energiya keskin farq qiladi.",
      params=[fp("su", "Mustahkamlik chegarasi", 200, 900, 400, 10, "MPa"),
              fp("d_pl", "Plastik cho'zilish", 2, 30, 15, 1, "%")],
      curves=[fc("Plastik material", "min(210000*x/1000, su)", "compress"),
              fc("Mo'rt material", "210000*x/1000", "tension"),
              fc("Mo'rt uzilish nuqtasi", "su", "rule", dashed=True)],
      x=("deformatsiya ε, %", "σ, MPa"), x_min="0", x_max="d_pl",
      readouts=[fr("Plastik: yutilgan energiya", "su*d_pl*10", "kJ/m³", "compress"),
                fr("Mo'rt: yutilgan energiya", "su^2/(2*210000)*1000", "kJ/m³", "tension"),
                fr("Nisbat", "su*d_pl*10/(su^2/(2*210000)*1000)", "marta", "mark")],
      note="Plastik material ogohlantirib uziladi va ancha ko'p energiya yutadi — shuning uchun xavfsizroq."),
 ],
 "mq-05": [
  fig("Zaxira koeffitsientini tanlash",
      "Yuk va material noaniqligi zaxirani belgilaydi.",
      params=[fp("sy", "Oqish chegarasi", 150, 900, 300, 10, "MPa"),
              fp("s_ish", "Ish kuchlanishi", 20, 400, 120, 5, "MPa")],
      curves=[fc("Zaxira n = σᵧ/σ", "sy/x", "tension"),
              fc("n = 1,5 chegara", "1.5", "rule", dashed=True),
              fc("n = 1 (oqish)", "1", "compress", dashed=True)],
      x=("ish kuchlanishi σ, MPa", "zaxira n"), x_min="20", x_max="400",
      readouts=[fr("Joriy zaxira", "sy/s_ish", "", "tension"),
                fr("Holat", "sy/s_ish - 1.5", "", "mark", text="yetarli|YETARLI EMAS"),
                fr("Ruxsat etilgan σ (n=1,5)", "sy/1.5", "MPa", "compress")],
      note="Zaxira 1 dan katta bo'lishining o'zi yetarli emas — normalar odatda 1,5 dan yuqorini talab qiladi."),
  fig("Mustahkamlik sharti: kerakli kesim",
      "Kuch oshsa kerakli yuza chiziqli o'sadi.",
      params=[fp("sall", "Ruxsat etilgan [σ]", 50, 300, 160, 5, "MPa")],
      curves=[fc("A_kerak = N/[σ]", "x*1000/(sall*1e6)*1e4", "tension"),
              fc("Mavjud 10 sm²", "10", "rule", dashed=True)],
      x=("kuch N, kN", "kerakli yuza, sm²"), x_min="0", x_max="400",
      readouts=[fr("A (N=100 kN)", "100*1000/(sall*1e6)*1e4", "sm²", "tension"),
                fr("10 sm² ko'taradigan N", "sall*1e6*10e-4/1000", "kN", "compress")],
      note="Loyihalashda kesim shu shartdan topiladi, so'ng standart profillardan kattarog'i tanlanadi."),
 ],
 "mq-06": [
  fig("Temperatura kuchlari: statik aniqmas sterjen",
      "Ikki uchi mahkamlangan sterjen isiganda kuchlanish paydo bo'ladi.",
      params=[fp("E", "Modul", 70, 220, 210, 5, "GPa"),
              fp("al", "Chiziqli kengayish α", 8, 25, 12, 0.5, "×10⁻⁶/°C")],
      curves=[fc("σ = αEΔT", "al*1e-6*E*1000*x", "tension"),
              fc("Oqish chegarasi 250 MPa", "250", "rule", dashed=True)],
      x=("temperatura o'zgarishi ΔT, °C", "σ, MPa"), x_min="0", x_max="120",
      readouts=[fr("σ (ΔT=50°C)", "al*1e-6*E*1000*50", "MPa", "tension"),
                fr("Oqishga yetadigan ΔT", "250/(al*1e-6*E*1000)", "°C", "mark"),
                fr("Kuchlanish UZUNLIKKA bog'liqmi", "0", "", "compress", text="ha|yo'q")],
      note="Temperatura kuchlanishi sterjen uzunligiga umuman bog'liq emas — faqat α, E va ΔT ga."),
  fig("Statik aniqmas tizim: kuchlarning qattiqlik bo'yicha taqsimlanishi",
      "Har bir sterjen o'z bikrligiga proporsional ulush oladi.",
      params=[fp("P", "Umumiy yuk", 10, 500, 120, 5, "kN"),
              fp("EA1", "Birinchi sterjen bikrligi", 1, 20, 5, 0.5, "MN")],
      curves=[fc("N₁ = P·EA₁/(EA₁+EA₂)", "P*EA1/(EA1 + x)", "tension"),
              fc("N₂ = P·EA₂/(EA₁+EA₂)", "P*x/(EA1 + x)", "compress"),
              fc("Yig'indi = P", "P", "rule", dashed=True)],
      x=("ikkinchi sterjen bikrligi EA₂, MN", "kuch, kN"), x_min="1", x_max="20",
      readouts=[fr("Teng bikrlikda N₁", "P/2", "kN", "mark"),
                fr("N₁ (EA₂=10)", "P*EA1/(EA1 + 10)", "kN", "tension"),
                fr("Nazorat N₁+N₂", "P", "kN", "rule")],
      note="Statik aniq tizimdan farqli, bu yerda kuch taqsimoti BIKRLIKKA bog'liq — deformatsiya sharti kerak."),
 ],
 "mq-07": [
  fig("Og'irlik markazi: ikki to'g'ri to'rtburchakdan iborat kesim",
      "Markaz kattaroq qismga yaqinroq yotadi.",
      params=[fp("A1", "Birinchi yuza", 1, 50, 12, 1, "sm²"),
              fp("y1", "Birinchi markaz", 0, 20, 2, 0.5, "sm"),
              fp("y2", "Ikkinchi markaz", 0, 30, 12, 0.5, "sm")],
      curves=[fc("y_c = (A₁y₁+A₂y₂)/(A₁+A₂)", "(A1*y1 + x*y2)/(A1 + x)", "tension"),
              fc("Birinchi markaz", "y1", "rule", dashed=True),
              fc("Ikkinchi markaz", "y2", "rule", dashed=True)],
      x=("ikkinchi yuza A₂, sm²", "og'irlik markazi y_c, sm"), x_min="1", x_max="50",
      readouts=[fr("y_c (A₂=A₁)", "(y1 + y2)/2", "sm", "mark"),
                fr("y_c (A₂=20)", "(A1*y1 + 20*y2)/(A1 + 20)", "sm", "tension"),
                fr("Statik moment nazorati", "0", "sm³", "compress")],
      note="Og'irlik markazida statik moment aynan nolga teng — bu markazning ta'rifi."),
  fig("Statik moment o'qqa bog'liq",
      "O'q markazdan uzoqlashgani sari statik moment chiziqli o'sadi.",
      params=[fp("A", "Kesim yuzasi", 2, 60, 20, 1, "sm²")],
      curves=[fc("S = A·d", "A*x", "tension"),
              fc("Markaziy o'qda S=0", "0", "compress", dashed=True)],
      x=("o'qning markazdan masofasi d, sm", "statik moment S, sm³"), x_min="-10", x_max="10",
      readouts=[fr("S (d=5 sm)", "A*5", "sm³", "tension"),
                fr("S markaziy o'qda", "0", "sm³", "compress"),
                fr("Ishora", "1", "", "mark", text="o'q tomoniga qarab|—")],
      note="Statik moment ishorali kattalik: o'qning qaysi tomonida yuza ko'p bo'lsa, o'sha ishora chiqadi."),
 ],
 "mq-08": [
  fig("Shteyner formulasi kesim uchun",
      "O'q markazdan siljisa inersiya momenti kvadratik o'sadi.",
      params=[fp("Ic", "Markaziy inersiya momenti", 10, 5000, 500, 10, "sm⁴"),
              fp("A", "Kesim yuzasi", 2, 100, 20, 1, "sm²")],
      curves=[fc("I = I_c + Ad²", "Ic + A*x^2", "tension"),
              fc("I_c (minimal)", "Ic", "rule", dashed=True),
              fc("Ad² qismi", "A*x^2", "compress", dashed=True)],
      x=("siljish d, sm", "I, sm⁴"), x_min="0", x_max="20",
      readouts=[fr("I (d=10 sm)", "Ic + A*100", "sm⁴", "tension"),
                fr("Ad² ulushi (d=10)", "100*A*100/(Ic + A*100)", "%", "compress"),
                fr("Ikki barobar bo'ladigan d", "sqrt(Ic/A)", "sm", "mark")],
      note="Katta d da Ad² hadi hukmron bo'ladi — shuning uchun dvutavrda javonlar chetga chiqariladi."),
  fig("To'rtburchak kesim: balandlik hal qiluvchi",
      "I = bh³/12 — balandlik kubga, kenglik esa chiziqli kiradi.",
      params=[fp("b", "Kenglik b", 1, 30, 10, 0.5, "sm")],
      curves=[fc("I = bh³/12", "b*x^3/12", "tension"),
              fc("W = bh²/6", "b*x^2/6", "compress")],
      x=("balandlik h, sm", "I, sm⁴  /  W, sm³"), x_min="0", x_max="40",
      readouts=[fr("I (h=20)", "b*8000/12", "sm⁴", "tension"),
                fr("h ikki barobar bo'lsa I", "8", "marta", "mark"),
                fr("b ikki barobar bo'lsa I", "2", "marta", "compress")],
      note="Shuning uchun taxta yotqizilgan emas, tik qo'yilgan holda ancha bikr bo'ladi."),
 ],
 "mq-09": [
  fig("Siljish deformatsiyasi va siljish moduli",
      "G = E/(2(1+ν)) — mustaqil emas, E va ν orqali ifodalanadi.",
      params=[fp("E", "Elastiklik moduli", 70, 220, 210, 5, "GPa")],
      curves=[fc("G = E/(2(1+ν))", "E/(2*(1 + x))", "tension"),
              fc("E/2 chegarasi (ν=0)", "E/2", "rule", dashed=True),
              fc("E/3 (ν=0,5)", "E/3", "compress", dashed=True)],
      x=("Puasson koeffitsienti ν", "G, GPa"), x_min="0", x_max="0.5",
      readouts=[fr("G (ν=0,3)", "E/2.6", "GPa", "tension"),
                fr("G/E nisbati", "1/2.6", "", "mark"),
                fr("Siyqilmaydigan material", "E/3", "GPa", "compress")],
      note="Po'lat uchun G ≈ 0,385E ≈ 81 GPa. ν = 0,5 (rezina) da G eng kichik qiymatga tushadi."),
  fig("Kesilishga hisob: boltning diametri",
      "τ = Q/A ≤ [τ]; diametr oshsa kuchlanish kvadratik kamayadi.",
      params=[fp("Q", "Kesuvchi kuch", 5, 200, 40, 1, "kN"),
              fp("tall", "Ruxsat etilgan [τ]", 40, 200, 90, 5, "MPa")],
      curves=[fc("τ = 4Q/(πd²)", "4*Q*1000/(pi*(x*1e-3)^2)/1e6", "tension"),
              fc("[τ]", "tall", "rule", dashed=True)],
      x=("bolt diametri d, mm", "τ, MPa"), x_min="5", x_max="40",
      readouts=[fr("Kerakli d", "sqrt(4*Q*1000/(pi*tall*1e6))*1000", "mm", "tension"),
                fr("τ (d=16 mm)", "4*Q*1000/(pi*(16e-3)^2)/1e6", "MPa", "compress"),
                fr("Ikki bolt bo'lsa d", "sqrt(4*Q*500/(pi*tall*1e6))*1000", "mm", "mark")],
      note="Ikkita boltga o'tish diametrni ikki barobar emas, atigi √2 marta kamaytiradi."),
 ],
 "mq-10": [
  fig("Buralishda urinma kuchlanish radius bo'ylab",
      "τ markazda nol, chetda maksimal — chiziqli taqsimot.",
      params=[fp("T", "Burovchi moment", 50, 5000, 800, 50, "N·m"),
              fp("d", "Val diametri", 10, 120, 40, 1, "mm")],
      curves=[fc("τ(r) = Tr/I_p", "T*x*1e-3/(pi*(d*1e-3)^4/32)/1e6", "tension"),
              fc("τ_max", "T*(d/2)*1e-3/(pi*(d*1e-3)^4/32)/1e6", "rule", dashed=True)],
      x=("radius r, mm", "τ, MPa"), x_min="0", x_max="d/2",
      readouts=[fr("τ_max (chetda)", "16*T/(pi*(d*1e-3)^3)/1e6", "MPa", "tension"),
                fr("Markazda", "0", "MPa", "compress"),
                fr("I_p", "pi*(d*1e-3)^4/32*1e12", "mm⁴", "mark")],
      note="Markazdagi material deyarli ishlamaydi — shuning uchun quvur to'la valdan samaraliroq."),
  fig("Quvur va to'la val: massa bo'yicha samaradorlik",
      "Ichki teshik massani kamaytiradi, qarshilikni esa kam yo'qotadi.",
      params=[fp("D", "Tashqi diametr", 20, 150, 60, 1, "mm")],
      curves=[fc("W_p quvur, sm³", "pi*(D*1e-3)^3*(1 - x^4)/16*1e6", "tension"),
              fc("W_p to'la val", "pi*(D*1e-3)^3/16*1e6", "rule", dashed=True),
              fc("Massa (1 m), kg", "7850*pi*(D*1e-3)^2*(1 - x^2)/4", "compress")],
      x=("ichki/tashqi diametr nisbati d/D", "W_p, sm³  /  massa, kg"), x_min="0", x_max="0.9",
      readouts=[fr("d/D=0,8: qarshilik", "1 - 0.8^4", "ulush", "tension"),
                fr("d/D=0,8: massa", "1 - 0.8^2", "ulush", "compress"),
                fr("Samaradorlik", "(1 - 0.8^4)/(1 - 0.8^2)", "marta", "mark")],
      note="d/D = 0,8 da qarshilikning 59% i saqlanadi, massa esa 36% ga tushadi — 1,6 barobar yutuq."),
 ],
 "mq-11": [
  fig("Statik aniqmas val: momentning bo'laklarga taqsimlanishi",
      "Har bir bo'lak burilish burchagi bo'yicha muvofiqlashadi.",
      params=[fp("T", "Tashqi moment", 100, 3000, 600, 50, "N·m"),
              fp("L", "Val uzunligi", 0.5, 4, 2, 0.1, "m")],
      curves=[fc("Chap reaksiya T_A", "T*(L - x)/L", "tension"),
              fc("O'ng reaksiya T_B", "T*x/L", "compress"),
              fc("Yig'indi = T", "T", "rule", dashed=True)],
      x=("moment qo'yilgan joy a, m", "reaksiya momenti, N·m"), x_min="0", x_max="L",
      readouts=[fr("T_A (a = 0,5 m)", "T*(L - 0.5)/L", "N·m", "rule"),
                fr("T_A (o'rtada)", "T/2", "N·m", "tension"),
                fr("T_B (o'rtada)", "T/2", "N·m", "compress"),
                fr("Nazorat T_A+T_B", "T", "N·m", "rule")],
      note="Moment mahkamlash joyiga qanchalik yaqin bo'lsa, o'sha reaksiya shuncha katta ulush oladi."),
  fig("Valni burilish burchagi bo'yicha loyihalash",
      "Mustahkamlikdan tashqari bikrlik sharti ham diametrni belgilaydi.",
      params=[fp("T", "Moment", 100, 3000, 800, 50, "N·m"),
              fp("G", "Siljish moduli", 25, 90, 81, 1, "GPa"),
              fp("L", "Uzunlik", 0.5, 4, 1.5, 0.1, "m")],
      curves=[fc("θ' = T/(GI_p), °/m", "T/(G*1e9*pi*(x*1e-3)^4/32)*180/pi", "tension"),
              fc("Ruxsat 0,5 °/m", "0.5", "rule", dashed=True)],
      x=("diametr d, mm", "solishtirma burilish, °/m"), x_min="15", x_max="90",
      readouts=[fr("θ' (d=40 mm)", "T/(G*1e9*pi*(40e-3)^4/32)*180/pi", "°/m", "tension"),
                fr("To'liq burilish (d=40)", "T/(G*1e9*pi*(40e-3)^4/32)*180/pi*L", "°", "compress"),
                fr("Bikrlik bo'yicha d", "(32*T*180/(G*1e9*pi^2*0.5))^0.25*1000", "mm", "mark")],
      note="Uzatma vallarida ko'pincha bikrlik sharti hal qiluvchi bo'ladi, mustahkamlik emas."),
 ],
 "mq-12": [
  fig("Sodda balka: kesuvchi kuch va eguvchi moment epyuralari",
      "Markazga qo'yilgan kuch uchburchak moment epyurasini beradi.",
      params=[fp("F", "Kuch", 5, 200, 50, 5, "kN"),
              fp("L", "Oraliq", 1, 10, 4, 0.5, "m")],
      curves=[fc("M(x) chap yarmi", "F*x/2", "tension"),
              fc("M(x) o'ng yarmi", "F*(L - x)/2", "compress"),
              fc("Nol chizig'i", "0", "rule", dashed=True)],
      x=("x, m", "eguvchi moment M, kN·m"), x_min="0", x_max="L",
      readouts=[fr("M_max (o'rtada)", "F*L/4", "kN·m", "tension"),
                fr("Q chap yarmida", "F/2", "kN", "compress"),
                fr("Q o'ng yarmida", "-F/2", "kN", "mark")],
      note="Kesuvchi kuch ishora o'zgargan joyda moment maksimumga chiqadi — bu Q = dM/dx dan kelib chiqadi."),
  fig("Tarqalgan yuk ostidagi balka",
      "Parabolik moment, chiziqli kesuvchi kuch.",
      params=[fp("q", "Tarqalgan yuk", 1, 60, 10, 1, "kN/m"),
              fp("L", "Oraliq", 1, 12, 6, 0.5, "m")],
      curves=[fc("M(x) = qx(L−x)/2", "q*x*(L - x)/2", "tension"),
              fc("Q(x) = q(L/2 − x)", "q*(L/2 - x)", "compress"),
              fc("Nol", "0", "rule", dashed=True)],
      x=("x, m", "M, kN·m  /  Q, kN"), x_min="0", x_max="L",
      readouts=[fr("M_max", "q*L^2/8", "kN·m", "tension"),
                fr("Q tayanchda", "q*L/2", "kN", "compress"),
                fr("M_max joyi", "L/2", "m", "mark")],
      note="qL²/8 — muhandislikda eng ko'p ishlatiladigan formula; uni yoddan bilish kerak."),
 ],
 "mq-13": [
  fig("Egilishda normal kuchlanish balandlik bo'ylab",
      "Neytral o'qda nol, chetlarda maksimal — chiziqli taqsimot.",
      params=[fp("M", "Eguvchi moment", 1, 200, 40, 1, "kN·m"),
              fp("b", "Kenglik", 5, 40, 12, 1, "sm"),
              fp("h", "Balandlik", 5, 60, 24, 1, "sm")],
      curves=[fc("σ(y) = My/I", "M*1000*x*1e-2/(b*1e-2*(h*1e-2)^3/12)/1e6", "tension"),
              fc("Neytral o'q", "0", "rule", dashed=True)],
      x=("neytral o'qdan masofa y, sm", "σ, MPa"), x_min="-h/2", x_max="h/2",
      readouts=[fr("σ_max", "M*1000*(h*1e-2/2)/(b*1e-2*(h*1e-2)^3/12)/1e6", "MPa", "tension"),
                fr("Qarshilik momenti W", "b*h^2/6", "sm³", "compress"),
                fr("Neytral o'qda σ", "0", "MPa", "mark")],
      note="Neytral o'q kesimning og'irlik markazidan o'tadi — bu N = 0 shartidan kelib chiqadi."),
  fig("Kesim balandligi va egilish kuchlanishi",
      "σ = 6M/(bh²) — balandlik kvadrat bo'lib kiradi.",
      params=[fp("M", "Moment", 1, 200, 40, 1, "kN·m"),
              fp("b", "Kenglik", 5, 40, 12, 1, "sm")],
      curves=[fc("σ_max = 6M/(bh²)", "6*M*1000/(b*1e-2*(x*1e-2)^2)/1e6", "tension"),
              fc("[σ] = 160 MPa", "160", "rule", dashed=True)],
      x=("balandlik h, sm", "σ_max, MPa"), x_min="5", x_max="60",
      readouts=[fr("σ (h=24 sm)", "6*M*1000/(b*1e-2*(24e-2)^2)/1e6", "MPa", "tension"),
                fr("Kerakli h ([σ]=160)", "sqrt(6*M*1000/(b*1e-2*160e6))*100", "sm", "compress"),
                fr("h 2× bo'lsa σ", "0.25", "marta", "mark")],
      note="Balandlikni ikki barobar oshirish kuchlanishni to'rt barobar kamaytiradi — juda samarali chora."),
 ],
 "mq-14": [
  fig("Juravskiy formulasi: urinma kuchlanish taqsimoti",
      "To'rtburchak kesimda parabola, neytral o'qda maksimal.",
      params=[fp("Q", "Kesuvchi kuch", 5, 300, 60, 5, "kN"),
              fp("b", "Kenglik", 5, 40, 12, 1, "sm"),
              fp("h", "Balandlik", 5, 60, 24, 1, "sm")],
      curves=[fc("τ(y) = 1,5Q/A·(1−4y²/h²)", "1.5*Q*1000/(b*h*1e-4)*(1 - 4*x^2/h^2)/1e6", "compress"),
              fc("O'rtacha τ = Q/A", "Q*1000/(b*h*1e-4)/1e6", "rule", dashed=True)],
      x=("y, sm", "τ, MPa"), x_min="-h/2", x_max="h/2",
      readouts=[fr("τ_max (neytral o'qda)", "1.5*Q*1000/(b*h*1e-4)/1e6", "MPa", "compress"),
                fr("O'rtacha τ", "Q*1000/(b*h*1e-4)/1e6", "MPa", "rule"),
                fr("Chetlarda τ", "0", "MPa", "tension")],
      note="τ_max o'rtachadan aynan 1,5 marta katta — bu to'rtburchak kesimning o'ziga xos koeffitsienti."),
  fig("Qachon urinma kuchlanish muhim bo'ladi",
      "Qisqa balkada τ normal kuchlanish bilan raqobatlashadi.",
      params=[fp("h", "Balandlik", 10, 60, 30, 1, "sm")],
      curves=[fc("σ_max/τ_max nisbati", "2*x*100/h", "tension"),
              fc("Nisbat = 10", "10", "rule", dashed=True)],
      x=("oraliq L, m", "σ_max / τ_max"), x_min="0.2", x_max="10",
      readouts=[fr("Nisbat (L=1 m)", "2*100/h", "", "tension"),
                fr("Nisbat (L=6 m)", "12*100/h", "", "compress"),
                fr("τ hisobga olinsinmi (L=1)", "2*100/h - 10", "", "mark", text="yo'q|HA")],
      note="Nisbat 4L/h ga teng va YUKKA umuman bog'liq emas — q surat va maxrajda qisqaradi. L/h < 5 bo'lganda urinma kuchlanishni tekshirish shart: yog'och va yupqa devorli balkalarda ayniqsa."),
 ],
 "mq-15": [
  fig("Egilgan o'q: bikrlik va oraliq ta'siri",
      "f = 5qL⁴/(384EI) — oraliq to'rtinchi darajada kiradi.",
      params=[fp("q", "Yuk", 1, 60, 10, 1, "kN/m"),
              fp("E", "Modul", 10, 220, 210, 5, "GPa"),
              fp("I", "Inersiya momenti", 100, 50000, 5000, 100, "sm⁴")],
      curves=[fc("f = 5qL⁴/(384EI), mm", "5*q*1000*x^4/(384*E*1e9*I*1e-8)*1000", "tension"),
              fc("Ruxsat L/250", "x/250*1000", "rule", dashed=True)],
      x=("oraliq L, m", "salqilik f, mm"), x_min="0", x_max="10",
      readouts=[fr("f (L=6 m)", "5*q*1000*1296/(384*E*1e9*I*1e-8)*1000", "mm", "tension"),
                fr("Ruxsat (L=6)", "24", "mm", "compress"),
                fr("Chegaraviy L", "(384*E*1e9*I*1e-8/(250*5*q*1000))^(1/3)", "m", "mark")],
      note="Oraliq ikki barobar oshsa salqilik 16 barobar oshadi — shuning uchun uzun balkalar bikrlik bo'yicha hisoblanadi."),
  fig("Egilish chizig'ining shakli",
      "Tarqalgan yuk ostida o'q to'rtinchi darajali egri chiziq bo'ladi.",
      params=[fp("fm", "O'rtadagi salqilik", 1, 60, 20, 1, "mm"),
             fp("L", "Oraliq", 1, 12, 6, 0.5, "m")],
      curves=[fc("w(x) sodda balka", "fm*16/5*(x/L - 2*(x/L)^3 + (x/L)^4)", "tension"),
              fc("Nol chizig'i", "0", "rule", dashed=True)],
      x=("x, m", "ko'chish w, mm"), x_min="0", x_max="L",
      readouts=[fr("Egrilik radiusi o'rtada", "L^2/(9.6*fm*1e-3)", "m", "rule"),
                fr("w o'rtada", "fm", "mm", "tension"),
                fr("w chorakda", "fm*16/5*(0.25 - 2*0.015625 + 0.00390625)", "mm", "compress"),
                fr("Chorak/o'rta nisbati", "16/5*(0.25 - 0.03125 + 0.00390625)", "", "mark")],
      note="Chorak nuqtadagi ko'chish o'rtadagining 71% ini tashkil qiladi — egri chiziq juda yassi."),
 ],
 "mq-16": [
  fig("Konsol balka: yuk joyi va uch nuqta ko'chishi",
      "Kuch uchga yaqinlashgani sari ko'chish keskin oshadi.",
      params=[fp("F", "Kuch", 1, 100, 20, 1, "kN"),
              fp("L", "Konsol uzunligi", 0.5, 6, 3, 0.1, "m"),
              fp("EI", "Bikrlik", 100, 20000, 4000, 100, "kN·m²")],
      curves=[fc("w_uch = Fa²(3L−a)/(6EI), mm", "F*x^2*(3*L - x)/(6*EI)*1000", "tension"),
              fc("Uchga qo'yilganda", "F*L^3/(3*EI)*1000", "rule", dashed=True)],
      x=("kuch joyi a, m", "uch ko'chishi, mm"), x_min="0", x_max="L",
      readouts=[fr("w (a=L)", "F*L^3/(3*EI)*1000", "mm", "tension"),
                fr("w (a=L/2)", "F*(L/2)^2*(3*L - L/2)/(6*EI)*1000", "mm", "compress"),
                fr("Nisbat", "(L/2)^2*(2.5*L)/(2*L^3)", "", "mark")],
      note="Kuchni o'rtaga surish uch ko'chishini 5/16 = 0,31 marta kamaytiradi, ya'ni uch barobardan ko'proq."),
  fig("Mor integrali: birlik kuch usuli",
      "Ko'chish ikki moment epyurasining ko'paytmasi integrali.",
      params=[fp("q", "Yuk", 1, 60, 12, 1, "kN/m"),
              fp("EI", "Bikrlik", 100, 20000, 5000, 100, "kN·m²")],
      curves=[fc("δ = 5qL⁴/(384EI), mm", "5*q*x^4/(384*EI)*1000", "tension"),
              fc("Konsol: qL⁴/(8EI)", "q*x^4/(8*EI)*1000", "compress")],
      x=("uzunlik L, m", "ko'chish, mm"), x_min="0", x_max="8",
      readouts=[fr("Sodda balka (L=6)", "5*q*1296/(384*EI)*1000", "mm", "tension"),
                fr("Konsol (L=6)", "q*1296/(8*EI)*1000", "mm", "compress"),
                fr("Konsol/sodda", "48/5", "marta", "mark")],
      note="Bir xil yuk va uzunlikda konsol sodda balkadan 9,6 marta ko'proq egiladi."),
 ],
 "mq-17": [
  fig("Statik aniqmas balka: tayanch momenti",
      "Qo'shimcha tayanch oraliq momentini keskin kamaytiradi.",
      params=[fp("q", "Yuk", 1, 60, 12, 1, "kN/m")],
      curves=[fc("Sodda balka M_max = qL²/8", "q*x^2/8", "tension"),
              fc("Ikki uchi qistirilgan: qL²/24", "q*x^2/24", "compress"),
              fc("Qistirilgan tayanchda: qL²/12", "q*x^2/12", "mark", dashed=True)],
      x=("oraliq L, m", "M, kN·m"), x_min="0", x_max="10",
      readouts=[fr("Sodda (L=6)", "q*36/8", "kN·m", "tension"),
                fr("Qistirilgan oraliq (L=6)", "q*36/24", "kN·m", "compress"),
                fr("Kamayish", "3", "marta", "mark")],
      note="Qistirish oraliq momentini 3 marta kamaytiradi, lekin tayanchda qL²/12 moment paydo bo'ladi."),
  fig("Ortiqcha bog'lanish reaksiyasi",
      "Uchinchi tayanch bikrligi kuch taqsimotini o'zgartiradi.",
      params=[fp("q", "Yuk", 1, 60, 12, 1, "kN/m"),
              fp("L", "Oraliq", 2, 12, 6, 0.5, "m")],
      curves=[fc("O'rta tayanch reaksiyasi, kN", "5*q*L/8*x", "tension"),
              fc("Sodda balka (tayanchsiz)", "0", "rule", dashed=True)],
      x=("tayanch bikrligi ulushi", "reaksiya R, kN"), x_min="0", x_max="1",
      readouts=[fr("To'liq bikr tayanch", "5*q*L/8", "kN", "tension"),
                fr("Chekka reaksiyalar", "3*q*L/16", "kN", "compress"),
                fr("Umumiy yuk", "q*L", "kN", "rule")],
      note="Cheksiz bikr o'rta tayanch yukning 5/8 ini oladi — statik aniqmaslikning klassik natijasi."),
 ],
 "mq-18": [
  fig("Kesim shakllarining samaradorligi",
      "Bir xil yuzada W keskin farq qiladi.",
      params=[fp("A", "Kesim yuzasi", 10, 100, 40, 1, "sm²")],
      curves=[fc("Doira: W = A^1.5/(4√π)", "x^1.5/(4*sqrt(pi))", "compress"),
              fc("Kvadrat: W = A^1.5/6", "x^1.5/6", "mark"),
              fc("Dvutavr (taxminiy)", "0.35*x^1.5", "tension"),
              fc("Joriy A dagi dvutavr", "0.35*A^1.5", "rule", dashed=True)],
      x=("yuza A, sm²", "W, sm³"), x_min="10", x_max="100",
      readouts=[fr("Doira (A=40)", "40^1.5/(4*sqrt(pi))", "sm³", "compress"),
                fr("Kvadrat (A=40)", "40^1.5/6", "sm³", "mark"),
                fr("Dvutavr/doira", "0.35*4*sqrt(pi)", "marta", "tension")],
      note="Dvutavr bir xil massada doiradan ~2,5 marta ko'p qarshilik beradi — material chetga chiqarilgani uchun."),
  fig("Teng mustahkam balka: o'zgaruvchan balandlik",
      "Har bir kesimda σ = [σ] bo'lsa material minimal sarflanadi.",
      params=[fp("F", "Uchdagi kuch", 1, 100, 20, 1, "kN"),
              fp("b", "Kenglik", 5, 30, 10, 1, "sm"),
              fp("sall", "[σ]", 50, 250, 160, 5, "MPa")],
      curves=[fc("h(x) teng mustahkam", "sqrt(6*F*1000*x/(b*1e-2*sall*1e6))*100", "tension"),
              fc("Doimiy balandlik", "sqrt(6*F*1000*3/(b*1e-2*sall*1e6))*100", "rule", dashed=True)],
      x=("mahkamlashdan masofa x, m", "kerakli balandlik h, sm"), x_min="0", x_max="3",
      readouts=[fr("h mahkamlashda", "sqrt(6*F*1000*3/(b*1e-2*sall*1e6))*100", "sm", "tension"),
                fr("h o'rtada", "sqrt(6*F*1000*1.5/(b*1e-2*sall*1e6))*100", "sm", "compress"),
                fr("Material tejash", "33.3", "%", "mark")],
      note="Parabolik konsol doimiy kesimga nisbatan 1/3 material tejaydi — samolyot qanotlari shu tamoyilda."),
 ],
 "mq-19": [
  fig("Mor doirasi: asosiy kuchlanishlar",
      "Burchak o'zgarganda normal kuchlanish sinusoidal o'zgaradi.",
      params=[fp("sx", "σx", -200, 200, 80, 5, "MPa"),
              fp("sy", "σy", -200, 200, -40, 5, "MPa"),
              fp("txy", "τxy", -150, 150, 50, 5, "MPa")],
      curves=[fc("σ(α)", "(sx+sy)/2 + (sx-sy)/2*cos(2*x*pi/180) + txy*sin(2*x*pi/180)", "tension"),
              fc("τ(α)", "-(sx-sy)/2*sin(2*x*pi/180) + txy*cos(2*x*pi/180)", "compress"),
              fc("O'rtacha", "(sx+sy)/2", "rule", dashed=True)],
      x=("maydon burchagi α, °", "kuchlanish, MPa"), x_min="0", x_max="180",
      readouts=[fr("σ₁", "(sx+sy)/2 + sqrt(((sx-sy)/2)^2 + txy^2)", "MPa", "tension"),
                fr("σ₂", "(sx+sy)/2 - sqrt(((sx-sy)/2)^2 + txy^2)", "MPa", "compress"),
                fr("τ_max", "sqrt(((sx-sy)/2)^2 + txy^2)", "MPa", "mark"),
                fr("Asosiy burchak", "0.5*atan2(2*txy, sx-sy)*180/pi", "°", "rule")],
      note="Asosiy maydonda τ = 0. Invariant σx+σy burchakka bog'liq emas — bu Mor doirasining markazi."),
  fig("Sof siljish: cho'zilish va siqilish 45° da",
      "Buralishdagi val aynan shu holatda ishlaydi.",
      params=[fp("t", "Urinma kuchlanish τ", 10, 200, 80, 5, "MPa")],
      curves=[fc("σ(α)", "t*sin(2*x*pi/180)", "tension"),
              fc("τ(α)", "t*cos(2*x*pi/180)", "compress"),
              fc("Nol", "0", "rule", dashed=True)],
      x=("burchak α, °", "kuchlanish, MPa"), x_min="0", x_max="180",
      readouts=[fr("σ₁ (45° da)", "t", "MPa", "tension"),
                fr("σ₂ (135° da)", "-t", "MPa", "compress"),
                fr("O'rtacha kuchlanish", "0", "MPa", "rule")],
      note="Shuning uchun buralgan bo'r 45° spiral bo'ylab uziladi — mo'rt material cho'zilishdan buziladi."),
 ],
 "mq-20": [
  fig("Umumlashgan Guk qonuni: ko'ndalang deformatsiya",
      "Bir o'q bo'ylab cho'zilish boshqa o'qlarda siqilish beradi.",
      params=[fp("sx", "σx", 0, 300, 120, 5, "MPa"),
              fp("E", "Modul", 70, 220, 210, 5, "GPa")],
      curves=[fc("εx = σx/E", "sx/(E*1000)*1000", "tension"),
              fc("εy = −νσx/E", "-x*sx/(E*1000)*1000", "compress"),
              fc("Nol", "0", "rule", dashed=True)],
      x=("Puasson koeffitsienti ν", "deformatsiya, ‰"), x_min="0", x_max="0.5",
      readouts=[fr("εx", "sx/(E*1000)*1000", "‰", "tension"),
                fr("εy (ν=0,3)", "-0.3*sx/(E*1000)*1000", "‰", "compress"),
                fr("Hajm o'zgarishi (ν=0,3)", "0.4*sx/(E*1000)*1000", "‰", "mark")],
      note="ν = 0,5 da hajm umuman o'zgarmaydi — bu siyqilmaydigan material (rezina) holati."),
  fig("Hajmiy deformatsiya va hajmiy modul",
      "K = E/(3(1−2ν)) — ν 0,5 ga yaqinlashganda cheksizga intiladi.",
      params=[fp("E", "Modul", 70, 220, 210, 5, "GPa")],
      curves=[fc("K = E/(3(1−2ν))", "E/(3*(1 - 2*x))", "tension"),
              fc("E darajasi", "E", "rule", dashed=True)],
      x=("ν", "hajmiy modul K, GPa"), x_min="0", x_max="0.45",
      readouts=[fr("K (ν=0,3)", "E/1.2", "GPa", "tension"),
                fr("K (ν=0,45)", "E/0.3", "GPa", "compress"),
                fr("K/E (ν=0,3)", "1/1.2", "", "mark")],
      note="Po'lat uchun K ≈ 175 GPa. Suyuqliklarda ν → 0,5 va K juda katta: ular deyarli siqilmaydi."),
 ],
 "mq-21": [
  fig("Mustahkamlik nazariyalarini taqqoslash",
      "Bir xil kuchlanish holatida nazariyalar turli ekvivalent qiymat beradi.",
      params=[fp("s", "Normal kuchlanish σ", 0, 300, 100, 5, "MPa")],
      curves=[fc("Mizes: √(σ²+3τ²)", "sqrt(s^2 + 3*x^2)", "tension"),
              fc("Treska: √(σ²+4τ²)", "sqrt(s^2 + 4*x^2)", "compress"),
              fc("[σ] = 160 MPa", "160", "rule", dashed=True)],
      x=("urinma kuchlanish τ, MPa", "ekvivalent kuchlanish, MPa"), x_min="0", x_max="150",
      readouts=[fr("Mizes (τ=60)", "sqrt(s^2 + 3*3600)", "MPa", "tension"),
                fr("Treska (τ=60)", "sqrt(s^2 + 4*3600)", "MPa", "compress"),
                fr("Farq", "100*(sqrt(s^2+4*3600)/sqrt(s^2+3*3600) - 1)", "%", "mark")],
      note="Treska har doim xavfsizroq (konservativ) tomonga xato qiladi; Mizes tajribaga yaqinroq."),
  fig("Sof siljishda ruxsat etilgan urinma kuchlanish",
      "[τ] nazariyaga qarab [σ] ning 0,5 yoki 0,577 ulushi bo'ladi.",
      params=[fp("sall", "[σ]", 60, 300, 160, 5, "MPa")],
      curves=[fc("Mizes: [τ] = [σ]/√3", "sall/sqrt(3) + 0*x", "tension"),
              fc("Treska: [τ] = [σ]/2", "sall/2 + 0*x", "compress")],
      x=("shartli o'q", "[τ], MPa"), x_min="0", x_max="1",
      readouts=[fr("Mizes [τ]", "sall/sqrt(3)", "MPa", "tension"),
                fr("Treska [τ]", "sall/2", "MPa", "compress"),
                fr("Nisbat", "2/sqrt(3)", "marta", "mark")],
      note="Farq 15,5% — buralgan vallarni loyihalashda bu sezilarli zaxira farqini beradi."),
 ],
 "mq-22": [
  fig("Qiyshiq egilish: ikki tekislikdagi momentlar qo'shiladi",
      "Burchak o'zgarganda kuchlanish keskin oshadi.",
      params=[fp("M", "To'liq moment", 1, 100, 20, 1, "kN·m"),
              fp("Wx", "Wx", 10, 2000, 400, 10, "sm³"),
              fp("Wy", "Wy", 5, 500, 80, 5, "sm³")],
      curves=[fc("σ = M(cosφ/Wx + sinφ/Wy)", "M*1000*(cos(x*pi/180)/(Wx*1e-6) + sin(x*pi/180)/(Wy*1e-6))/1e6", "tension"),
              fc("Faqat Wx bo'yicha", "M*1000/(Wx*1e-6)/1e6", "rule", dashed=True)],
      x=("og'ish burchagi φ, °", "σ_max, MPa"), x_min="0", x_max="45",
      readouts=[fr("σ (φ=0)", "M*1000/(Wx*1e-6)/1e6", "MPa", "rule"),
                fr("σ (φ=5°)", "M*1000*(cos(5*pi/180)/(Wx*1e-6) + sin(5*pi/180)/(Wy*1e-6))/1e6", "MPa", "tension"),
                fr("Oshish", "100*(cos(5*pi/180) + sin(5*pi/180)*Wx/Wy - 1)", "%", "mark")],
      note="Atigi 5° og'ish dvutavrda kuchlanishni 40% dan ko'proq oshiradi — shuning uchun yon ushlagichlar qo'yiladi."),
  fig("Ekssentrik siqilish: kesim yadrosi",
      "Ekssentrisitet chegaradan oshsa cho'zilish paydo bo'ladi.",
      params=[fp("N", "Siquvchi kuch", 10, 500, 100, 5, "kN"),
              fp("b", "Kenglik", 10, 60, 30, 1, "sm"),
              fp("h", "Balandlik", 10, 60, 30, 1, "sm")],
      curves=[fc("σ_min = −N/A(1 − 6e/h)", "-N*1000/(b*h*1e-4)*(1 - 6*x/h)/1e6", "compress"),
              fc("σ_max", "-N*1000/(b*h*1e-4)*(1 + 6*x/h)/1e6", "tension"),
              fc("Nol (cho'zilish chegarasi)", "0", "rule", dashed=True)],
      x=("ekssentrisitet e, sm", "σ, MPa"), x_min="0", x_max="h/3",
      readouts=[fr("Yadro chegarasi h/6", "h/6", "sm", "mark"),
                fr("σ_min (e=h/6)", "0", "MPa", "rule"),
                fr("σ_max (e=h/6)", "-2*N*1000/(b*h*1e-4)/1e6", "MPa", "compress")],
      note="Yadrodan tashqaridagi kuch beton va g'ishtda darz keltiradi — shuning uchun 'uchdan bir qoidasi' muhim."),
 ],
 "mq-23": [
  fig("Egilish va buralish: ekvivalent moment",
      "Val ikkala ta'sirni birga ko'taradi.",
      params=[fp("M", "Eguvchi moment", 0, 2000, 400, 10, "N·m"),
              fp("d", "Val diametri", 15, 120, 45, 1, "mm")],
      curves=[fc("Mizes ekvivalent", "sqrt(M^2 + 0.75*x^2)/(pi*(d*1e-3)^3/32)/1e6", "tension"),
              fc("Faqat egilish", "M/(pi*(d*1e-3)^3/32)/1e6", "rule", dashed=True),
              fc("Treska ekvivalent", "sqrt(M^2 + x^2)/(pi*(d*1e-3)^3/32)/1e6", "compress")],
      x=("burovchi moment T, N·m", "σ_ekv, MPa"), x_min="0", x_max="2000",
      readouts=[fr("σ_ekv (T=600, Mizes)", "sqrt(M^2 + 0.75*360000)/(pi*(d*1e-3)^3/32)/1e6", "MPa", "tension"),
                fr("Treska (T=600)", "sqrt(M^2 + 360000)/(pi*(d*1e-3)^3/32)/1e6", "MPa", "compress"),
                fr("Kerakli d ([σ]=80, Mizes)", "(32*sqrt(M^2+0.75*360000)/(pi*80e6))^(1/3)*1000", "mm", "mark")],
      note="Redukторlar valida egilish va buralish deyarli har doim birga keladi — alohida hisob xato beradi."),
  fig("Val diametrining ekvivalent momentga bog'liqligi",
      "Diametr moment kub ildizi bo'yicha o'sadi.",
      params=[fp("sall", "[σ]", 40, 200, 80, 5, "MPa")],
      curves=[fc("d = (32M_ekv/(π[σ]))^(1/3)", "(32*x/(pi*sall*1e6))^(1/3)*1000", "tension"),
              fc("Standart 40 mm", "40", "rule", dashed=True)],
      x=("ekvivalent moment M_ekv, N·m", "kerakli d, mm"), x_min="50", x_max="4000",
      readouts=[fr("d (M=800 N·m)", "(32*800/(pi*sall*1e6))^(1/3)*1000", "mm", "tension"),
                fr("Moment 8× bo'lsa d", "2", "marta", "mark"),
                fr("40 mm ko'taradigan M", "pi*sall*1e6*(40e-3)^3/32", "N·m", "compress")],
      note="Momentni 8 barobar oshirish diametrni faqat 2 barobar oshirishni talab qiladi — kub bog'liqlik."),
 ],
 "mq-24": [
  fig("Deformatsiya energiyasi va zarbiy xavfsizlik",
      "Yumshoq element ko'proq energiya yutadi.",
      params=[fp("F", "Kuch", 1, 100, 20, 1, "kN")],
      curves=[fc("U = F²/(2k), J", "F^2*1e6/(2*x*1e6)", "tension"),
              fc("Ko'chish δ = F/k, mm", "F*1000/(x*1e6)*1000", "compress")],
      x=("bikrlik k, MN/m", "U, J  /  δ, mm"), x_min="1", x_max="50",
      readouts=[fr("U (k=10 MN/m)", "F^2*1e6/(2*10*1e6)", "J", "tension"),
                fr("U (k=40 MN/m)", "F^2*1e6/(2*40*1e6)", "J", "compress"),
                fr("Nisbat", "4", "marta", "mark")],
      note="Bikrlikni 4 barobar oshirish energiya sig'imini 4 barobar kamaytiradi — zarbga chidamlilik pasayadi."),
  fig("Kastilyano teoremasi: ko'chish energiya hosilasi",
      "∂U/∂F = δ — energiya usuli ko'chishni to'g'ridan-to'g'ri beradi.",
      params=[fp("L", "Uzunlik", 0.5, 5, 2, 0.1, "m"),
              fp("EI", "Bikrlik", 100, 20000, 3000, 100, "kN·m²")],
      curves=[fc("U = F²L³/(6EI), J", "x^2*L^3/(6*EI)*1000", "tension"),
              fc("δ = FL³/(3EI), mm", "x*L^3/(3*EI)*1000", "compress")],
      x=("kuch F, kN", "U, J  /  δ, mm"), x_min="0", x_max="50",
      readouts=[fr("U (F=20 kN)", "400*L^3/(6*EI)*1000", "J", "tension"),
                fr("δ (F=20 kN)", "20*L^3/(3*EI)*1000", "mm", "compress"),
                fr("Nazorat 2U/F = δ", "2*400*L^3/(6*EI)*1000/20", "mm", "mark")],
      note="Chiziqli tizimda U = Fδ/2, shuning uchun 2U/F aynan δ ga teng — nazorat sifatida ishlatiladi."),
 ],
 "mq-25": [
  fig("Eyler kritik kuchi va sterjen uzunligi",
      "Kritik kuch uzunlik kvadratiga teskari proporsional.",
      params=[fp("E", "Modul", 70, 220, 210, 5, "GPa"),
              fp("I", "Minimal inersiya momenti", 5, 2000, 100, 5, "sm⁴")],
      curves=[fc("F_kr = π²EI/L²", "pi^2*E*1e9*I*1e-8/x^2/1000", "tension"),
              fc("Ishchi yuk 50 kN", "50", "rule", dashed=True)],
      x=("sterjen uzunligi L, m", "kritik kuch F_kr, kN"), x_min="0.5", x_max="8",
      readouts=[fr("F_kr (L=3 m)", "pi^2*E*1e9*I*1e-8/9/1000", "kN", "tension"),
                fr("L 2× bo'lsa F_kr", "0.25", "marta", "mark"),
                fr("50 kN uchun L_max", "sqrt(pi^2*E*1e9*I*1e-8/50000)", "m", "compress")],
      note="Ustuvorlik mustahkamlikdan mustaqil: F_kr da material umuman oqish chegarasiga yetmagan bo'lishi mumkin."),
  fig("Mahkamlash usuli va keltirilgan uzunlik",
      "μ koeffitsienti kritik kuchni 16 barobargacha o'zgartiradi.",
      params=[fp("EI", "Bikrlik", 10, 5000, 200, 10, "kN·m²"),
              fp("L", "Geometrik uzunlik", 0.5, 8, 3, 0.1, "m")],
      curves=[fc("F_kr = π²EI/(μL)²", "pi^2*EI/(x*L)^2", "tension"),
              fc("Sharnirli (μ=1)", "pi^2*EI/L^2", "rule", dashed=True)],
      x=("keltirish koeffitsienti μ", "F_kr, kN"), x_min="0.5", x_max="2",
      readouts=[fr("Ikki uchi qistirilgan (μ=0,5)", "pi^2*EI/(0.5*L)^2", "kN", "tension"),
                fr("Sharnirli (μ=1)", "pi^2*EI/L^2", "kN", "rule"),
                fr("Konsol (μ=2)", "pi^2*EI/(2*L)^2", "kN", "compress")],
      note="Qistirilgan sterjen konsoldan 16 marta ko'p ko'taradi — mahkamlash ustuvorlikda hal qiluvchi."),
 ],
 "mq-26": [
  fig("Eyler formulasi qayerda ishlaydi",
      "Kichik moslikda formula haqiqatdan uzoqlashadi.",
      params=[fp("E", "Modul", 70, 220, 210, 5, "GPa"),
              fp("sy", "Oqish chegarasi", 150, 600, 250, 10, "MPa")],
      curves=[fc("Eyler: π²E/λ²", "pi^2*E*1000/x^2", "tension"),
              fc("Oqish chegarasi", "sy", "rule", dashed=True),
              fc("Yasinskiy (taxminiy)", "sy - 1.1*x", "compress")],
      x=("moslik λ", "kritik kuchlanish, MPa"), x_min="20", x_max="200",
      readouts=[fr("Chegaraviy λ_pr", "pi*sqrt(E*1000/sy)", "", "mark"),
                fr("σ_kr (λ=100)", "pi^2*E*1000/10000", "MPa", "tension"),
                fr("λ=50 da Eyler", "pi^2*E*1000/2500", "MPa", "compress")],
      note="λ < λ_pr da Eyler formulasi oqish chegarasidan katta qiymat beradi — bu fizik jihatdan mumkin emas."),
  fig("Ustuvorlik koeffitsienti φ bo'yicha hisob",
      "Amaliy hisobda [σ] ga φ ko'paytiriladi.",
      params=[fp("sall", "[σ]", 60, 300, 160, 5, "MPa"),
              fp("A", "Kesim yuzasi", 5, 100, 25, 1, "sm²")],
      curves=[fc("Ruxsat etilgan kuch φ[σ]A, kN", "(1 - 0.0045*x)*sall*A*1e-4*1e6/1000", "tension"),
              fc("Ustuvorliksiz [σ]A", "sall*A*1e-4*1e6/1000", "rule", dashed=True)],
      x=("moslik λ", "ruxsat etilgan kuch, kN"), x_min="0", x_max="150",
      readouts=[fr("λ=0 da", "sall*A*1e-4*1e6/1000", "kN", "rule"),
                fr("λ=100 da", "0.55*sall*A*1e-4*1e6/1000", "kN", "tension"),
                fr("Yo'qotish", "45", "%", "mark")],
      note="Chiziqli φ(λ) — soddalashtirilgan model. Real normalarda φ jadvaldan material bo'yicha olinadi."),
 ],
 "mq-27": [
  fig("Dinamiklik koeffitsienti va tushish balandligi",
      "Zarbda kuchlanish statikdan bir necha barobar oshadi.",
      params=[fp("dst", "Statik ko'chish", 0.05, 20, 1, 0.05, "mm")],
      curves=[fc("k_d = 1 + √(1 + 2h/δ_st)", "1 + sqrt(1 + 2*x/(dst*1e-3))", "tension"),
              fc("Statik daraja", "1", "rule", dashed=True)],
      x=("tushish balandligi h, m", "dinamiklik koeffitsienti k_d"), x_min="0", x_max="1",
      readouts=[fr("k_d (h=0,1 m)", "1 + sqrt(1 + 0.2/(dst*1e-3))", "", "tension"),
                fr("k_d (h=0)", "2", "", "compress"),
                fr("Yumshoqroq (δ=4 mm)", "1 + sqrt(1 + 0.2/4e-3)", "", "mark")],
      note="h = 0 da ham k_d = 2 — yukni birdan qo'yish statik qo'yishdan ikki barobar xavfli."),
  fig("Yumshoq tayanch zarbni kamaytiradi",
      "Bikrlik kamaysa dinamiklik koeffitsienti tushadi.",
      params=[fp("h", "Tushish balandligi", 0.01, 1, 0.2, 0.01, "m"),
              fp("m", "Yuk massasi", 5, 500, 50, 5, "kg"),
              fp("sst", "Statik kuchlanish", 1, 100, 20, 1, "MPa")],
      curves=[fc("σ_d = σ_st·k_d", "sst*(1 + sqrt(1 + 2*h/(x*1e-3)))", "tension"),
              fc("Statik", "sst", "rule", dashed=True),
              fc("[σ]=160", "160", "compress", dashed=True)],
      x=("statik ko'chish δ_st, mm", "σ_d, MPa"), x_min="0.1", x_max="20",
      readouts=[fr("σ_d (δ=1 mm)", "sst*(1 + sqrt(1 + 2*h/1e-3))", "MPa", "tension"),
                fr("σ_d (δ=10 mm)", "sst*(1 + sqrt(1 + 2*h/1e-2))", "MPa", "compress"),
                fr("Zarb energiyasi", "m*9.81*h", "J", "mark")],
      note="Rezina amortizator δ_st ni 10 barobar oshirib zarb kuchlanishini ~3 barobar kamaytiradi."),
 ],
 "mq-28": [
  fig("Veler egri chizig'i: sikllar soni va amplituda",
      "Chidamlilik chegarasidan past amplitudada detal cheksiz ishlaydi.",
      params=[fp("su", "Mustahkamlik chegarasi", 300, 1200, 600, 10, "MPa")],
      curves=[fc("σ_a = σ_u·N^(−0,1)", "su*(10^x)^(-0.1)", "tension"),
              fc("Chidamlilik chegarasi 0,5σ_u", "0.5*su", "rule", dashed=True)],
      x=("lg N (sikllar soni)", "amplituda σ_a, MPa"), x_min="3", x_max="7",
      readouts=[fr("σ_a (N=10⁵)", "su*(1e5)^(-0.1)", "MPa", "tension"),
                fr("σ_a (N=10⁶)", "su*(1e6)^(-0.1)", "MPa", "compress"),
                fr("σ_−1 (0,5σ_u)", "0.5*su", "MPa", "mark")],
      note="Po'latda 10⁷ sikldan keyin egri chiziq yassilanadi — bu haqiqiy chidamlilik chegarasi."),
  fig("O'rtacha kuchlanish ta'siri: Gudman diagrammasi",
      "Doimiy cho'zilish ruxsat etilgan amplitudani kamaytiradi.",
      params=[fp("sm1", "Chidamlilik chegarasi σ₋₁", 100, 500, 250, 10, "MPa"),
              fp("su", "Mustahkamlik σ_u", 300, 1200, 600, 10, "MPa")],
      curves=[fc("Gudman: σ_a = σ₋₁(1 − σ_m/σ_u)", "sm1*(1 - x/su)", "tension"),
              fc("Soderberg (σᵧ=0,6σ_u)", "sm1*(1 - x/(0.6*su))", "compress"),
              fc("Nol", "0", "rule", dashed=True)],
      x=("o'rtacha kuchlanish σ_m, MPa", "ruxsat etilgan amplituda, MPa"), x_min="0", x_max="su",
      readouts=[fr("σ_a (σ_m=0)", "sm1", "MPa", "tension"),
                fr("σ_a (σ_m=200)", "sm1*(1 - 200/su)", "MPa", "compress"),
                fr("Kamayish", "100*200/su", "%", "mark")],
      note="Soderberg konservativroq: u oqish chegarasiga tayanadi va plastik deformatsiyaga yo'l qo'ymaydi."),
 ],
 "mq-29": [
  fig("Teshik atrofida kuchlanish konsentratsiyasi",
      "Cheksiz plastinadagi dumaloq teshik koeffitsienti 3 ga teng.",
      params=[fp("s0", "Nominal kuchlanish", 10, 200, 60, 5, "MPa"),
              fp("a", "Teshik radiusi", 1, 20, 5, 0.5, "mm")],
      curves=[fc("σ(r) = σ₀(1 + a²/(2r²) + 3a⁴/(2r⁴))", "s0*(1 + a^2/(2*x^2) + 3*a^4/(2*x^4))", "tension"),
              fc("Nominal σ₀", "s0", "rule", dashed=True)],
      x=("markazdan masofa r, mm", "σ, MPa"), x_min="a", x_max="5*a",
      readouts=[fr("σ_max (r=a)", "3*s0", "MPa", "tension"),
                fr("σ (r=2a)", "s0*(1 + 1/8 + 3/32)", "MPa", "compress"),
                fr("Konsentratsiya so'nishi (r=3a)", "100*(a^2/(2*9*a^2) + 3*a^4/(2*81*a^4))", "%", "mark"),
                fr("σ teshikdan 1 mm narida", "s0*(1 + a^2/(2*(a + 1)^2) + 3*a^4/(2*(a + 1)^4))", "MPa", "rule")],
      note="Konsentratsiya tez so'nadi: uch radius masofada qo'shimcha kuchlanish 7,4% ga tushadi. Teshik qanchalik KATTA bo'lsa, undan 1 mm narida kuchlanish shunchalik yuqori qoladi — shuning uchun katta teshiklar xavfliroq."),
  fig("Galtel radiusi va konsentratsiya koeffitsienti",
      "O'tkir burchak — charchash darzining boshlanish joyi.",
      params=[fp("d", "Kichik diametr", 10, 100, 40, 1, "mm"),
             fp("D", "Katta diametr", 20, 120, 50, 1, "mm")],
      curves=[fc("K_t ≈ 1 + 0,8√(d/(2r))", "1 + 0.8*sqrt(d/(2*x))", "tension"),
              fc("K_t = 1 (konsentratsiyasiz)", "1", "rule", dashed=True)],
      x=("galtel radiusi r, mm", "K_t"), x_min="0.5", x_max="10",
      readouts=[fr("D/d nisbati", "D/d", "", "rule"),
                fr("K_t (r=1 mm)", "1 + 0.8*sqrt(d/2)", "", "tension"),
                fr("K_t (r=5 mm)", "1 + 0.8*sqrt(d/10)", "", "compress"),
                fr("Yaxshilanish", "100*(1 - (1 + 0.8*sqrt(d/10))/(1 + 0.8*sqrt(d/2)))", "%", "mark")],
      note="Radiusni 1 dan 5 mm ga oshirish konsentratsiyani sezilarli kamaytiradi — arzon va samarali chora."),
 ],
 "mq-30": [
  fig("Kompleks hisob: uchta shart birgalikda",
      "Mustahkamlik, bikrlik va ustuvorlik turli diametr talab qiladi.",
      params=[fp("F", "Kuch", 5, 200, 40, 1, "kN"),
              fp("L", "Uzunlik", 0.5, 6, 2, 0.1, "m"),
              fp("sall", "[σ]", 60, 300, 160, 5, "MPa")],
      curves=[fc("Mustahkamlik: σ, MPa", "F*1000/(pi*(x*1e-3)^2/4)/1e6", "tension"),
              fc("[σ]", "sall", "rule", dashed=True),
              fc("Ustuvorlik zaxirasi ×10", "10*pi^2*210e9*pi*(x*1e-3)^4/64/L^2/(F*1000)", "compress")],
      x=("diametr d, mm", "σ, MPa  /  zaxira×10"), x_min="10", x_max="60",
      readouts=[fr("Mustahkamlik bo'yicha d", "sqrt(4*F*1000/(pi*sall*1e6))*1000", "mm", "tension"),
                fr("Ustuvorlik bo'yicha d (n=3)", "(3*F*1000*64*L^2/(pi^3*210e9))^0.25*1000", "mm", "compress"),
                fr("Qabul qilinadigan d", "max(sqrt(4*F*1000/(pi*sall*1e6))*1000, (3*F*1000*64*L^2/(pi^3*210e9))^0.25*1000)", "mm", "mark")],
      note="Loyihalashda har doim ENG KATTA talab qabul qilinadi — u barcha shartlarni bir yo'la qoplaydi."),
  fig("Massa va zaxira o'rtasidagi muvozanat",
      "Zaxirani oshirish massani chiziqli oshiradi.",
      params=[fp("F", "Kuch", 5, 200, 40, 1, "kN"),
              fp("L", "Uzunlik", 0.5, 6, 2, 0.1, "m"),
              fp("sy", "Oqish chegarasi", 150, 600, 250, 10, "MPa")],
      curves=[fc("Massa m = ρALn/σᵧ, kg", "7850*F*1000*x/(sy*1e6)*L", "tension"),
              fc("n = 1,5", "7850*F*1000*1.5/(sy*1e6)*L", "rule", dashed=True)],
      x=("zaxira koeffitsienti n", "massa, kg"), x_min="1", x_max="4",
      readouts=[fr("Massa (n=1,5)", "7850*F*1000*1.5/(sy*1e6)*L", "kg", "tension"),
                fr("Massa (n=3)", "7850*F*1000*3/(sy*1e6)*L", "kg", "compress"),
                fr("Yuqori mustahkam po'lat (σᵧ=500)", "7850*F*1000*1.5/(500e6)*L", "kg", "mark")],
      note="Mustahkamroq po'lat massani kamaytiradi, lekin bikrlik o'zgarmaydi — E barcha po'latlarda bir xil."),
 ],
}
