"""NM — nazariy mexanika mavzulari uchun interaktiv chizmalar."""

from __future__ import annotations

from content.curriculum.figures.base import fc, fig, fp, fr

FIGURES = {
 "nm-01": [
  fig("Vektorning koordinata o'qlariga proyeksiyasi",
      "Burchak o'zgarganda proyeksiyalar qanday o'zgaradi.",
      params=[fp("F", "Vektor moduli", 10, 200, 100, 5, "N"),
              fp("al", "Burchak", 0, 180, 30, 1, "°")],
      curves=[fc("Fx = F·cos θ", "F*cos(x*pi/180)", "tension"),
              fc("Fy = F·sin θ", "F*sin(x*pi/180)", "compress"),
              fc("|F| (o'zgarmas)", "F", "rule", dashed=True)],
      x=("burchak θ, °", "proyeksiya, N"), x_min="0", x_max="180",
      readouts=[fr("Fx", "F*cos(al*pi/180)", "N", "tension"),
                fr("Fy", "F*sin(al*pi/180)", "N", "compress"),
                fr("Nazorat: Fx²+Fy²", "sqrt((F*cos(al*pi/180))^2+(F*sin(al*pi/180))^2)", "N", "mark")],
      note="Proyeksiyalar burchakka bog'liq, modul esa yo'q — nazorat qatori doim |F| ga teng."),
  fig("Vektor ko'paytma: moment yelka orqali",
      "M = F·d; yelka d = r·sin θ, shuning uchun θ = 0 da moment yo'qoladi.",
      params=[fp("r", "Yelka uzunligi r", 0.2, 4, 1.5, 0.1, "m"),
              fp("F", "Kuch F", 10, 300, 120, 5, "N")],
      curves=[fc("M(θ) = F·r·sin θ", "F*r*sin(x*pi/180)", "tension"),
              fc("Maksimum F·r", "F*r", "rule", dashed=True)],
      x=("burchak θ, °", "moment M, N·m"), x_min="0", x_max="180",
      readouts=[fr("M maksimal (θ=90°)", "F*r", "N·m", "tension"),
                fr("M (θ=30°)", "F*r*0.5", "N·m"),
                fr("M (θ=0°)", "0", "N·m", "compress")],
      note="Skalyar ko'paytmadan farqli, vektor ko'paytma parallel vektorlarda nolga aylanadi."),
 ],
 "nm-02": [
  fig("Tekis tezlanuvchan harakat: uchta kattalik",
      "Joy, tezlik va tezlanish — biri ikkinchisining hosilasi.",
      params=[fp("v0", "Boshlang'ich tezlik", -20, 40, 10, 1, "m/s"),
              fp("a", "Tezlanish", -10, 10, 2, 0.5, "m/s²")],
      curves=[fc("x(t) = v₀t + at²/2", "v0*x + a*x^2/2", "tension"),
              fc("v(t) = v₀ + at", "v0 + a*x", "compress"),
              fc("a = const", "a", "mark", dashed=True)],
      x=("vaqt t, s", "x, v, a"), x_min="0", x_max="10",
      readouts=[fr("To'xtash vaqti", "(a < 0) ? (0-v0/a) : 0", "s", "mark"),
                fr("x(10)", "v0*10 + a*50", "m", "tension"),
                fr("v(10)", "v0 + a*10", "m/s", "compress")],
      note="Tezlanish manfiy bo'lsa, tezlik nolga aylanadigan vaqt hisoblanadi — undan keyin harakat teskari."),
  fig("Gorizontga burchak ostida otilgan jism",
      "Traektoriya parabola; uchish masofasi 45° da maksimal.",
      params=[fp("v0", "Boshlang'ich tezlik", 5, 60, 25, 1, "m/s"),
              fp("th", "Otilish burchagi", 5, 85, 45, 1, "°")],
      curves=[fc("y(x)", "x*tan(th*pi/180) - 9.81*x^2/(2*(v0*cos(th*pi/180))^2)", "tension"),
              fc("Yer sathi", "0", "rule", dashed=True)],
      x=("masofa x, m", "balandlik y, m"),
      x_min="0", x_max="v0^2*sin(2*th*pi/180)/9.81*1.05",
      readouts=[fr("Uchish masofasi", "v0^2*sin(2*th*pi/180)/9.81", "m", "tension"),
                fr("Maksimal balandlik", "(v0*sin(th*pi/180))^2/(2*9.81)", "m", "compress"),
                fr("Uchish vaqti", "2*v0*sin(th*pi/180)/9.81", "s", "mark")],
      note="Burchakni 45° ga qo'ying — masofa maksimal. 30° va 60° bir xil masofa beradi."),
 ],
 "nm-03": [
  fig("Tezlanishning urinma va normal tashkil etuvchilari",
      "Tezlik o'zgarsa urinma, yo'nalish o'zgarsa normal tashkil etuvchi paydo bo'ladi.",
      params=[fp("R", "Egrilik radiusi", 5, 200, 50, 5, "m"),
              fp("at", "Urinma tezlanish", -4, 4, 1, 0.1, "m/s²")],
      curves=[fc("aₙ = v²/R", "x^2/R", "tension"),
              fc("a_τ = const", "at", "compress", dashed=True),
              fc("|a| to'liq", "sqrt((x^2/R)^2 + at^2)", "mark")],
      x=("tezlik v, m/s", "tezlanish, m/s²"), x_min="0", x_max="40",
      readouts=[fr("aₙ (v=20)", "400/R", "m/s²", "tension"),
                fr("|a| (v=20)", "sqrt((400/R)^2 + at^2)", "m/s²", "mark"),
                fr("Normal ulushi", "100*(400/R)/sqrt((400/R)^2+at^2)", "%", "compress")],
      note="Radiusni kamaytiring: normal tashkil etuvchi tez o'sadi va to'liq tezlanishda hukmron bo'ladi."),
  fig("Egrilik radiusi traektoriya bo'ylab",
      "y = A·sin(kx) egri chizig'ining egrilik radiusi.",
      params=[fp("A", "Amplituda A", 0.2, 3, 1, 0.1, "m"),
              fp("k", "To'lqin soni k", 0.2, 2, 0.8, 0.05, "1/m")],
      curves=[fc("Traektoriya y(x)", "A*sin(k*x)", "rule"),
              fc("Egrilik ρ(x)", "(1 + (A*k*cos(k*x))^2)^1.5 / max(abs(A*k^2*sin(k*x)), 0.001)", "tension")],
      x=("x, m", "y, m  /  ρ, m"), x_min="0", x_max="12",
      readouts=[fr("ρ minimal (cho'qqida)", "1/(A*k^2)", "m", "tension"),
                fr("Egilish nuqtasida ρ", "1e6", "m", "compress")],
      note="Cho'qqida egrilik eng katta (ρ eng kichik), egilish nuqtasida esa ρ cheksizga intiladi."),
 ],
 "nm-04": [
  fig("Aylanma harakat: burchak kattaliklari",
      "Burchak tezlanish o'zgarmas bo'lganda burchak va burchak tezlik.",
      params=[fp("w0", "Boshlang'ich burchak tezlik", -5, 20, 4, 0.5, "rad/s"),
              fp("ep", "Burchak tezlanish", -3, 3, 1, 0.1, "rad/s²")],
      curves=[fc("φ(t)", "w0*x + ep*x^2/2", "tension"),
              fc("ω(t)", "w0 + ep*x", "compress"),
              fc("ε = const", "ep", "mark", dashed=True)],
      x=("vaqt t, s", "φ, ω, ε"), x_min="0", x_max="10",
      readouts=[fr("Aylanishlar soni (10 s)", "(w0*10 + ep*50)/(2*pi)", "ayl", "tension"),
                fr("ω(10)", "w0 + ep*10", "rad/s", "compress")],
      note="Ilgarilanma harakat bilan to'liq o'xshashlik: x↔φ, v↔ω, a↔ε."),
  fig("Nuqta tezligi aylanish o'qidan masofaga bog'liq",
      "v = ω·r — chetdagi nuqta markazdagidan tezroq.",
      params=[fp("w", "Burchak tezlik ω", 1, 50, 12, 1, "rad/s"),
              fp("R", "Jism radiusi", 0.1, 2, 0.6, 0.05, "m")],
      curves=[fc("v = ω·r", "w*x", "tension"),
              fc("aₙ = ω²·r", "w^2*x/10", "compress")],
      x=("o'qdan masofa r, m", "v, m/s  /  aₙ/10"), x_min="0", x_max="R",
      readouts=[fr("Chetdagi tezlik", "w*R", "m/s", "tension"),
                fr("Chetdagi aₙ", "w^2*R", "m/s²", "compress"),
                fr("Markazda", "0", "—", "rule")],
      note="Ikkalasi ham radius bo'ylab chiziqli o'sadi, lekin aₙ burchak tezlikning KVADRATIGA bog'liq."),
 ],
 "nm-05": [
  fig("Tekis harakatda tezliklar taqsimoti",
      "Oniy markazdan masofa qancha katta bo'lsa, tezlik shuncha katta.",
      params=[fp("w", "Burchak tezlik", 0.5, 20, 5, 0.5, "rad/s"),
              fp("d", "Nuqtadan OM gacha", 0.1, 3, 1, 0.05, "m")],
      curves=[fc("v = ω·d", "w*x", "tension"),
              fc("Joriy nuqta", "w*d", "mark", dashed=True)],
      x=("oniy markazdan masofa, m", "tezlik, m/s"), x_min="0", x_max="3",
      readouts=[fr("Joriy tezlik", "w*d", "m/s", "tension"),
                fr("Oniy markazda", "0", "m/s", "compress")],
      note="Oniy markaz — tezligi nolga teng yagona nuqta; qolgan hamma nuqta unga nisbatan aylanadi."),
  fig("G'ildirakning dumalashi: nuqtalar tezligi",
      "Yerga tegib turgan nuqta tinch, yuqori nuqta ikki barobar tez.",
      params=[fp("v", "Markaz tezligi", 1, 30, 10, 0.5, "m/s"),
              fp("R", "G'ildirak radiusi", 0.1, 1, 0.35, 0.01, "m")],
      curves=[fc("v(h) = v·h/R", "v*x/R", "tension"),
              fc("Markaz tezligi", "v", "rule", dashed=True)],
      x=("tegish nuqtasidan balandlik h, m", "tezlik, m/s"), x_min="0", x_max="2*R",
      readouts=[fr("Pastdagi nuqta", "0", "m/s", "compress"),
                fr("Markaz", "v", "m/s", "rule"),
                fr("Yuqorigi nuqta", "2*v", "m/s", "tension")],
      note="Dumalashda tegish nuqtasi oniy markaz bo'ladi — shuning uchun u tinch turadi."),
 ],
 "nm-06": [
  fig("Koriolis tezlanishi burchakka bog'liq",
      "aᶜ = 2ω·v_r·sin α — vektorlar parallel bo'lsa nolga aylanadi.",
      params=[fp("w", "Aylanish tezligi ω", 0.1, 10, 2, 0.1, "rad/s"),
              fp("vr", "Nisbiy tezlik", 0.5, 20, 5, 0.5, "m/s")],
      curves=[fc("aᶜ(α) = 2ω·v_r·sin α", "2*w*vr*sin(x*pi/180)", "tension"),
              fc("Maksimum 2ω·v_r", "2*w*vr", "rule", dashed=True)],
      x=("ω va v_r orasidagi burchak, °", "aᶜ, m/s²"), x_min="0", x_max="180",
      readouts=[fr("Maksimal aᶜ", "2*w*vr", "m/s²", "tension"),
                fr("α = 0° da", "0", "m/s²", "compress"),
                fr("Yer uchun (ω=7,3e-5)", "2*7.3e-5*vr", "m/s²", "mark")],
      note="Koriolis tezlanishi faqat AYLANUVCHI kadrda paydo bo'ladi va nisbiy tezlik nolga teng bo'lsa yo'qoladi."),
  fig("Yer yuzasida Koriolis effekti kenglikka bog'liq",
      "Ekvatorda gorizontal tashkil etuvchi nolga teng, qutbda maksimal.",
      params=[fp("v", "Harakat tezligi", 10, 900, 250, 10, "m/s")],
      curves=[fc("aᶜ = 2Ω·v·sin φ", "2*7.292e-5*v*sin(x*pi/180)", "tension"),
              fc("Ekvator darajasi", "0", "rule", dashed=True)],
      x=("kenglik φ, °", "aᶜ, m/s²"), x_min="0", x_max="90",
      readouts=[fr("Qutbda (90°)", "2*7.292e-5*v", "m/s²", "tension"),
                fr("41° (Toshkent)", "2*7.292e-5*v*sin(41*pi/180)", "m/s²", "mark"),
                fr("Ekvatorda", "0", "m/s²", "compress")],
      note="Shuning uchun siklonlar shimoliy yarim sharda soat strelkasiga teskari aylanadi."),
 ],
 "nm-07": [
  fig("Nyuton tenglamasi: kuch va tezlanish",
      "F = ma — massa o'zgarsa bir xil kuch turlicha tezlanish beradi.",
      params=[fp("m", "Massa", 0.5, 50, 5, 0.5, "kg")],
      curves=[fc("a = F/m", "x/m", "tension"),
              fc("m = 2m uchun", "x/(2*m)", "compress", dashed=True)],
      x=("kuch F, N", "tezlanish a, m/s²"), x_min="0", x_max="200",
      readouts=[fr("a (F=100 N)", "100/m", "m/s²", "tension"),
                fr("Massa 2 barobar", "100/(2*m)", "m/s²", "compress"),
                fr("Og'irlik mg", "m*9.81", "N", "mark")],
      note="Massa — inersiya o'lchovi: u qancha katta bo'lsa, bir xil kuch shuncha kam tezlanish beradi."),
  fig("Qiya tekislikda jism: ishqalanish bilan",
      "Burchak oshgani sari harakatlantiruvchi tashkil etuvchi o'sadi.",
      params=[fp("m", "Massa", 1, 50, 10, 1, "kg"),
              fp("mu", "Ishqalanish koeffitsienti", 0, 1, 0.3, 0.02)],
      curves=[fc("Siljituvchi mg·sin α", "m*9.81*sin(x*pi/180)", "tension"),
              fc("Ishqalanish μmg·cos α", "mu*m*9.81*cos(x*pi/180)", "compress"),
              fc("Natijaviy kuch", "m*9.81*sin(x*pi/180) - mu*m*9.81*cos(x*pi/180)", "mark")],
      x=("qiyalik burchagi α, °", "kuch, N"), x_min="0", x_max="60",
      readouts=[fr("Siljish burchagi", "atan(mu)*180/pi", "°", "mark"),
                fr("Tezlanish (α=30°)", "9.81*(sin(30*pi/180) - mu*cos(30*pi/180))", "m/s²", "tension")],
      note="Natijaviy kuch nolni kesgan burchak — siljish boshlanadigan burchak: tan α = μ."),
 ],
 "nm-08": [
  fig("Teskari masala: berilgan kuchdan harakatni topish",
      "F = F₀·sin(ωt) kuchi ostidagi nuqtaning tezligi va siljishi.",
      params=[fp("F0", "Kuch amplitudasi", 1, 100, 20, 1, "N"),
              fp("m", "Massa", 0.5, 20, 2, 0.5, "kg"),
              fp("w", "Chastota ω", 0.5, 10, 2, 0.1, "rad/s")],
      curves=[fc("a(t) = F/m", "F0*sin(w*x)/m", "mark"),
              fc("v(t)", "F0*(1 - cos(w*x))/(m*w)", "compress"),
              fc("s(t)", "F0*(x - sin(w*x)/w)/(m*w)", "tension")],
      x=("vaqt t, s", "a, v, s"), x_min="0", x_max="10",
      readouts=[fr("Maksimal tezlanish", "F0/m", "m/s²", "mark"),
                fr("O'rtacha tezlik", "F0/(m*w)", "m/s", "compress")],
      note="Tezlanish o'rtacha nolga teng bo'lsa ham, tezlik musbat qoladi — integrallash doimiysi shundan."),
  fig("To'g'ri masala: harakatdan kuchni tiklash",
      "s(t) berilgan bo'lsa, ikki marta differensiallab kuch topiladi.",
      params=[fp("A", "Amplituda", 0.1, 5, 1, 0.1, "m"),
              fp("w", "Chastota", 0.5, 8, 2, 0.1, "rad/s"),
              fp("m", "Massa", 0.5, 20, 3, 0.5, "kg")],
      curves=[fc("s(t) = A·sin ωt", "A*sin(w*x)", "tension"),
              fc("v(t) = Aω·cos ωt", "A*w*cos(w*x)", "compress"),
              fc("F(t) = −mAω²·sin ωt", "0-m*A*w^2*sin(w*x)", "mark")],
      x=("vaqt t, s", "s, v, F"), x_min="0", x_max="8",
      readouts=[fr("Maksimal kuch", "m*A*w^2", "N", "mark"),
                fr("Kuch / siljish", "0-m*w^2", "N/m", "tension")],
      note="Kuch siljishga proporsional va unga QARAMA-QARSHI — bu garmonik tebranishning belgisi."),
 ],
 "nm-09": [
  fig("Muhit qarshiligi: chiziqli va kvadratik qonun",
      "Past tezlikda qarshilik ~v, yuqori tezlikda ~v².",
      params=[fp("k1", "Chiziqli koeffitsient", 0, 5, 1, 0.1, "N·s/m"),
              fp("k2", "Kvadratik koeffitsient", 0, 0.5, 0.05, 0.01, "N·s²/m²")],
      curves=[fc("Chiziqli k₁v", "k1*x", "compress"),
              fc("Kvadratik k₂v²", "k2*x^2", "tension"),
              fc("Yig'indi", "k1*x + k2*x^2", "mark")],
      x=("tezlik v, m/s", "qarshilik, N"), x_min="0", x_max="40",
      readouts=[fr("Teng bo'lish tezligi", "(k2 > 0) ? k1/k2 : 0", "m/s", "mark"),
                fr("Qarshilik (v=20)", "k1*20 + k2*400", "N", "tension")],
      note="Ikki had teng bo'ladigan tezlikdan keyin kvadratik qonun hukmron bo'ladi."),
  fig("Chegaraviy tezlik: erkin tushish qarshilik bilan",
      "Tezlik chegaraviy qiymatga eksponensial yaqinlashadi.",
      params=[fp("m", "Massa", 0.1, 100, 70, 1, "kg"),
              fp("k", "Qarshilik koeffitsienti", 0.5, 30, 12, 0.5, "N·s/m")],
      curves=[fc("v(t)", "m*9.81/k*(1 - exp(0-k*x/m))", "tension"),
              fc("Chegaraviy tezlik", "m*9.81/k", "rule", dashed=True),
              fc("Qarshiliksiz gt", "9.81*x", "compress", dashed=True)],
      x=("vaqt t, s", "tezlik v, m/s"), x_min="0", x_max="30",
      readouts=[fr("Chegaraviy tezlik", "m*9.81/k", "m/s", "tension"),
                fr("Xarakterli vaqt m/k", "m/k", "s", "mark"),
                fr("63% ga yetish vaqti", "m/k", "s", "compress")],
      note="Bir xarakterli vaqtda tezlik chegaraviy qiymatning 63% iga yetadi — eksponensial qonunning belgisi."),
 ],
 "nm-10": [
  fig("Bog'lanish reaksiyasi: ikki tayanchli balka",
      "Yuk joyi o'zgarsa reaksiyalar qanday qayta taqsimlanadi.",
      params=[fp("P", "Yuk P", 1, 100, 40, 1, "kN"),
              fp("L", "Oraliq L", 1, 12, 6, 0.5, "m")],
      curves=[fc("R_A(a)", "P*(L - x)/L", "tension"),
              fc("R_B(a)", "P*x/L", "compress"),
              fc("Yig'indi = P", "P", "mark", dashed=True)],
      x=("yuk joyi a, m", "reaksiya, kN"), x_min="0", x_max="L",
      readouts=[fr("R_A (a=L/2)", "P/2", "kN", "tension"),
                fr("R_B (a=L/2)", "P/2", "kN", "compress"),
                fr("Nazorat R_A+R_B", "P", "kN", "mark")],
      note="Yuk qaysi tayanchga yaqin bo'lsa, o'sha tayanch ko'proq oladi. Yig'indi esa doim P ga teng."),
  fig("Ip tarangligi: osilgan yuk burchakka bog'liq",
      "Iplar orasidagi burchak oshgani sari taranglik keskin o'sadi.",
      params=[fp("W", "Yuk og'irligi", 10, 500, 100, 5, "N")],
      curves=[fc("T = W/(2·cos θ)", "W/(2*cos(x*pi/180))", "tension"),
              fc("Yuk darajasi W", "W", "rule", dashed=True)],
      x=("ipning vertikaldan burchagi θ, °", "taranglik T, N"), x_min="0", x_max="85",
      readouts=[fr("T (θ=0°)", "W/2", "N", "compress"),
                fr("T (θ=60°)", "W", "N", "mark"),
                fr("T (θ=80°)", "W/(2*cos(80*pi/180))", "N", "tension")],
      note="Ipni gorizontal tortishga urinmang: θ → 90° da taranglik cheksizga intiladi."),
 ],
 "nm-11": [
  fig("Kuchlar sistemasini bir nuqtaga keltirish",
      "Keltirish markazi surilsa bosh vektor o'zgarmaydi, bosh moment o'zgaradi.",
      params=[fp("F", "Kuch F", 10, 200, 60, 5, "N"),
              fp("M0", "Boshlang'ich moment", -200, 200, 50, 5, "N·m")],
      curves=[fc("Bosh moment M(d)", "M0 + F*x", "tension"),
              fc("Bosh vektor F (o'zgarmas)", "F", "compress", dashed=True),
              fc("Nol darajasi", "0", "rule", dashed=True)],
      x=("markazning siljishi d, m", "M, N·m  /  F, N"), x_min="-4", x_max="4",
      readouts=[fr("M nolga aylanadigan d", "0-M0/F", "m", "mark"),
                fr("Bosh vektor", "F", "N", "compress")],
      note="Bosh moment nolga aylanadigan nuqta bor — o'sha yerda sistema bitta kuchga keltiriladi."),
  fig("Muvozanat sharti: uchta kuch",
      "Uchinchi kuch ikkitasining geometrik yig'indisiga teng va qarama-qarshi.",
      params=[fp("F1", "Kuch F₁", 10, 200, 80, 5, "N"),
              fp("F2", "Kuch F₂", 10, 200, 60, 5, "N")],
      curves=[fc("F₃ = √(F₁²+F₂²−2F₁F₂cos θ)", "sqrt(F1^2 + F2^2 - 2*F1*F2*cos(x*pi/180))", "tension"),
              fc("F₁+F₂ (chegara)", "F1+F2", "rule", dashed=True),
              fc("|F₁−F₂| (chegara)", "abs(F1-F2)", "rule", dashed=True)],
      x=("F₁ va F₂ orasidagi burchak, °", "muvozanatlovchi F₃, N"), x_min="0", x_max="180",
      readouts=[fr("θ=0° (bir yo'nalish)", "abs(F1-F2)", "N", "compress"),
                fr("θ=90°", "sqrt(F1^2+F2^2)", "N", "mark"),
                fr("θ=180°", "F1+F2", "N", "tension")],
      note="Uchinchi kuch faqat |F₁−F₂| va F₁+F₂ oralig'ida bo'lishi mumkin — uchburchak tengsizligi."),
 ],
 "nm-12": [
  fig("Ishqalanish konusi va muvozanat chegarasi",
      "Qiyalik burchagi ishqalanish burchagidan oshsa, jism siljiydi.",
      params=[fp("mu", "Ishqalanish koeffitsienti μ", 0.05, 1.2, 0.35, 0.01)],
      curves=[fc("Kerakli ushlab turuvchi kuch", "9.81*(sin(x*pi/180) - mu*cos(x*pi/180))", "tension"),
              fc("Nol darajasi", "0", "rule", dashed=True)],
      x=("qiyalik burchagi α, °", "kuch / massa, m/s²"), x_min="0", x_max="70",
      readouts=[fr("Ishqalanish burchagi φ", "atan(mu)*180/pi", "°", "mark"),
                fr("α < φ bo'lsa", "1", "", "compress", text="o'z-o'zidan turadi|siljiydi"),
                fr("Siljish tezlanishi (α=40°)", "max(9.81*(sin(40*pi/180) - mu*cos(40*pi/180)), 0)", "m/s²", "tension")],
      note="μ = tan φ. Bu burchakdan past qiyalikda jism qancha og'ir bo'lmasin o'z-o'zidan turadi."),
  fig("Sirg'anish va dumalash ishqalanishi",
      "Dumalash ishqalanishi sirg'anishdan tartibga kichik.",
      params=[fp("N", "Normal bosim", 50, 2000, 500, 10, "N"),
              fp("R", "G'ildirak radiusi", 0.05, 1, 0.3, 0.01, "m")],
      curves=[fc("Sirg'anish μN", "x*N", "tension"),
              fc("Dumalash (f=0,5 mm)", "0.0005*N/R + 0*x", "compress")],
      x=("ishqalanish koeffitsienti μ", "kuch, N"), x_min="0", x_max="0.6",
      readouts=[fr("Dumalash qarshiligi", "0.0005*N/R", "N", "compress"),
                fr("Sirg'anish (μ=0,3)", "0.3*N", "N", "tension"),
                fr("Nisbat", "0.3*N/(0.0005*N/R)", "marta", "mark")],
      note="Shuning uchun g'ildirak ixtiro qilingan: dumalash qarshiligi sirg'anishdan yuzlab marta kichik."),
 ],
 "nm-13": [
  fig("Impuls saqlanishi: markaziy to'qnashuv",
      "Tiklanish koeffitsienti e to'qnashuvdan keyingi tezliklarni belgilaydi.",
      params=[fp("m1", "Birinchi massa", 0.5, 20, 2, 0.5, "kg"),
              fp("m2", "Ikkinchi massa", 0.5, 20, 3, 0.5, "kg"),
              fp("u1", "Boshlang'ich tezlik", 0.5, 20, 6, 0.5, "m/s")],
      curves=[fc("v₁ (to'qnashuvdan keyin)", "((m1 - x*m2)*u1)/(m1 + m2)", "tension"),
              fc("v₂ (to'qnashuvdan keyin)", "(m1*u1*(1 + x))/(m1 + m2)", "compress"),
              fc("Nol", "0", "rule", dashed=True)],
      x=("tiklanish koeffitsienti e", "tezlik, m/s"), x_min="0", x_max="1",
      readouts=[fr("Impuls (oldin)", "m1*u1", "kg·m/s", "mark"),
                fr("Elastik (e=1) v₁", "((m1 - m2)*u1)/(m1 + m2)", "m/s", "tension"),
                fr("Noelastik (e=0) umumiy v", "m1*u1/(m1 + m2)", "m/s", "compress"),
                fr("Energiya yo'qolishi (e=0)", "m1*m2*u1^2/(2*(m1+m2))", "J", "mark")],
      note="Impuls har doim saqlanadi; energiya esa faqat e = 1 da. e = 0 da jismlar birga harakatlanadi."),
  fig("Impuls momenti saqlanishi: figurist effekti",
      "Inersiya momenti kamaysa, burchak tezlik shuncha ortadi.",
      params=[fp("J0", "Boshlang'ich inersiya momenti", 0.5, 10, 4, 0.1, "kg·m²"),
              fp("w0", "Boshlang'ich burchak tezlik", 0.5, 20, 3, 0.1, "rad/s")],
      curves=[fc("ω = J₀ω₀/J", "J0*w0/x", "tension"),
              fc("Kinetik energiya T = L²/(2J)", "(J0*w0)^2/(2*x)", "compress"),
              fc("Boshlang'ich ω₀", "w0", "rule", dashed=True)],
      x=("joriy inersiya momenti J, kg·m²", "ω, rad/s  /  T, J"), x_min="0.3", x_max="J0*1.5",
      readouts=[fr("Impuls momenti L (o'zgarmas)", "J0*w0", "kg·m²/s", "mark"),
                fr("J yarmiga tushsa ω", "2*w0", "rad/s", "tension"),
                fr("Shunda energiya", "2*(J0*w0^2/2)", "J", "compress")],
      note="L saqlanadi, lekin energiya O'SADI — farqni figurist qo'llarini tortib ish bajarib qo'shadi."),
 ],
 "nm-14": [
  fig("Kinetik energiya haqidagi teorema",
      "Kuch bajargan ish kinetik energiya o'zgarishiga teng.",
      params=[fp("m", "Massa", 0.5, 50, 5, 0.5, "kg"),
              fp("F", "Doimiy kuch", 1, 200, 30, 1, "N")],
      curves=[fc("Ish A = F·s", "F*x", "tension"),
              fc("Tezlik v = √(2Fs/m)", "sqrt(2*F*x/m)*10", "compress")],
      x=("yo'l s, m", "A, J  /  v×10, m/s"), x_min="0", x_max="20",
      readouts=[fr("Ish (s=10 m)", "F*10", "J", "tension"),
                fr("Tezlik (s=10 m)", "sqrt(2*F*10/m)", "m/s", "compress"),
                fr("Kinetik energiya", "F*10", "J", "mark")],
      note="Tezlik yo'lning kvadrat ildizi kabi o'sadi — energiya esa chiziqli."),
  fig("Quvvat: bir xil ishni turli vaqtda bajarish",
      "N = A/t — vaqt qisqarsa quvvat keskin oshadi.",
      params=[fp("A", "Bajariladigan ish", 100, 100000, 10000, 100, "J")],
      curves=[fc("Quvvat N = A/t", "A/x", "tension"),
              fc("1 kVt darajasi", "1000", "rule", dashed=True)],
      x=("vaqt t, s", "quvvat N, Vt"), x_min="0.5", x_max="60",
      readouts=[fr("N (t=10 s)", "A/10", "Vt", "tension"),
                fr("N (t=60 s)", "A/60", "Vt", "compress"),
                fr("Ot kuchida (t=10 s)", "A/10/735.5", "o.k.", "mark")],
      note="Ish bir xil bo'lsa ham, uni tez bajarish uchun ancha katta quvvat kerak."),
 ],
 "nm-15": [
  fig("Potensial chuqurcha va harakat sohasi",
      "To'liq energiya chizig'i potensial egrini kesgan joy — burilish nuqtasi.",
      params=[fp("E", "To'liq energiya", 0.1, 6, 2, 0.05, "J"),
              fp("k", "Chuqurcha chuqurligi", 0.5, 4, 1.6, 0.1)],
      curves=[fc("U(x) = k(x⁴/4 − x²/2) + 2", "k*(x^4/4 - x^2/2) + 2", "ink"),
              fc("To'liq energiya E", "E", "tension", dashed=True)],
      x=("koordinata x", "energiya, J"), x_min="-2.2", x_max="2.2",
      readouts=[fr("Minimumlar joyi ±", "1", "", "compress"),
                fr("To'siq balandligi", "2", "J", "mark"),
                fr("E > to'siq bo'lsa", "E - 2", "J", "tension", text="ikki chuqurcha ulangan|chuqurchada qamalgan")],
      note="E ni to'siq balandligidan oshiring — jism bitta chuqurchadan ikkinchisiga o'ta oladi."),
  fig("Prujina: potensial va kinetik energiya almashinuvi",
      "Yig'indi o'zgarmas, ulushlar esa doimo almashinadi.",
      params=[fp("A", "Amplituda", 0.05, 1, 0.3, 0.01, "m"),
              fp("k", "Prujina bikrligi", 50, 5000, 800, 50, "N/m")],
      curves=[fc("U = kx²/2", "k*x^2/2", "compress"),
              fc("T = k(A²−x²)/2", "k*(A^2 - x^2)/2", "tension"),
              fc("To'liq E = kA²/2", "k*A^2/2", "mark", dashed=True)],
      x=("siljish x, m", "energiya, J"), x_min="0-A", x_max="A",
      readouts=[fr("To'liq energiya", "k*A^2/2", "J", "mark"),
                fr("Markazda T", "k*A^2/2", "J", "tension"),
                fr("Chetda U", "k*A^2/2", "J", "compress")],
      note="Ikki egri chiziq har doim bir xil yig'indi beradi — energiya saqlanishining ko'rinishi."),
 ],
 "nm-16": [
  fig("Massalar markazi ikki jism uchun",
      "Markaz og'irroq jismga yaqinroq yotadi.",
      params=[fp("m1", "Birinchi massa", 0.5, 50, 5, 0.5, "kg"),
              fp("L", "Jismlar orasi", 0.5, 10, 4, 0.1, "m")],
      curves=[fc("x_c = m₂L/(m₁+m₂)", "x*L/(m1 + x)", "tension"),
              fc("O'rta nuqta L/2", "L/2", "rule", dashed=True)],
      x=("ikkinchi massa m₂, kg", "markaz joyi x_c, m"), x_min="0.5", x_max="50",
      readouts=[fr("m₂ = m₁ bo'lsa", "L/2", "m", "rule"),
                fr("m₂ = 2m₁ bo'lsa", "2*L/3", "m", "tension"),
                fr("m₂ → ∞ bo'lsa", "L", "m", "compress")],
      note="Yer–Oy tizimida markaz Yer ichida yotadi, chunki Yer 81 barobar og'ir."),
  fig("Massalar markazi harakati teoremasi",
      "Ichki kuchlar markaz harakatiga umuman ta'sir qilmaydi.",
      params=[fp("M", "Umumiy massa", 1, 100, 20, 1, "kg"),
              fp("Fe", "Tashqi kuch", 0, 200, 40, 5, "N")],
      curves=[fc("a_c = F_tashqi/M", "Fe/M + 0*x", "tension"),
              fc("Ichki kuchlar hissasi", "0", "compress", dashed=True),
              fc("v_c(t) = a_c·t", "Fe/M*x", "mark")],
      x=("vaqt t, s", "a_c, m/s²  /  v_c, m/s"), x_min="0", x_max="10",
      readouts=[fr("Markaz tezlanishi", "Fe/M", "m/s²", "tension"),
                fr("Tashqi kuch nol bo'lsa", "0", "m/s²", "compress"),
                fr("v_c (10 s)", "Fe/M*10", "m/s", "mark")],
      note="Portlash paytida parchalar tarqaladi, lekin ularning massalar markazi eski traektoriyani davom ettiradi."),
 ],
 "nm-17": [
  fig("Turli jismlarning inersiya momenti",
      "Massa o'qdan qancha uzoq taqsimlangan bo'lsa, J shuncha katta.",
      params=[fp("m", "Massa", 0.5, 50, 10, 0.5, "kg")],
      curves=[fc("Halqa mR²", "m*x^2", "tension"),
              fc("Disk mR²/2", "m*x^2/2", "compress"),
              fc("Shar 2mR²/5", "2*m*x^2/5", "mark")],
      x=("radius R, m", "inersiya momenti J, kg·m²"), x_min="0", x_max="1",
      readouts=[fr("Halqa (R=0,5)", "m*0.25", "kg·m²", "tension"),
                fr("Disk (R=0,5)", "m*0.125", "kg·m²", "compress"),
                fr("Shar (R=0,5)", "2*m*0.25/5", "kg·m²", "mark")],
      note="Bir xil massa va radiusda halqa eng katta J beradi — butun massasi chetda."),
  fig("Shteyner teoremasi: o'qni surish",
      "J = J_c + md² — markazdan uzoqlashgani sari kvadratik o'sadi.",
      params=[fp("m", "Massa", 0.5, 50, 8, 0.5, "kg"),
              fp("Jc", "Markaziy inersiya momenti", 0.1, 10, 1.2, 0.1, "kg·m²")],
      curves=[fc("J(d) = J_c + md²", "Jc + m*x^2", "tension"),
              fc("J_c (minimal)", "Jc", "rule", dashed=True)],
      x=("o'qning markazdan masofasi d, m", "J, kg·m²"), x_min="0", x_max="2",
      readouts=[fr("J (d=0)", "Jc", "kg·m²", "rule"),
                fr("J (d=1 m)", "Jc + m", "kg·m²", "tension"),
                fr("Ikki barobar bo'ladigan d", "sqrt(Jc/m)", "m", "mark")],
      note="Markaziy o'q — inersiya momenti MINIMAL bo'ladigan yagona o'q."),
 ],
 "nm-18": [
  fig("Qiya tekislikdan dumalash: shakl tezlanishni belgilaydi",
      "J/mR² nisbati qancha kichik bo'lsa, jism shuncha tez dumalaydi.",
      params=[fp("al", "Qiyalik burchagi", 5, 45, 20, 1, "°")],
      curves=[fc("a = g·sin α/(1+k)", "9.81*sin(al*pi/180)/(1 + x)", "tension"),
              fc("Sirg'anish (k=0)", "9.81*sin(al*pi/180)", "rule", dashed=True)],
      x=("k = J/(mR²)", "tezlanish a, m/s²"), x_min="0", x_max="1.2",
      readouts=[fr("Shar (k=0,4)", "9.81*sin(al*pi/180)/1.4", "m/s²", "tension"),
                fr("Disk (k=0,5)", "9.81*sin(al*pi/180)/1.5", "m/s²", "compress"),
                fr("Halqa (k=1)", "9.81*sin(al*pi/180)/2", "m/s²", "mark")],
      note="Shar halqadan tezroq dumalaydi — massasi o'qqa yaqin, shuning uchun aylanishga kam energiya ketadi."),
  fig("Dumalash uchun kerakli ishqalanish",
      "Qiyalik oshgani sari sirg'anmaslik uchun ko'proq ishqalanish kerak.",
      params=[fp("k", "k = J/(mR²)", 0.2, 1.2, 0.4, 0.05)],
      curves=[fc("μ_kerak = k·tan α/(1+k)", "k*tan(x*pi/180)/(1 + k)", "tension"),
              fc("Odatiy μ = 0,5", "0.5", "rule", dashed=True)],
      x=("qiyalik burchagi α, °", "kerakli μ"), x_min="0", x_max="60",
      readouts=[fr("μ_kerak (α=30°)", "k*tan(30*pi/180)/(1+k)", "", "tension"),
                fr("μ=0,5 da chegara burchak", "atan(0.5*(1+k)/k)*180/pi", "°", "mark")],
      note="Chegara burchakdan keyin jism dumalash bilan birga sirg'ana boshlaydi."),
 ],
 "nm-19": [
  fig("Erkinlik darajalari soni bog'lanishlar bilan kamayadi",
      "n = 3N − k (tekislikda): har bir bog'lanish bittadan olib tashlaydi.",
      params=[fp("N", "Jismlar soni", 1, 12, 4, 1, "dona")],
      curves=[fc("n = 3N − k", "3*N - x", "tension"),
              fc("Mexanizm chegarasi n=1", "1", "rule", dashed=True),
              fc("Ferma n=0", "0", "compress", dashed=True)],
      x=("bog'lanishlar soni k", "erkinlik darajasi n"), x_min="0", x_max="3*N+2",
      readouts=[fr("Bog'lanishsiz", "3*N", "", "mark"),
                fr("n=1 uchun kerak k", "3*N - 1", "", "tension"),
                fr("n=0 uchun kerak k", "3*N", "", "compress")],
      note="n = 1 — mexanizm (bitta harakat), n = 0 — konstruksiya, n < 0 — statik aniqmas."),
  fig("Umumlashgan koordinata: ikki karrali mayatnik",
      "Ikki erkinlik darajasi — ikkita burchak yetarli.",
      params=[fp("l1", "Birinchi sterjen", 0.2, 2, 1, 0.05, "m"),
              fp("l2", "Ikkinchi sterjen", 0.2, 2, 0.8, 0.05, "m"),
              fp("th1", "Birinchi burchak", -180, 180, 40, 1, "°")],
      curves=[fc("Uchning x koordinatasi", "l1*sin(th1*pi/180) + l2*sin(x*pi/180)", "tension"),
              fc("Uchning y koordinatasi", "0-l1*cos(th1*pi/180) - l2*cos(x*pi/180)", "compress")],
      x=("ikkinchi burchak θ₂, °", "koordinata, m"), x_min="-180", x_max="180",
      readouts=[fr("Maksimal uzoqlik", "l1 + l2", "m", "mark"),
                fr("Minimal uzoqlik", "abs(l1 - l2)", "m", "rule"),
                fr("Erkinlik darajasi", "2", "", "tension")],
      note="Dekart koordinatalarida 4 ta son kerak bo'lardi; umumlashgan koordinatada — atigi 2 ta burchak."),
 ],
 "nm-20": [
  fig("Mumkin bo'lgan ko'chishlar: richag muvozanati",
      "Virtual ish nolga teng bo'lgan joyda muvozanat.",
      params=[fp("P", "Chap yuk", 1, 100, 30, 1, "N"),
              fp("a", "Chap yelka", 0.1, 3, 1, 0.05, "m")],
      curves=[fc("Virtual ish δA = Pa − Qb", "P*a - x*1.5", "tension"),
              fc("Muvozanat chizig'i", "0", "rule", dashed=True)],
      x=("o'ng yuk Q, N (yelka 1,5 m)", "virtual ish, N·m"), x_min="0", x_max="100",
      readouts=[fr("Muvozanat Q", "P*a/1.5", "N", "tension"),
                fr("Chap moment", "P*a", "N·m", "compress"),
                fr("Foyda", "a/1.5", "marta", "mark")],
      note="Reaksiya kuchlari virtual ishda umuman qatnashmaydi — usulning asosiy qulayligi shu."),
  fig("Umumlashgan kuch: qiya tekislikdagi yuk",
      "Q = −∂Π/∂q — potensial energiyaning umumlashgan koordinata bo'yicha hosilasi.",
      params=[fp("m", "Massa", 1, 100, 20, 1, "kg"),
              fp("al", "Qiyalik", 5, 60, 25, 1, "°")],
      curves=[fc("Π(s) = mgs·sin α", "m*9.81*x*sin(al*pi/180)", "compress"),
              fc("Q = −mg·sin α", "0-m*9.81*sin(al*pi/180) + 0*x", "tension")],
      x=("qiyalik bo'ylab siljish s, m", "Π, J  /  Q, N"), x_min="0", x_max="5",
      readouts=[fr("Umumlashgan kuch", "0-m*9.81*sin(al*pi/180)", "N", "tension"),
                fr("Π (s=5 m)", "m*9.81*5*sin(al*pi/180)", "J", "compress")],
      note="Potensial energiya chiziqli o'sganda umumlashgan kuch o'zgarmas bo'ladi."),
 ],
 "nm-21": [
  fig("D'Alembert: inersiya kuchi bilan statikaga keltirish",
      "Liftdagi jismning ko'rinma og'irligi tezlanishga bog'liq.",
      params=[fp("m", "Massa", 1, 150, 70, 1, "kg")],
      curves=[fc("N = m(g + a)", "m*(9.81 + x)", "tension"),
              fc("Tinch holatdagi mg", "m*9.81", "rule", dashed=True),
              fc("Vaznsizlik chegarasi", "0", "compress", dashed=True)],
      x=("lift tezlanishi a, m/s²", "tayanch reaksiyasi N, N"), x_min="-12", x_max="12",
      readouts=[fr("Tinch (a=0)", "m*9.81", "N", "rule"),
                fr("a = +3 m/s²", "m*12.81", "N", "tension"),
                fr("Erkin tushish (a=−g)", "0", "N", "compress")],
      note="a = −g da reaksiya nolga aylanadi — vaznsizlik. Bu kuch yo'qolgani emas, tayanch yo'qolgani."),
  fig("Aylanuvchi tizimdagi markazdan qochma inersiya kuchi",
      "Konussimon mayatnik burchagi aylanish tezligiga bog'liq.",
      params=[fp("L", "Ip uzunligi", 0.2, 3, 1, 0.05, "m"),
              fp("m", "Massa", 0.1, 10, 1, 0.1, "kg")],
      curves=[fc("cos θ = g/(ω²L)", "9.81/(x^2*L)", "tension"),
              fc("cos θ = 1 chegara", "1", "rule", dashed=True)],
      x=("burchak tezlik ω, rad/s", "cos θ"), x_min="1", x_max="12",
      readouts=[fr("Minimal ω (θ→0)", "sqrt(9.81/L)", "rad/s", "mark"),
                fr("Taranglik (ω=6)", "m*36*L", "N", "tension"),
                fr("Burchak (ω=6)", "acos(min(9.81/(36*L),1))*180/pi", "°", "compress")],
      note="Minimal ω dan past tezlikda konus hosil bo'lmaydi — mayatnik osilib qoladi."),
 ],
 "nm-22": [
  fig("Lagranj tenglamasi: matematik mayatnik davri",
      "Kichik tebranishda davr amplitudaga bog'liq emas, kattasida esa bog'liq.",
      params=[fp("L", "Mayatnik uzunligi", 0.1, 5, 1, 0.05, "m")],
      curves=[fc("T(θ₀) aniq (1-tuzatma)", "2*pi*sqrt(L/9.81)*(1 + (x*pi/180)^2/16)", "tension"),
              fc("Kichik tebranish T₀", "2*pi*sqrt(L/9.81)", "rule", dashed=True)],
      x=("amplituda θ₀, °", "davr T, s"), x_min="0", x_max="120",
      readouts=[fr("T₀ (kichik)", "2*pi*sqrt(L/9.81)", "s", "rule"),
                fr("T (θ₀=30°)", "2*pi*sqrt(L/9.81)*(1 + (30*pi/180)^2/16)", "s", "tension"),
                fr("Farq (30°)", "100*((30*pi/180)^2/16)", "%", "mark")],
      note="30° da farq atigi 1,7% — shuning uchun kichik tebranish taqribi juda uzoqqa ishlaydi."),
  fig("Lagranj funksiyasi: kinetik va potensial hadlar",
      "L = T − Π; tizim L ni ekstremal qiladigan yo'ldan boradi.",
      params=[fp("m", "Massa", 0.1, 10, 1, 0.1, "kg"),
              fp("k", "Bikrlik", 10, 2000, 400, 10, "N/m"),
              fp("A", "Amplituda", 0.02, 0.5, 0.1, 0.01, "m")],
      curves=[fc("T (kinetik)", "k*(A^2 - (A*sin(x))^2)/2", "tension"),
              fc("Π (potensial)", "k*(A*sin(x))^2/2", "compress"),
              fc("L = T − Π", "k*(A^2 - 2*(A*sin(x))^2)/2", "mark"),
              fc("E = T + Π", "k*A^2/2", "rule", dashed=True)],
      x=("faza ωt, rad", "energiya, J"), x_min="0", x_max="6.28",
      readouts=[fr("To'liq energiya", "k*A^2/2", "J", "rule"),
                fr("L o'rtacha qiymati", "0", "J", "mark"),
                fr("Chastota", "sqrt(k/m)", "rad/s", "tension")],
      note="E o'zgarmas, L esa tebranadi va bir davr bo'yicha o'rtachasi nolga teng."),
 ],
 "nm-23": [
  fig("Siklik koordinata: markaziy maydonda impuls momenti",
      "φ koordinatasi Lagranjianda yo'q — demak unga mos impuls saqlanadi.",
      params=[fp("L0", "Impuls momenti", 0.5, 20, 5, 0.5, "kg·m²/s"),
              fp("m", "Massa", 0.1, 10, 1, 0.1, "kg")],
      curves=[fc("Markazdan qochma U_eff = L²/(2mr²)", "L0^2/(2*m*x^2)", "tension"),
              fc("Tortishish −k/r", "0-10/x", "compress"),
              fc("Effektiv U_eff", "L0^2/(2*m*x^2) - 10/x", "mark")],
      x=("radius r, m", "energiya, J"), x_min="0.3", x_max="10",
      readouts=[fr("Barqaror orbita radiusi", "L0^2/(m*10)", "m", "mark"),
                fr("Impuls momenti", "L0", "kg·m²/s", "tension")],
      note="Effektiv potensialning minimumi — doiraviy orbita. L saqlangani uchun r kichrayganda ω o'sadi."),
  fig("Simmetriya va saqlanish: Noter teoremasi",
      "Har bir uzluksiz simmetriyaga bitta saqlanuvchi kattalik mos keladi.",
      params=[fp("v", "Tizim tezligi", 0, 20, 5, 0.5, "m/s"),
              fp("m", "Massa", 0.5, 50, 10, 0.5, "kg")],
      curves=[fc("Impuls p = mv (siljish simmetriyasi)", "m*x", "tension"),
              fc("Kinetik energiya (vaqt simmetriyasi)", "m*x^2/2", "compress")],
      x=("tezlik v, m/s", "p, kg·m/s  /  T, J"), x_min="0", x_max="20",
      readouts=[fr("Siljish → impuls", "m*v", "kg·m/s", "tension"),
                fr("Vaqt → energiya", "m*v^2/2", "J", "compress"),
                fr("Burilish → impuls momenti", "m*v*1", "kg·m²/s", "mark")],
      note="Fazoning bir jinsliligi impulsni, vaqtning bir jinsliligi energiyani saqlaydi."),
 ],
 "nm-25": [
  fig("Erkin tebranish: chastota massa va bikrlikka bog'liq",
      "ω = √(k/m) — bikrlik oshsa tez, massa oshsa sekin tebranadi.",
      params=[fp("m", "Massa", 0.1, 20, 2, 0.1, "kg")],
      curves=[fc("ω = √(k/m)", "sqrt(x/m)", "tension"),
              fc("Davr T = 2π√(m/k)", "2*pi*sqrt(m/x)", "compress")],
      x=("bikrlik k, N/m", "ω, rad/s  /  T, s"), x_min="10", x_max="5000",
      readouts=[fr("ω (k=1000)", "sqrt(1000/m)", "rad/s", "tension"),
                fr("Davr (k=1000)", "2*pi*sqrt(m/1000)", "s", "compress"),
                fr("Chastota", "sqrt(1000/m)/(2*pi)", "Hz", "mark")],
      note="Massani to'rt barobar oshirish chastotani atigi ikki barobar kamaytiradi — kvadrat ildiz."),
  fig("Boshlang'ich shartlar amplituda va fazani belgilaydi",
      "x(t) = A·cos(ωt − φ); A va φ boshlang'ich holatdan topiladi.",
      params=[fp("x0", "Boshlang'ich siljish", -0.5, 0.5, 0.2, 0.01, "m"),
              fp("v0", "Boshlang'ich tezlik", -3, 3, 1, 0.1, "m/s"),
              fp("w", "Xususiy chastota", 1, 30, 8, 0.5, "rad/s")],
      curves=[fc("x(t)", "x0*cos(w*x) + v0/w*sin(w*x)", "tension"),
              fc("Amplituda ±A", "sqrt(x0^2 + (v0/w)^2)", "rule", dashed=True),
              fc("−A", "0-sqrt(x0^2 + (v0/w)^2)", "rule", dashed=True)],
      x=("vaqt t, s", "siljish x, m"), x_min="0", x_max="3",
      readouts=[fr("Amplituda A", "sqrt(x0^2 + (v0/w)^2)", "m", "tension"),
                fr("Faza φ", "atan2(v0/w, x0)*180/pi", "°", "mark"),
                fr("Davr", "2*pi/w", "s", "compress")],
      note="Boshlang'ich tezlik nolga teng bo'lsa, amplituda aynan boshlang'ich siljishga teng bo'ladi."),
 ],
 "nm-26": [
  fig("So'nuvchi tebranish: logarifmik dekrement",
      "Har bir davrda amplituda bir xil NISBATDA kamayadi.",
      params=[fp("z", "Dempfirlash ζ", 0.005, 0.4, 0.05, 0.005),
              fp("wn", "Xususiy chastota", 2, 40, 10, 0.5, "rad/s")],
      curves=[fc("x(t)", "exp(0-z*wn*x)*cos(wn*sqrt(1 - z^2)*x)", "tension"),
              fc("O'rama +", "exp(0-z*wn*x)", "rule", dashed=True),
              fc("O'rama −", "0-exp(0-z*wn*x)", "rule", dashed=True)],
      x=("vaqt t, s", "siljish (normallashgan)"), x_min="0", x_max="5",
      readouts=[fr("Logarifmik dekrement δ", "2*pi*z/sqrt(1 - z^2)", "", "tension"),
                fr("So'nish davri", "2*pi/(wn*sqrt(1 - z^2))", "s", "compress"),
                fr("Yarmiga tushish vaqti", "log(2)/(z*wn)", "s", "mark")],
      note="δ ni o'lchash orqali dempfirlashni tajribadan topish mumkin — eng keng tarqalgan usul."),
  fig("Uch rejim: kam, kritik va ortiqcha dempfirlash",
      "ζ = 1 da tebranishsiz eng tez qaytish.",
      params=[fp("wn", "Xususiy chastota", 2, 30, 8, 0.5, "rad/s")],
      curves=[fc("ζ = 0,1 (kam)", "exp(0-0.1*wn*x)*cos(wn*sqrt(0.99)*x)", "tension"),
              fc("ζ = 1,0 (kritik)", "(1 + wn*x)*exp(0-wn*x)", "compress"),
              fc("ζ = 2,5 (ortiqcha)", "exp(0-wn*x*(2.5 - sqrt(5.25)))", "mark")],
      x=("vaqt t, s", "siljish (normallashgan)"), x_min="0", x_max="2",
      readouts=[fr("Kritik dempfirlash c", "2*wn", "·m", "compress"),
                fr("Kam dempfirlashda oshib ketish", "exp(0-0.1*pi/sqrt(0.99))*100", "%", "tension")],
      note="Avtomobil amortizatori kritikka yaqin sozlanadi: tez tinchlanadi, lekin qattiq bo'lmaydi."),
 ],
 "nm-28": [
  fig("Ikki massali tizim: ikkita xususiy chastota",
      "Massa nisbati o'zgarsa chastotalar ajralib boradi.",
      params=[fp("k", "Bikrlik", 100, 5000, 1000, 50, "N/m"),
              fp("m1", "Birinchi massa", 0.5, 20, 2, 0.5, "kg")],
      curves=[fc("ω₁ (birinchi shakl)", "sqrt(k*(m1 + x + sqrt(m1^2 + x^2 - m1*x))/(m1*x))*0 + sqrt(k/m1*(1 + m1/x - sqrt((1 + m1/x)^2 - 1)))", "compress"),
              fc("ω₂ (ikkinchi shakl)", "sqrt(k/m1*(1 + m1/x + sqrt((1 + m1/x)^2 - 1)))", "tension")],
      x=("ikkinchi massa m₂, kg", "xususiy chastota, rad/s"), x_min="0.5", x_max="20",
      readouts=[fr("Erkinlik darajasi", "2", "", "mark"),
                fr("ω₁ (m₂=5)", "sqrt(k/m1*(1 + m1/5 - sqrt((1 + m1/5)^2 - 1)))", "rad/s", "compress"),
                fr("ω₂ (m₂=5)", "sqrt(k/m1*(1 + m1/5 + sqrt((1 + m1/5)^2 - 1)))", "rad/s", "tension")],
      note="N erkinlik darajali tizimda aynan N ta xususiy chastota bo'ladi."),
  fig("Massa va bikrlik matritsalarining roli",
      "Chastota ikkalasining nisbatidan chiqadi: ω² = k/m.",
      params=[fp("m", "Diagonal massa", 0.5, 20, 3, 0.5, "kg")],
      curves=[fc("ω = √(k/m)", "sqrt(x/m)", "tension"),
              fc("2m uchun", "sqrt(x/(2*m))", "compress", dashed=True),
              fc("m/2 uchun", "sqrt(2*x/m)", "mark", dashed=True)],
      x=("diagonal bikrlik k, N/m", "ω, rad/s"), x_min="50", x_max="5000",
      readouts=[fr("ω (k=1000)", "sqrt(1000/m)", "rad/s", "tension"),
                fr("Massa 2× bo'lsa", "sqrt(1000/(2*m))", "rad/s", "compress"),
                fr("Nisbat", "1/sqrt(2)", "", "mark")],
      note="Matritsa ko'rinishida ham mohiyat bir xil: bikrlik chastotani oshiradi, massa kamaytiradi."),
 ],
 "nm-29": [
  fig("Xususiy shakllar: tugunlar soni chastota bilan o'sadi",
      "n-shaklda n−1 ta tugun bo'ladi.",
      params=[fp("n", "Shakl raqami n", 1, 5, 2, 1),
              fp("L", "Uzunlik", 0.5, 5, 2, 0.1, "m")],
      curves=[fc("φₙ(x) = sin(nπx/L)", "sin(n*pi*x/L)", "tension"),
              fc("Nol chizig'i", "0", "rule", dashed=True)],
      x=("koordinata x, m", "shakl amplitudasi"), x_min="0", x_max="L",
      readouts=[fr("Tugunlar soni", "n - 1", "", "mark"),
                fr("Nisbiy chastota ωₙ/ω₁", "n^2", "", "tension"),
                fr("To'lqin uzunligi", "2*L/n", "m", "compress")],
      note="Balka uchun chastota n² kabi o'sadi — ikkinchi shakl birinchidan to'rt barobar tez."),
  fig("Modal superpozitsiya: shakllar yig'indisi",
      "Har qanday harakat xususiy shakllar yig'indisi sifatida yoziladi.",
      params=[fp("a1", "1-shakl ulushi", 0, 1, 1, 0.05),
              fp("a2", "2-shakl ulushi", 0, 1, 0.5, 0.05),
              fp("a3", "3-shakl ulushi", 0, 1, 0.25, 0.05)],
      curves=[fc("1-shakl", "a1*sin(pi*x)", "rule", dashed=True),
              fc("2-shakl", "a2*sin(2*pi*x)", "rule", dashed=True),
              fc("3-shakl", "a3*sin(3*pi*x)", "rule", dashed=True),
              fc("Yig'indi", "a1*sin(pi*x) + a2*sin(2*pi*x) + a3*sin(3*pi*x)", "tension")],
      x=("x / L", "siljish"), x_min="0", x_max="1",
      readouts=[fr("Modal energiya ulushi (1)", "100*a1^2/(a1^2 + 4*a2^2 + 9*a3^2)", "%", "tension"),
                fr("Modal energiya ulushi (2)", "100*4*a2^2/(a1^2 + 4*a2^2 + 9*a3^2)", "%", "compress")],
      note="Odatda birinchi bir necha shakl yetarli — shuning uchun modal qisqartirish juda samarali."),
 ],
 "nm-30": [
  fig("Nochiziqli mayatnik: davr amplitudaga bog'liq",
      "Chiziqli nazariyadan farq amplituda oshgani sari o'sadi.",
      params=[fp("L", "Uzunlik", 0.2, 3, 1, 0.05, "m")],
      curves=[fc("T/T₀ (aniq, 2-tartib)", "1 + (x*pi/180)^2/16 + 11*(x*pi/180)^4/3072", "tension"),
              fc("Chiziqli nazariya", "1", "rule", dashed=True)],
      x=("amplituda θ₀, °", "T / T₀"), x_min="0", x_max="170",
      readouts=[fr("T₀", "2*pi*sqrt(L/9.81)", "s", "rule"),
                fr("Farq (60°)", "100*((60*pi/180)^2/16 + 11*(60*pi/180)^4/3072)", "%", "tension"),
                fr("Farq (150°)", "100*((150*pi/180)^2/16 + 11*(150*pi/180)^4/3072)", "%", "mark")],
      note="Chiziqli mayatnik izoxron, nochiziqlisi esa yo'q — soatlarda kichik amplituda shuning uchun kerak."),
  fig("Vilkasimon bifurkatsiya: turg'unlikning yo'qolishi",
      "Parametr kritik qiymatdan oshganda bitta holat uchtaga bo'linadi.",
      params=[fp("mu", "Parametr μ", -2, 3, 1, 0.05)],
      curves=[fc("Turg'un tarmoq +√μ", "sqrt(max(x, 0))", "compress"),
              fc("Turg'un tarmoq −√μ", "0-sqrt(max(x, 0))", "compress"),
              fc("x = 0 (μ>0 da noturg'un)", "0", "tension", dashed=True)],
      x=("parametr μ", "muvozanat holati x*"), x_min="-2", x_max="3",
      readouts=[fr("Bifurkatsiya nuqtasi", "0", "", "mark"),
                fr("Joriy holat", "mu", "", "tension", text="ikki turg'un holat|bitta turg'un holat"),
                fr("Tarmoq qiymati", "sqrt(max(mu, 0))", "", "compress")],
      note="Ustuvorlikni yo'qotish, faza o'tishlari va ko'p konstruktiv hodisa aynan shu shaklga ega."),
 ],
 "nm-24": [
  fig("Gamilton funksiyasi: energiya saqlanishi",
      "H = T + Π; kanonik tenglamalar uni o'zgarmas saqlaydi.",
      params=[fp("E", "To'liq energiya H", 0.2, 4, 1.5, 0.05, "J"),
              fp("m", "Massa", 0.2, 5, 1, 0.1, "kg")],
      curves=[fc("p(q) = +√(2m(H − Π))", "sqrt(max(2*m*(E - (1 - cos(x))), 0))", "tension"),
              fc("p(q) = −√(2m(H − Π))", "0-sqrt(max(2*m*(E - (1 - cos(x))), 0))", "tension"),
              fc("Potensial Π = 1 − cos q", "1 - cos(x)", "compress", dashed=True),
              fc("H darajasi", "E", "rule", dashed=True)],
      x=("umumlashgan koordinata q, rad", "impuls p  /  energiya"), x_min="-3.3", x_max="3.3",
      readouts=[fr("Separatrisa energiyasi", "2", "J", "mark"),
                fr("Rejim", "2 - E", "", "tension", text="tebranish (yopiq)|aylanish (ochiq)"),
                fr("Maksimal impuls", "sqrt(2*m*E)", "kg·m/s", "compress")],
      note="Fazaviy traektoriya — H = const chizig'i. E = 2 dan oshsa yopiq orbita ochiladi."),
  fig("Kanonik tenglamalar: q va p ning o'zaro bog'liqligi",
      "q̇ = ∂H/∂p va ṗ = −∂H/∂q — ikkita birinchi tartibli tenglama.",
      params=[fp("m", "Massa", 0.2, 5, 1, 0.1, "kg"),
              fp("k", "Bikrlik", 10, 1000, 200, 10, "N/m"),
              fp("p0", "Impuls p", 0, 5, 2, 0.1, "kg·m/s")],
      curves=[fc("q̇ = p/m (o'zgarmas)", "p0/m + 0*x", "compress"),
              fc("ṗ = −kq", "0-k*x", "tension"),
              fc("Nol", "0", "rule", dashed=True)],
      x=("koordinata q, m", "q̇, m/s  /  ṗ, N"), x_min="-0.1", x_max="0.1",
      readouts=[fr("Chastota √(k/m)", "sqrt(k/m)", "rad/s", "mark"),
                fr("q̇ (p berilgan)", "p0/m", "m/s", "compress"),
                fr("ṗ (q=0,05)", "0-k*0.05", "N", "tension")],
      note="Ikkinchi tartibli bitta tenglama o'rniga birinchi tartibli ikkita — fazaviy fazoning asosi."),
 ],
 "nm-27": [
  fig("Rezonans egri chizig'i: dempfirlash cho'qqini cheklaydi",
      "ζ kamaysa cho'qqi 1/(2ζ) kabi o'sadi.",
      params=[fp("z", "Dempfirlash ζ", 0.02, 0.8, 0.08, 0.01)],
      curves=[fc("M(β)", "1/sqrt((1 - x^2)^2 + (2*z*x)^2)", "tension"),
              fc("ζ = 0,3 taqqoslash", "1/sqrt((1 - x^2)^2 + (0.6*x)^2)", "rule", dashed=True),
              fc("Statik daraja M=1", "1", "compress", dashed=True)],
      x=("β = ω/ωₙ", "kuchaytirish M"), x_min="0.05", x_max="2.6",
      readouts=[fr("Maksimal M", "(z < 0.707) ? 1/(2*z*sqrt(1 - z^2)) : 1", "", "tension"),
                fr("Cho'qqi joyi β", "(z < 0.707) ? sqrt(1 - 2*z^2) : 0", "", "mark"),
                fr("M (β=1)", "1/(2*z)", "", "compress")],
      note="ζ > 0,707 bo'lsa cho'qqi umuman yo'qoladi — tizim rezonansga kirmaydi."),
  fig("Faza siljishi: rezonansda aynan 90°",
      "Chastota o'tganda javob kuchdan orqada qoladi.",
      params=[fp("z", "Dempfirlash ζ", 0.02, 0.8, 0.1, 0.01)],
      curves=[fc("φ(β)", "atan2(2*z*x, 1 - x^2)*180/pi", "tension"),
              fc("90° chizig'i", "90", "rule", dashed=True),
              fc("ζ = 0,5 taqqoslash", "atan2(x, 1 - x^2)*180/pi", "compress", dashed=True)],
      x=("β = ω/ωₙ", "faza siljishi φ, °"), x_min="0.05", x_max="3",
      readouts=[fr("φ (β=1)", "90", "°", "mark"),
                fr("φ (β=0,5)", "atan2(z, 0.75)*180/pi", "°", "compress"),
                fr("φ (β=2)", "atan2(4*z, 0-3)*180/pi", "°", "tension")],
      note="β = 1 da faza dempfirlashdan QAT'I NAZAR aynan 90° — rezonansni aniqlashning ishonchli belgisi."),
 ],
}
