"""PQ — plastinalar va qobiqlar nazariyasi mavzulari uchun interaktiv chizmalar."""

from __future__ import annotations

from content.curriculum.figures.base import fc, fig, fp, fr

FIGURES = {
 "pq-01": [
  fig("Yupqa plastina chegarasi: h/a nisbati",
      "Kirxhoff nazariyasi faqat yetarlicha yupqa plastinada ishlaydi.",
      params=[fp("a", "Plastina tomoni", 100, 5000, 1000, 10, "mm")],
      curves=[fc("h/a nisbati", "x/a", "tension"),
              fc("Yupqa chegarasi 1/20", "0.05", "rule", dashed=True),
              fc("Membrana chegarasi 1/100", "0.01", "compress", dashed=True)],
      x=("qalinlik h, mm", "h/a"), x_min="1", x_max="200",
      readouts=[fr("h/a (h=10 mm)", "10/a", "", "tension"),
                fr("Yupqa chegara h", "a/20", "mm", "mark"),
                fr("Kirxhoff ishlaydimi (h=10)", "10/a - 0.05", "", "compress", text="ha|YO'Q")],
      note="h/a < 1/20 bo'lsa sdvig deformatsiyasi 1% dan kam xato beradi — Kirxhoff gipotezasi asosli."),
  fig("Silindrik bikrlik va qalinlik",
      "D = Eh³/(12(1−ν²)) — qalinlik kubga kiradi.",
      params=[fp("E", "Modul", 10, 400, 210, 5, "GPa"),
              fp("nu", "Puasson ν", 0, 0.45, 0.3, 0.01, "")],
      curves=[fc("D = Eh³/(12(1−ν²)), N·m", "E*1e9*(x*1e-3)^3/(12*(1 - nu^2))", "tension"),
              fc("Balka EI/b (ν=0)", "E*1e9*(x*1e-3)^3/12", "compress", dashed=True)],
      x=("qalinlik h, mm", "D, N·m"), x_min="1", x_max="50",
      readouts=[fr("D (h=10 mm)", "E*1e9*1e-6/(12*(1 - nu^2))", "N·m", "tension"),
                fr("Plastina/balka nisbati", "1/(1 - nu^2)", "", "mark"),
                fr("h 2× bo'lsa D", "8", "marta", "compress")],
      note="Plastina bir xil kesimdagi balkadan 1/(1−ν²) = 1,099 marta bikrroq — yon tomon ushlab turadi."),
 ],
 "pq-02": [
  fig("Egrilik va normal deformatsiya qalinlik bo'ylab",
      "Deformatsiya o'rta sirtdan masofaga chiziqli proporsional.",
      params=[fp("kx", "Egrilik κx", 0.001, 2, 0.2, 0.001, "1/m"),
              fp("h", "Qalinlik", 1, 50, 10, 1, "mm")],
      curves=[fc("εx = −zκx, ‰", "-x*1e-3*kx*1000", "tension"),
              fc("O'rta sirt", "0", "rule", dashed=True)],
      x=("z, mm", "εx, ‰"), x_min="-h/2", x_max="h/2",
      readouts=[fr("ε yuqori sirtda", "h/2*1e-3*kx*1000", "‰", "tension"),
                fr("ε pastki sirtda", "-h/2*1e-3*kx*1000", "‰", "compress"),
                fr("O'rta sirtda", "0", "‰", "rule")],
      note="O'rta sirt cho'zilmaydi ham, siqilmaydi ham — bu Kirxhoff gipotezasining asosiy natijasi."),
  fig("Buralish egriligi: burchaklarning ko'tarilishi",
      "κxy plastina burchaklarini burab ko'taradi.",
      params=[fp("kxy", "Buralish egriligi", 0, 2, 0.3, 0.01, "1/m"),
              fp("a", "Plastina tomoni", 0.2, 5, 1, 0.1, "m")],
      curves=[fc("w(x,y=a) = −κxy·x·a, mm", "-kxy*x*a*1000", "tension"),
              fc("w(x,y=0) = 0", "0", "rule", dashed=True)],
      x=("x, m", "ko'chish w, mm"), x_min="0", x_max="a",
      readouts=[fr("Burchak ko'chishi", "-kxy*a^2*1000", "mm", "tension"),
                fr("Buralish momenti Mxy (D=1000)", "1000*(1 - 0.3)*kxy", "N·m/m", "compress"),
                fr("Gauss egriligi", "-kxy^2", "1/m²", "mark")],
      note="Sof buralishda Gauss egriligi manfiy — sirt egar shaklini oladi, bu yassilanmaydi."),
 ],
 "pq-03": [
  fig("Egish momenti va egrilik bog'lanishi",
      "Ikki yo'nalish Puasson koeffitsienti orqali bog'langan.",
      params=[fp("D", "Silindrik bikrlik", 100, 100000, 20000, 100, "N·m"),
              fp("kx", "Egrilik κx", 0.001, 2, 0.1, 0.001, "1/m"),
              fp("nu", "ν", 0, 0.45, 0.3, 0.01, "")],
      curves=[fc("Mx = −D(κx + νκy)", "-D*(kx + nu*x)", "tension"),
              fc("My = −D(κy + νκx)", "-D*(x + nu*kx)", "compress"),
              fc("Nol", "0", "rule", dashed=True)],
      x=("egrilik κy, 1/m", "moment, N·m/m"), x_min="-0.5", x_max="0.5",
      readouts=[fr("Mx (κy=0)", "-D*kx", "N·m/m", "tension"),
                fr("My (κy=0)", "-D*nu*kx", "N·m/m", "compress"),
                fr("My/Mx", "nu", "", "mark")],
      note="Silindrik egilishda ham ko'ndalang moment paydo bo'ladi: My = νMx — balkada bunday emas."),
  fig("Plastina kuchlanishi: moment va qalinlik",
      "σ = 6M/h² — qalinlik kvadrat bo'lib kiradi.",
      params=[fp("M", "Egish momenti", 10, 50000, 2000, 10, "N·m/m")],
      curves=[fc("σ_max = 6M/h²", "6*M/(x*1e-3)^2/1e6", "tension"),
              fc("[σ] = 160 MPa", "160", "rule", dashed=True)],
      x=("qalinlik h, mm", "σ_max, MPa"), x_min="2", x_max="60",
      readouts=[fr("σ (h=10 mm)", "6*M/1e-4/1e6", "MPa", "tension"),
                fr("Kerakli h ([σ]=160)", "sqrt(6*M/160e6)*1000", "mm", "compress"),
                fr("Qarshilik momenti W", "1/6", "h² ulush", "mark")],
      note="Qalinlikni 40% oshirish kuchlanishni ikki barobar kamaytiradi — bu eng arzon chora."),
 ],
 "pq-04": [
  fig("Sofi Jermen tenglamasi: yuk va og'ish",
      "D∇⁴w = q — og'ish bikrlikka teskari proporsional.",
      params=[fp("q", "Yuk", 0.1, 100, 10, 0.1, "kPa"),
              fp("a", "Plastina tomoni", 0.2, 5, 1, 0.1, "m")],
      curves=[fc("w_max = 0,00406qa⁴/D, mm", "0.00406*q*1000*a^4/x*1000", "tension"),
              fc("Ruxsat a/250", "a/250*1000", "rule", dashed=True)],
      x=("silindrik bikrlik D, N·m", "w_max, mm"), x_min="100", x_max="100000",
      readouts=[fr("w (D=20000)", "0.00406*q*1000*a^4/20000*1000", "mm", "tension"),
                fr("Ruxsat", "a/250*1000", "mm", "rule"),
                fr("Kerakli D", "0.00406*q*1000*a^4*250/a", "N·m", "mark")],
      note="Og'ish tomonning TO'RTINCHI darajasiga proporsional — o'lchamni 20% oshirish og'ishni 2 barobar oshiradi."),
  fig("Bigarmonik operator: sinus yechimi",
      "Sinus funksiyasi ∇⁴ ostida o'zini saqlaydi.",
      params=[fp("a", "Tomon a", 0.2, 5, 1, 0.1, "m")],
      curves=[fc("(π²/a² + π²/b²)² ko'paytuvchi", "(pi^2/a^2 + pi^2/x^2)^2", "tension"),
              fc("Kvadrat plastina (b=a)", "(2*pi^2/a^2)^2", "rule", dashed=True)],
      x=("tomon b, m", "∇⁴ ko'paytuvchi, 1/m⁴"), x_min="0.2", x_max="5",
      readouts=[fr("Kvadrat (b=a)", "(2*pi^2/a^2)^2", "1/m⁴", "rule"),
                fr("Uzun (b=3a)", "(pi^2/a^2 + pi^2/(9*a^2))^2", "1/m⁴", "tension"),
                fr("Nisbat", "(1 + 1/9)^2/4", "", "mark")],
      note="Uzun plastina (b→∞) silindrik egilishga o'tadi — ko'paytuvchi kvadrat plastinanikidan 4 marta kichik."),
 ],
 "pq-05": [
  fig("Chegaraviy shart turlari va og'ish",
      "Qistirish og'ishni sharnirga nisbatan keskin kamaytiradi.",
      params=[fp("q", "Yuk", 0.1, 100, 10, 0.1, "kPa"),
              fp("D", "Bikrlik", 100, 100000, 20000, 100, "N·m")],
      curves=[fc("Sharnirli: 0,00406qa⁴/D, mm", "0.00406*q*1000*x^4/D*1000", "tension"),
              fc("Qistirilgan: 0,00126qa⁴/D", "0.00126*q*1000*x^4/D*1000", "compress")],
      x=("tomon a, m", "w_max, mm"), x_min="0.2", x_max="3",
      readouts=[fr("Sharnirli (a=1 m)", "0.00406*q*1000/D*1000", "mm", "tension"),
                fr("Qistirilgan (a=1 m)", "0.00126*q*1000/D*1000", "mm", "compress"),
                fr("Kamayish", "0.00406/0.00126", "marta", "mark")],
      note="Qistirish og'ishni 3,2 marta kamaytiradi, lekin chekkada katta moment paydo qiladi."),
  fig("Kirxhoff kesuvchi kuchi va burchak reaksiyasi",
      "Burchakda to'plangan reaksiya paydo bo'ladi.",
      params=[fp("q", "Yuk", 0.1, 100, 10, 0.1, "kPa"),
              fp("a", "Tomon", 0.2, 5, 1, 0.1, "m")],
      curves=[fc("Burchak reaksiyasi R = 2Mxy, kN", "2*0.0325*q*x^2", "tension"),
              fc("Chekka reaksiya (jami/4)", "q*x^2/4", "compress")],
      x=("tomon a, m", "kuch, kN"), x_min="0.2", x_max="3",
      readouts=[fr("R burchakda (a=1 m)", "2*0.0325*q", "kN", "tension"),
                fr("Umumiy yuk", "q*a^2", "kN", "rule"),
                fr("Burchak ulushi", "100*2*0.0325/1", "%", "mark")],
      note="Burchak reaksiyasi plastinani PASTGA emas, YUQORIGA tortadi — mahkamlanmagan burchak ko'tariladi."),
 ],
 "pq-06": [
  fig("Plastinadagi Mizes kuchlanishi",
      "Ikki yo'nalishdagi momentlar birgalikda baholanadi.",
      params=[fp("Mx", "Mx", -20000, 20000, 3000, 100, "N·m/m"),
              fp("h", "Qalinlik", 2, 60, 12, 1, "mm")],
      curves=[fc("σ_ekv (Mizes)", "6*sqrt(Mx^2 - Mx*x + x^2)/(h*1e-3)^2/1e6", "tension"),
              fc("σx alohida", "6*Mx/(h*1e-3)^2/1e6", "rule", dashed=True)],
      x=("My, N·m/m", "σ_ekv, MPa"), x_min="-20000", x_max="20000",
      readouts=[fr("σ_ekv (My=0)", "6*abs(Mx)/(h*1e-3)^2/1e6", "MPa", "rule"),
                fr("σ_ekv (My=Mx)", "6*abs(Mx)/(h*1e-3)^2/1e6", "MPa", "tension"),
                fr("σ_ekv (My=−Mx)", "6*sqrt(3)*abs(Mx)/(h*1e-3)^2/1e6", "MPa", "compress")],
      note="Teng ikki o'qli egilishda Mizes bir o'qlidek qoladi; qarama-qarshi ishorada esa √3 marta oshadi."),
  fig("Qalinlik bo'ylab kuchlanish va urinma qism",
      "Normal kuchlanish chiziqli, urinma esa parabolik.",
      params=[fp("M", "Moment", 100, 20000, 3000, 100, "N·m/m"),
              fp("Q", "Kesuvchi kuch", 1, 500, 30, 1, "kN/m"),
              fp("h", "Qalinlik", 2, 60, 12, 1, "mm")],
      curves=[fc("σx(z), MPa", "12*M*x*1e-3/(h*1e-3)^3/1e6", "tension"),
              fc("τxz(z), MPa", "1.5*Q*1000/(h*1e-3)*(1 - 4*x^2/h^2)/1e6", "compress")],
      x=("z, mm", "kuchlanish, MPa"), x_min="-h/2", x_max="h/2",
      readouts=[fr("σ_max", "6*M/(h*1e-3)^2/1e6", "MPa", "tension"),
                fr("τ_max", "1.5*Q*1000/(h*1e-3)/1e6", "MPa", "compress"),
                fr("σ/τ nisbati", "6*M/(h*1e-3)^2/(1.5*Q*1000/(h*1e-3))", "", "mark")],
      note="Yupqa plastinada σ/τ odatda 10 dan katta — shuning uchun Kirxhoff nazariyasi τ ni e'tiborsiz qoldiradi."),
 ],
 "pq-07": [
  fig("Navye qatori: hadlar yaqinlashishi",
      "Og'ish uchun bir had yetarli, moment uchun esa yo'q.",
      params=[fp("q", "Yuk", 0.1, 100, 10, 0.1, "kPa"),
              fp("a", "Tomon", 0.2, 5, 1, 0.1, "m"),
              fp("D", "Bikrlik", 100, 100000, 20000, 100, "N·m")],
      curves=[fc("m=n=1 hadi, mm", "16*q*1000/(pi^6*D*(1/a^2 + 1/a^2)^2)*1000 + 0*x", "tension"),
              fc("Aniq yechim 0,00406qa⁴/D", "0.00406*q*1000*a^4/D*1000 + 0*x", "rule", dashed=True)],
      x=("hadlar soni N", "w_max, mm"), x_min="1", x_max="9",
      readouts=[fr("Birinchi had", "16*q*1000*a^4/(pi^6*D*4)*1000", "mm", "tension"),
                fr("Aniq qiymat", "0.00406*q*1000*a^4/D*1000", "mm", "rule"),
                fr("Bir hadli xato", "100*(16/(pi^6*4)/0.0040624 - 1)", "%", "mark")],
      note="Bitta had markaziy og'ishni 2,4% ga OSHIRIB yuboradi: keyingi hadlar markazda qarama-qarshi ishorada keladi."),
  fig("Tomonlar nisbati: bir hadli baho qayerda buziladi",
      "Cho'ziq plastinada uzun yo'nalish bo'yicha qo'shimcha hadlar kerak bo'ladi.",
      params=[fp("q", "Yuk", 0.1, 100, 10, 0.1, "kPa"),
              fp("a", "Qisqa tomon", 0.2, 5, 1, 0.1, "m"),
              fp("D", "Bikrlik", 100, 100000, 20000, 100, "N·m")],
      curves=[fc("Bir hadli baho, mm", "16*q*1000*a^4/(pi^6*D*(1 + 1/x^2)^2)*1000", "tension"),
              fc("Silindrik chegara 5qa⁴/384D", "5*q*1000*a^4/(384*D)*1000", "rule", dashed=True)],
      x=("b/a nisbati", "w_max, mm"), x_min="1", x_max="5",
      readouts=[fr("Bir had (b/a=1)", "16*q*1000*a^4/(pi^6*D*4)*1000", "mm", "tension"),
                fr("Aniq (b/a=1): 0,00406qa⁴/D", "0.0040624*q*1000*a^4/D*1000", "mm", "compress"),
                fr("Silindrik chegara", "5*q*1000*a^4/(384*D)*1000", "mm", "rule"),
                fr("Bir hadli xato (b/a=3)", "100*(16/(pi^6*(1+1/9)^2)/0.012234 - 1)", "%", "mark")],
      note="b/a = 1 da bir hadli xato 2,4%, b/a = 3 da esa 10,2% ga chiqadi; aniq qiymat 0,01223qa⁴/D silindrik chegara 0,01302 ga yaqin."),
 ],
 "pq-08": [
  fig("Levi yechimi: bir yo'nalishli qator",
      "Ikki qarama-qarshi chekka sharnirli bo'lsa masala ODT ga keladi.",
      params=[fp("a", "Sharnirli tomon", 0.2, 5, 1, 0.1, "m")],
      curves=[fc("α_m = mπ/a, 1/m", "x*pi/a", "tension"),
              fc("Birinchi had", "pi/a", "rule", dashed=True)],
      x=("had nomeri m", "α_m, 1/m"), x_min="1", x_max="9",
      readouts=[fr("α₁", "pi/a", "1/m", "tension"),
                fr("α₃", "3*pi/a", "1/m", "compress"),
                fr("So'nish masofasi 1/α₁", "a/pi", "m", "mark")],
      note="Yuqori hadlar e^{−αy} bo'yicha tez so'nadi — shuning uchun Levi qatori 3-5 had bilan yetarli."),
  fig("Uzun plastina: silindrik egilishning ikki chegaraviy holati",
      "Levi yechimining chegaraviy holati aniq formulaga keladi.",
      params=[fp("q", "Yuk", 0.1, 100, 10, 0.1, "kPa"),
              fp("D", "Bikrlik", 100, 100000, 20000, 100, "N·m")],
      curves=[fc("Sharnirli: 5qa⁴/(384D), mm", "5*q*1000*x^4/(384*D)*1000", "tension"),
              fc("Qistirilgan: qa⁴/(384D)", "q*1000*x^4/(384*D)*1000", "compress")],
      x=("qisqa tomon a, m", "w_max, mm"), x_min="0.2", x_max="3",
      readouts=[fr("Sharnirli (a=1 m)", "5*q*1000/(384*D)*1000", "mm", "tension"),
                fr("Qistirilgan (a=1 m)", "q*1000/(384*D)*1000", "mm", "compress"),
                fr("Nisbat", "5", "marta", "mark"),
                fr("Qistirish momenti qa²/12", "q*1000/12", "N·m/m", "rule")],
      note="Chekka shartlari og'ishni aynan 5 marta farqlantiradi — Levi yechimi bu ikki holat orasida yotadi."),
 ],
 "pq-09": [
  fig("Ritz usuli nimani kafolatlaydi",
      "Energetik baho pastdan, markaziy og'ish esa yuqoridan chiqishi mumkin.",
      params=[fp("q", "Yuk", 0.1, 100, 10, 0.1, "kPa"),
              fp("a", "Tomon", 0.2, 5, 1, 0.1, "m"),
              fp("D", "Bikrlik", 100, 100000, 20000, 100, "N·m")],
      curves=[fc("Bir hadli Ritz w_max, mm", "16*q*1000*x^4/(pi^6*D*4)*1000", "tension"),
              fc("Aniq w_max = 0,0040624qa⁴/D", "0.0040624*q*1000*x^4/D*1000", "compress")],
      x=("tomon a, m", "w_max, mm"), x_min="0.2", x_max="3",
      readouts=[fr("Ritz w_max", "16*q*1000*a^4/(pi^6*D*4)*1000", "mm", "tension"),
                fr("Aniq w_max", "0.0040624*q*1000*a^4/D*1000", "mm", "compress"),
                fr("Markazdagi xato", "100*(16/(pi^6*4)/0.0040624 - 1)", "%", "mark"),
                fr("Ish bo'yicha o'rtacha xato", "100*(0.00068341/0.00069000 - 1)", "%", "rule")],
      note="Ritz YUKNING ISHINI (ya'ni o'rtacha og'ishni) 0,96% ga kam baholaydi, lekin markazdagi qiymatni 2,4% ga oshirib yuboradi — kafolat energiyaga tegishli, nuqtaga emas."),
  fig("Galerkin usuli: qoldiq ortogonalligi",
      "Qoldiq sinov funksiyasiga ortogonal bo'lsa koeffitsient topiladi.",
      params=[fp("q", "Yuk", 0.1, 100, 10, 0.1, "kPa"),
              fp("D", "Bikrlik", 100, 100000, 20000, 100, "N·m")],
      curves=[fc("Qoldiq integrali ∫∫R·φ dxdy", "D*x*pi^4 - 4*q*1000/pi^2", "tension"),
              fc("Nol (yechim)", "0", "rule", dashed=True)],
      x=("koeffitsient A, m", "qoldiq"), x_min="0", x_max="0.01",
      readouts=[fr("Yechim A", "16*q*1000/(pi^6*D*4)", "m", "mark"),
                fr("w_max = A", "16*q*1000/(pi^6*D*4)*1000", "mm", "tension"),
                fr("Ritz bilan bir xilmi", "0", "", "compress", text="ha|yo'q")],
      note="Sinov funksiyasi chegaraviy shartlarni qanoatlantirsa, Galerkin va Ritz aynan bir xil natija beradi."),
 ],
 "pq-10": [
  fig("Chekli ayirmalar: to'r qadamiga bog'liq aniqlik",
      "Xato qadam kvadratiga proporsional kamayadi.",
      params=[fp("q", "Yuk", 0.1, 100, 10, 0.1, "kPa"),
              fp("a", "Tomon", 0.2, 5, 1, 0.1, "m"),
              fp("D", "Bikrlik", 100, 100000, 20000, 100, "N·m")],
      curves=[fc("Ayirmalar bahosi w_max, mm", "0.0040624*q*1000*a^4/D*1000*(1 - 11.2/(100*x^2))", "tension"),
              fc("Aniq 0,0040624qa⁴/D", "0.0040624*q*1000*a^4/D*1000", "rule", dashed=True)],
      x=("bo'linishlar soni N", "w_max, mm"), x_min="2", x_max="40",
      readouts=[fr("N=4 xato", "11.2/16", "%", "tension"),
                fr("N=8 xato", "11.2/64", "%", "compress"),
                fr("N=16 xato", "11.2/256", "%", "rule"),
                fr("Noma'lumlar (N=16, Markus)", "2*225", "ta", "mark")],
      note="Sharnirli kvadrat plastinada hisoblangan haqiqiy xatolar: N=4 da 0,84%, N=8 da 0,19%, N=16 da 0,045% — ya'ni ikkinchi tartib, va baho PASTDAN yaqinlashadi."),
  fig("Bigarmonik shablon: 13 nuqtali sxema",
      "∇⁴ operatori ikki marta qo'llangan Laplasdan chiqadi.",
      params=[fp("h", "To'r qadami", 0.01, 1, 0.1, 0.01, "m")],
      curves=[fc("Markaziy koeffitsient 20/h⁴", "20/x^4", "tension"),
              fc("Qo'shni −8/h⁴", "-8/x^4", "compress"),
              fc("Joriy qadamdagi markaz", "20/h^4", "mark", dashed=True)],
      x=("qadam h, m", "koeffitsient, 1/m⁴"), x_min="0.05", x_max="0.5",
      readouts=[fr("Markaz (h=0,1)", "20/1e-4", "1/m⁴", "tension"),
                fr("Qo'shni (h=0,1)", "-8/1e-4", "1/m⁴", "compress"),
                fr("Koeffitsientlar yig'indisi", "0", "", "mark")],
      note="Barcha koeffitsientlar yig'indisi nol — bu doimiy funksiya uchun ∇⁴w = 0 bo'lishini kafolatlaydi."),
 ],
 "pq-11": [
  fig("Konsentrlangan kuch: og'ish va moment",
      "Og'ish chekli, moment esa nuqtada cheksizga intiladi.",
      params=[fp("P", "Kuch", 0.1, 100, 10, 0.1, "kN"),
              fp("a", "Tomon", 0.2, 5, 1, 0.1, "m"),
              fp("D", "Bikrlik", 100, 100000, 20000, 100, "N·m")],
      curves=[fc("Moment ~ (P/4π)ln(a/r), N·m/m", "P*1000/(4*pi)*log(a/(x*1e-3))", "tension"),
              fc("Nol", "0", "rule", dashed=True)],
      x=("kuch markazidan masofa r, mm", "M, N·m/m"), x_min="1", x_max="200",
      readouts=[fr("w_max = 0,01160Pa²/D", "0.0116*P*1000*a^2/D*1000", "mm", "compress"),
                fr("M (r=10 mm)", "P*1000/(4*pi)*log(a/0.01)", "N·m/m", "tension"),
                fr("M (r=50 mm)", "P*1000/(4*pi)*log(a/0.05)", "N·m/m", "mark")],
      note="Logarifmik cheksizlik — matematik model natijasi; amalda kuch kichik yuza bo'ylab tarqaladi."),
  fig("Chegaraviy shartlarning og'ishga ta'siri",
      "Bir xil yuk, turli mahkamlash — natija uch barobargacha farq qiladi.",
      params=[fp("q", "Yuk", 0.1, 100, 10, 0.1, "kPa"),
              fp("D", "Bikrlik", 100, 100000, 20000, 100, "N·m")],
      curves=[fc("To'rt tomoni sharnirli: 0,00406", "0.00406*q*1000*x^4/D*1000", "tension"),
              fc("To'rt tomoni qistirilgan: 0,00126", "0.00126*q*1000*x^4/D*1000", "compress"),
              fc("Ikki tomoni sharnirli (silindrik): 5/384", "5*q*1000*x^4/(384*D)*1000", "mark", dashed=True)],
      x=("tomon a, m", "w_max, mm"), x_min="0.2", x_max="3",
      readouts=[fr("Sharnirli (a=1)", "0.00406*q*1000/D*1000", "mm", "tension"),
                fr("Qistirilgan (a=1)", "0.00126*q*1000/D*1000", "mm", "compress"),
                fr("Silindrik (a=1)", "5*q*1000/(384*D)*1000", "mm", "mark")],
      note="Ikki tomonli tayanch (silindrik egilish) to'rt tomonlidan 3,2 marta ko'p og'ish beradi."),
 ],
 "pq-12": [
  fig("Ortotrop plastina: ikki yo'nalishdagi bikrlik",
      "Qovurg'a bir yo'nalishni keskin bikrlashtiradi.",
      params=[fp("D1", "Dx (qovurg'ali)", 1000, 500000, 100000, 1000, "N·m"),
              fp("q", "Yuk", 0.1, 100, 10, 0.1, "kPa"),
              fp("a", "Tomon", 0.2, 5, 1, 0.1, "m")],
      curves=[fc("Dx ulushi yuk taqsimotida", "100*D1/(D1 + x)", "tension"),
              fc("Teng taqsimot 50%", "50", "rule", dashed=True)],
      x=("Dy, N·m", "Dx yo'nalishi ulushi, %"), x_min="1000", x_max="500000",
      readouts=[fr("Dy=20000 da Dx ulushi", "100*D1/(D1 + 20000)", "%", "tension"),
                fr("Dx/Dy", "D1/20000", "", "compress"),
                fr("w (izotrop D=Dy)", "0.00406*q*1000*a^4/20000*1000", "mm", "mark")],
      note="Qovurg'ali panelda yukning katta qismi qovurg'alar yo'nalishi bo'ylab uzatiladi — hisob shuni hisobga olishi kerak."),
  fig("Gofrlangan list: ekvivalent bikrliklar",
      "Gofr bir yo'nalishda bikrlikni oshiradi, ikkinchisida kamaytiradi.",
      params=[fp("E", "Modul", 10, 400, 210, 5, "GPa"),
              fp("t", "List qalinligi", 0.3, 5, 1, 0.1, "mm"),
              fp("H", "Gofr balandligi", 2, 100, 20, 1, "mm")],
      curves=[fc("Dx ≈ EtH²/2, N·m", "E*1e9*t*1e-3*(x*1e-3)^2/2", "tension"),
              fc("Tekis list D", "E*1e9*(t*1e-3)^3/(12*0.91)", "rule", dashed=True),
              fc("Joriy gofr balandligi", "E*1e9*t*1e-3*(H*1e-3)^2/2", "mark", dashed=True)],
      x=("gofr balandligi H, mm", "Dx, N·m"), x_min="2", x_max="100",
      readouts=[fr("Dx (H=20 mm)", "E*1e9*t*1e-3*4e-4/2", "N·m", "tension"),
                fr("Tekis list D", "E*1e9*(t*1e-3)^3/(12*0.91)", "N·m", "compress"),
                fr("Kuchayish", "E*1e9*t*1e-3*4e-4/2/(E*1e9*(t*1e-3)^3/(12*0.91))", "marta", "mark")],
      note="1 mm listni 20 mm ga gofrlash uzunlamasiga bikrlikni ~2200 marta oshiradi — massa esa deyarli o'zgarmaydi."),
 ],
 "pq-13": [
  fig("Doiraviy plastina: chekka sharti va og'ish",
      "Qistirish og'ishni 4 marta kamaytiradi.",
      params=[fp("q", "Yuk", 0.1, 100, 10, 0.1, "kPa"),
              fp("D", "Bikrlik", 100, 100000, 20000, 100, "N·m"),
              fp("nu", "ν", 0, 0.45, 0.3, 0.01, "")],
      curves=[fc("Qistirilgan: qa⁴/(64D), mm", "q*1000*x^4/(64*D)*1000", "compress"),
              fc("Sharnirli: qa⁴(5+ν)/(64D(1+ν))", "q*1000*x^4*(5 + nu)/(64*D*(1 + nu))*1000", "tension")],
      x=("radius a, m", "w_max, mm"), x_min="0.1", x_max="2",
      readouts=[fr("Qistirilgan (a=1)", "q*1000/(64*D)*1000", "mm", "compress"),
                fr("Sharnirli (a=1)", "q*1000*(5 + nu)/(64*D*(1 + nu))*1000", "mm", "tension"),
                fr("Nisbat (ν=0,3)", "(5 + nu)/(1 + nu)", "marta", "mark")],
      note="ν = 0,3 da sharnirli plastina qistirilgandan aynan 4,077 marta ko'p og'adi."),
  fig("Doiraviy plastinada momentlar radius bo'ylab",
      "Qistirilgan chekkada radial moment eng katta.",
      params=[fp("q", "Yuk", 0.1, 100, 10, 0.1, "kPa"),
              fp("a", "Radius", 0.1, 2, 0.5, 0.05, "m"),
              fp("nu", "ν", 0, 0.45, 0.3, 0.01, "")],
      curves=[fc("Mr = q/16·((1+ν)a² − (3+ν)r²)", "q*1000/16*((1 + nu)*a^2 - (3 + nu)*x^2)", "tension"),
              fc("Mt = q/16·((1+ν)a² − (1+3ν)r²)", "q*1000/16*((1 + nu)*a^2 - (1 + 3*nu)*x^2)", "compress"),
              fc("Nol", "0", "rule", dashed=True)],
      x=("radius r, m", "moment, N·m/m"), x_min="0", x_max="a",
      readouts=[fr("Mr markazda", "q*1000*(1 + nu)*a^2/16", "N·m/m", "tension"),
                fr("Mr chekkada", "-q*1000*a^2/8", "N·m/m", "compress"),
                fr("Chekka/markaz nisbati", "2/(1 + nu)", "marta", "mark")],
      note="Chekkadagi moment markazdagidan 1,54 marta katta — buzilish aynan qistirish joyidan boshlanadi."),
 ],
 "pq-14": [
  fig("Halqasimon plastina: teshik og'ishni qanday o'zgartiradi",
      "Kichik teshik ham kuchlanishni sezilarli oshiradi.",
      params=[fp("a", "Tashqi radius", 0.1, 2, 0.5, 0.05, "m"),
             fp("q", "Yuk", 0.1, 100, 10, 0.1, "kPa"),
             fp("D", "Bikrlik", 100, 100000, 20000, 100, "N·m")],
      curves=[fc("Halqa yuzasi, sm²", "pi*a^2*(1 - x^2)*1e4", "tension"),
              fc("To'la disk yuzasi", "pi*a^2*1e4", "rule", dashed=True)],
      x=("b/a (teshik nisbati)", "yuza, sm²"), x_min="0", x_max="0.9",
      readouts=[fr("To'la disk w (qistirilgan)", "q*1000*a^4/(64*D)*1000", "mm", "compress"),
                fr("Yuza yo'qotish (b/a=0,3)", "9", "%", "tension"),
                fr("Yuza yo'qotish (b/a=0,5)", "25", "%", "mark")],
      note="Teshik yuzaning kichik qismini olib tashlasa ham, chekka effekti kuchlanish taqsimotini keskin o'zgartiradi."),
  fig("Aylanuvchi disk: markazdan qochma kuchlanish",
      "Kuchlanish aylanish tezligi kvadratiga proporsional.",
      params=[fp("rho", "Zichlik", 2000, 9000, 7850, 50, "kg/m³"),
              fp("R", "Disk radiusi", 0.05, 1, 0.3, 0.01, "m"),
              fp("nu", "ν", 0, 0.45, 0.3, 0.01, "")],
      curves=[fc("σ_max = (3+ν)ρω²R²/8, MPa", "(3 + nu)*rho*(x*2*pi/60)^2*R^2/8/1e6", "tension"),
              fc("[σ] = 300 MPa", "300", "rule", dashed=True)],
      x=("aylanish tezligi n, ayl/min", "σ_max, MPa"), x_min="0", x_max="30000",
      readouts=[fr("σ (n=10000)", "(3 + nu)*rho*(10000*2*pi/60)^2*R^2/8/1e6", "MPa", "tension"),
                fr("Kritik tezlik ([σ]=300)", "sqrt(300e6*8/((3 + nu)*rho*R^2))*60/(2*pi)", "ayl/min", "mark"),
                fr("Chekkada σt", "(1 - nu)*rho*(10000*2*pi/60)^2*R^2/4/1e6", "MPa", "compress")],
      note="Markaziy teshik ochish maksimal kuchlanishni aynan IKKI barobar oshiradi — turbina disklarida bu hal qiluvchi."),
 ],
 "pq-15": [
  fig("Yarim yuklangan diskning Furye koeffitsientlari",
      "Nosimmetrik yuk garmonikalarga aniq yoyiladi.",
      params=[fp("q", "Yuk intensivligi", 0.1, 100, 10, 0.1, "kPa")],
      curves=[fc("|a_n| = 2q/(πn), toq n", "2*q/(pi*x)", "tension"),
              fc("O'rtacha a₀ = q/2", "q/2", "rule", dashed=True)],
      x=("garmonika nomeri n", "koeffitsient, kPa"), x_min="1", x_max="11",
      readouts=[fr("a₀ (o'qsimmetrik qism)", "q/2", "kPa", "rule"),
                fr("a₁ (birinchi garmonika)", "2*q/pi", "kPa", "tension"),
                fr("a₃", "2*q/(3*pi)", "kPa", "compress"),
                fr("a₅", "2*q/(5*pi)", "kPa", "mark")],
      note="Yarmi yuklangan disk uchun q(θ) = q/2 + (2q/π)(cos θ − cos3θ/3 + cos5θ/5 − …): juft garmonikalar umuman yo'q, toqlari esa 1/n bo'yicha so'nadi."),
  fig("Necha garmonika yetarli: qatorning yig'ilishi",
      "Hadlar soni oshgani sari qator haqiqiy yukka yaqinlashadi.",
      params=[fp("q", "Yuk intensivligi", 0.1, 100, 10, 0.1, "kPa")],
      curves=[fc("1 had", "q/2 + 2*q/pi*cos(x*pi/180)", "tension"),
              fc("3 had", "q/2 + 2*q/pi*(cos(x*pi/180) - cos(3*x*pi/180)/3 + cos(5*x*pi/180)/5)", "compress"),
              fc("Haqiqiy yuk (yuklangan yarim)", "q", "rule", dashed=True),
              fc("Yuklanmagan yarim", "0", "rule", dashed=True)],
      x=("burchak θ, °", "yuk, kPa"), x_min="0", x_max="180",
      readouts=[fr("1 had, θ=0", "q/2 + 2*q/pi", "kPa", "tension"),
                fr("3 had, θ=0", "q/2 + 2*q/pi*(1 - 1/3 + 1/5)", "kPa", "compress"),
                fr("Aniq qiymat θ=0", "q", "kPa", "rule"),
                fr("3 hadli oshib ketish", "100*(0.5 + 2/pi*(1 - 1/3 + 1/5) - 1)", "%", "mark")],
      note="θ = 0 da bir had 1,137q, uch had esa 1,052q beradi — sakrash yaqinida Gibbs hodisasi tufayli qator har doim biroz oshib ketadi."),
 ],
 "pq-16": [
  fig("Vinkler asosi: xarakterli uzunlik",
      "Yuk faqat chekli sohada tarqaladi.",
      params=[fp("D", "Plastina bikrligi", 100, 1000000, 50000, 100, "N·m"),
              fp("k", "Asos koeffitsienti", 1, 500, 50, 1, "MN/m³")],
      curves=[fc("l = (D/k)^0,25, m", "(D/(x*1e6))^0.25", "tension"),
              fc("1 m daraja", "1", "rule", dashed=True)],
      x=("asos koeffitsienti k, MN/m³", "xarakterli uzunlik l, m"), x_min="1", x_max="500",
      readouts=[fr("l (k=50 MN/m³)", "(D/50e6)^0.25", "m", "tension"),
                fr("Ta'sir radiusi ≈ 3l", "3*(D/(k*1e6))^0.25", "m", "compress"),
                fr("w markazda (P=100 kN)", "100000/(8*k*1e6*(D/(k*1e6))^0.5)*1000", "mm", "mark")],
      note="Yuk ta'siri ~3l masofada amalda tugaydi — shuning uchun uzun poydevorni cheksiz deb hisoblash mumkin."),
  fig("Asos bikrligi va plastina og'ishi",
      "Yumshoq asosda og'ish keskin oshadi.",
      params=[fp("P", "To'plangan kuch", 1, 1000, 100, 1, "kN"),
              fp("D", "Bikrlik", 100, 1000000, 50000, 100, "N·m")],
      curves=[fc("w₀ = P/(8k l²), mm", "P*1000/(8*sqrt(x*1e6*D))*1000", "tension"),
              fc("10 mm daraja", "10", "rule", dashed=True)],
      x=("asos koeffitsienti k, MN/m³", "w₀, mm"), x_min="1", x_max="500",
      readouts=[fr("w₀ (k=10)", "P*1000/(8*sqrt(10e6*D))*1000", "mm", "tension"),
                fr("w₀ (k=100)", "P*1000/(8*sqrt(100e6*D))*1000", "mm", "compress"),
                fr("k 10× oshsa", "sqrt(10)", "marta kamayadi", "mark")],
      note="Og'ish k va D ning KVADRAT ILDIZIGA teskari — asosni 10 barobar bikrlash og'ishni atigi 3,2 marta kamaytiradi."),
 ],
 "pq-17": [
  fig("Sendvich panel: yadro balandligining roli",
      "Qoplamalarni ajratish bikrlikni kvadratik oshiradi.",
      params=[fp("E", "Qoplama moduli", 10, 400, 70, 5, "GPa"),
              fp("tf", "Qoplama qalinligi", 0.1, 5, 0.5, 0.1, "mm")],
      curves=[fc("D ≈ E·tf·c²/2, N·m", "E*1e9*tf*1e-3*(x*1e-3)^2/2", "tension"),
              fc("Yagona list (2tf)", "E*1e9*(2*tf*1e-3)^3/(12*0.91)", "rule", dashed=True)],
      x=("yadro balandligi c, mm", "D, N·m"), x_min="1", x_max="100",
      readouts=[fr("D (c=25 mm)", "E*1e9*tf*1e-3*6.25e-4/2", "N·m", "tension"),
                fr("Yagona list D", "E*1e9*(2*tf*1e-3)^3/(12*0.91)", "N·m", "compress"),
                fr("Kuchayish", "E*1e9*tf*1e-3*6.25e-4/2/(E*1e9*(2*tf*1e-3)^3/(12*0.91))", "marta", "mark")],
      note="Massa deyarli o'zgarmaydi, bikrlik esa uch tartibga o'sadi (0,5 mm qoplama, 25 mm yadro: ~1700 marta) — samolyot pollari shunday qurilgan."),
  fig("Qatlam burchagi va ekvivalent modul",
      "Tolalar yo'nalishi panel xossalarini belgilaydi.",
      params=[fp("E1", "Tola bo'ylab E₁", 50, 400, 140, 5, "GPa"),
              fp("E2", "Ko'ndalang E₂", 2, 50, 10, 0.5, "GPa"),
              fp("G12", "Siljish G₁₂", 1, 20, 5, 0.5, "GPa")],
      curves=[fc("1/E(θ), 1/GPa", "cos(x*pi/180)^4/E1 + sin(x*pi/180)^4/E2 + (1/G12 - 0.6/E1)*sin(x*pi/180)^2*cos(x*pi/180)^2", "tension"),
              fc("1/E₁", "1/E1", "rule", dashed=True)],
      x=("burchak θ, °", "1/E, 1/GPa"), x_min="0", x_max="90",
      readouts=[fr("E (θ=0°)", "E1", "GPa", "tension"),
                fr("E (θ=45°)", "1/(0.25/E1 + 0.25/E2 + 0.25*(1/G12 - 0.6/E1))", "GPa", "mark"),
                fr("E (θ=90°)", "E2", "GPa", "compress")],
      note="Formulada ν₁₂ = 0,3 qabul qilingan. 45° da modul E₁ dan o'nlab barobar kichik — shuning uchun kompozitlar ko'p burchakli qatlamlardan yig'iladi."),
 ],
 "pq-18": [
  fig("Membrana effekti: katta og'ishlarda bikrlikning oshishi",
      "Og'ish qalinlikka yetganda chiziqli nazariya xato beradi.",
      params=[fp("h", "Qalinlik", 0.5, 20, 2, 0.1, "mm")],
      curves=[fc("q_chiziqsiz/q_chiziqli", "1 + 0.488*(x/h)^2", "tension"),
              fc("Chiziqli nazariya", "1", "rule", dashed=True)],
      x=("og'ish w, mm", "kerakli yuk nisbati"), x_min="0", x_max="20",
      readouts=[fr("w/h=0,5 da", "1 + 0.488*0.25", "marta", "compress"),
                fr("w/h=1 da", "1.488", "marta", "tension"),
                fr("w/h=2 da", "1 + 0.488*4", "marta", "mark")],
      note="Qistirilgan doiraviy plastina uchun qa⁴/(Eh⁴) = 5,86(w/h) + 2,86(w/h)³; demak w = h da chiziqli nazariya bashoratidan 48,8% ko'proq yuk kerak bo'ladi."),
  fig("Membrana va egish kuchlarining ulushi",
      "Og'ish oshgani sari yuk membrana orqali uzatila boshlaydi.",
      params=[fp("h", "Qalinlik", 0.5, 20, 2, 0.1, "mm")],
      curves=[fc("Membrana ulushi, %", "100*0.488*(x/h)^2/(1 + 0.488*(x/h)^2)", "tension"),
              fc("Egish ulushi, %", "100/(1 + 0.488*(x/h)^2)", "compress"),
              fc("50% chegara", "50", "rule", dashed=True)],
      x=("og'ish w, mm", "ulush, %"), x_min="0", x_max="20",
      readouts=[fr("Membrana (w/h=1)", "100*0.488/1.488", "%", "tension"),
                fr("Membrana (w/h=2)", "100*1.952/2.952", "%", "compress"),
                fr("Teng ulush w/h", "sqrt(1/0.488)", "", "mark")],
      note="w/h = 1,43 da membrana va egish teng ulush beradi; undan keyin plastina 'membrana'dek ishlaydi."),
 ],
 "pq-19": [
  fig("Sirt ichidagi kuchlar va og'ish",
      "Cho'zuvchi kuch bikrlashtiradi, siquvchi esa yumshatadi.",
      params=[fp("q", "Ko'ndalang yuk", 0.1, 100, 10, 0.1, "kPa"),
              fp("D", "Bikrlik", 100, 100000, 20000, 100, "N·m"),
              fp("a", "Tomon", 0.2, 5, 1, 0.1, "m")],
      curves=[fc("w = w₀/(1 − N/N_kr), mm", "0.0040624*q*1000*a^4/D*1000/(1 - x)", "tension"),
              fc("Sirt ichidagi kuchsiz w₀", "0.0040624*q*1000*a^4/D*1000", "rule", dashed=True)],
      x=("N/N_kr nisbati", "og'ish w, mm"), x_min="-1", x_max="0.9",
      readouts=[fr("N/N_kr=0,5 da", "2", "marta", "tension"),
                fr("N/N_kr=0,8 da", "5", "marta", "compress"),
                fr("Cho'zilish (N/N_kr=−1)", "0.5", "marta", "mark")],
      note="Siquvchi kuch kritik qiymatning yarmiga yetganda og'ish ikki barobar oshadi — bu ustuvorlikning oldingi belgisi."),
  fig("Ustuvorlik masalasining qo'yilishi: xos qiymat",
      "Yechim faqat ma'lum yuklarda noldan farqli bo'ladi.",
      params=[fp("D", "Bikrlik", 100, 100000, 20000, 100, "N·m"),
              fp("a", "Tomon", 0.2, 5, 1, 0.1, "m")],
      curves=[fc("N_kr(m) = π²D(m + 1/m)²/a² (kvadrat)", "pi^2*D*(x + 1/x)^2/a^2/1000", "tension"),
              fc("Minimum (m=1, kvadrat)", "4*pi^2*D/a^2/1000", "rule", dashed=True)],
      x=("yarim to'lqinlar soni m", "N_kr, kN/m"), x_min="1", x_max="5",
      readouts=[fr("N_kr (m=1)", "4*pi^2*D/a^2/1000", "kN/m", "tension"),
                fr("N_kr (m=2)", "pi^2*D*(2 + 0.5)^2/a^2/1000", "kN/m", "compress"),
                fr("Kritik kuchlanish (h=5 mm)", "4*pi^2*D/a^2/0.005/1e6", "MPa", "mark")],
      note="Kvadrat plastinada minimal kritik yuk m = 1 da: plastina bitta yarim to'lqin bilan bukiladi."),
 ],
 "pq-20": [
  fig("Siqilgan plastinaning kritik yuki",
      "k koeffitsienti tomonlar nisbatiga bog'liq.",
      params=[fp("E", "Modul", 10, 400, 210, 5, "GPa"),
              fp("h", "Qalinlik", 1, 30, 5, 0.5, "mm"),
              fp("b", "Kenglik", 0.1, 3, 0.5, 0.05, "m")],
      curves=[fc("σ_kr = kπ²E/(12(1−ν²))·(h/b)², MPa", "x*pi^2*E*1e9/(12*0.91)*(h*1e-3/b)^2/1e6", "tension"),
              fc("Oqish 250 MPa", "250", "rule", dashed=True)],
      x=("ustuvorlik koeffitsienti k", "σ_kr, MPa"), x_min="2", x_max="10",
      readouts=[fr("σ_kr (k=4, sharnirli)", "4*pi^2*E*1e9/(12*0.91)*(h*1e-3/b)^2/1e6", "MPa", "tension"),
                fr("σ_kr (k=6,97, qistirilgan)", "6.97*pi^2*E*1e9/(12*0.91)*(h*1e-3/b)^2/1e6", "MPa", "compress"),
                fr("Oqishga teng h", "sqrt(250e6*12*0.91/(4*pi^2*E*1e9))*b*1000", "mm", "mark")],
      note="Qistirilgan chekka k ni 4 dan 6,97 ga oshiradi — kritik kuchlanish 74% ga ko'tariladi."),
  fig("k koeffitsienti va tomonlar nisbati",
      "Uzun plastinada k = 4 atrofida tebranadi.",
      params=[fp("m", "Yarim to'lqinlar soni", 1, 5, 1, 1, "")],
      curves=[fc("k = (m/α + α/m)²", "(m/x + x/m)^2", "tension"),
              fc("k = 4 (minimum)", "4", "rule", dashed=True)],
      x=("α = a/b", "k"), x_min="0.4", x_max="5",
      readouts=[fr("k (α=1, m=1)", "(1/1 + 1)^2/1", "", "tension"),
                fr("k (α=2, m=1)", "(0.5 + 2)^2", "", "compress"),
                fr("k (α=2, m=2)", "(1 + 1)^2", "", "mark")],
      note="α = √2 da m = 1 dan m = 2 ga o'tish yuz beradi — bukilish shakli sakrab o'zgaradi, k esa 4 ga qaytadi."),
 ],
 "pq-21": [
  fig("Siljishda bukilish koeffitsienti",
      "Sof siljishda k siqilishdagidan sezilarli katta.",
      params=[fp("E", "Modul", 10, 400, 210, 5, "GPa"),
              fp("h", "Qalinlik", 1, 30, 4, 0.5, "mm"),
              fp("b", "Kenglik", 0.1, 3, 0.4, 0.05, "m")],
      curves=[fc("τ_kr = k_sπ²E(h/b)²/(12(1−ν²)), MPa", "(5.34 + 4/x^2)*pi^2*E*1e9/(12*0.91)*(h*1e-3/b)^2/1e6", "tension"),
              fc("Uzun plastina (k=5,34)", "5.34*pi^2*E*1e9/(12*0.91)*(h*1e-3/b)^2/1e6", "rule", dashed=True),
              fc("Siqilish (k=4)", "4*pi^2*E*1e9/(12*0.91)*(h*1e-3/b)^2/1e6", "compress", dashed=True)],
      x=("α = a/b", "kritik kuchlanish, MPa"), x_min="1", x_max="5",
      readouts=[fr("k_s (α=1)", "5.34 + 4", "", "tension"),
                fr("k_s (α=3)", "5.34 + 4/9", "", "compress"),
                fr("τ_kr (α=1)", "9.34*pi^2*E*1e9/(12*0.91)*(h*1e-3/b)^2/1e6", "MPa", "mark")],
      note="Kvadrat panelda k_s = 9,34, uzun panelda 5,34 ga tushadi — kesuvchi devorlarda qovurg'a shuning uchun qo'yiladi."),
  fig("Kritikdan keyingi ish: samarali kenglik",
      "Bukilgan plastina yuk ko'tarishda davom etadi.",
      params=[fp("scr", "Kritik kuchlanish σ_kr", 10, 300, 60, 5, "MPa"),
              fp("b", "Kenglik", 0.1, 3, 0.5, 0.05, "m")],
      curves=[fc("b_ef/b = √(σ_kr/σ)", "sqrt(scr/x)", "tension"),
              fc("To'liq kenglik", "1", "rule", dashed=True)],
      x=("chekka kuchlanishi σ, MPa", "samarali kenglik ulushi"), x_min="scr", x_max="400",
      readouts=[fr("b_ef (σ=2σ_kr)", "b*sqrt(0.5)*1000", "mm", "tension"),
                fr("b_ef (σ=σᵧ=250)", "b*sqrt(scr/250)*1000", "mm", "compress"),
                fr("Zaxira (σᵧ/σ_kr)", "250/scr", "marta", "mark")],
      note="Fon Karman samarali kenglik nazariyasi: plastina bukilgandan keyin ham oqish chegarasigacha ishlaydi."),
 ],
 "pq-22": [
  fig("Plastinaning xususiy chastotalari",
      "Chastota qalinlikka proporsional, tomon kvadratiga teskari.",
      params=[fp("E", "Modul", 10, 400, 210, 5, "GPa"),
              fp("rho", "Zichlik", 1000, 9000, 7850, 50, "kg/m³"),
              fp("a", "Tomon", 0.1, 3, 0.5, 0.05, "m")],
      curves=[fc("f₁₁ = (π/a²)√(D/ρh), Gs", "pi/a^2*sqrt(E*1e9*(x*1e-3)^3/(12*0.91)/(rho*x*1e-3))", "tension"),
              fc("50 Gs daraja", "50", "rule", dashed=True)],
      x=("qalinlik h, mm", "birinchi chastota f₁₁, Gs"), x_min="0.5", x_max="20",
      readouts=[fr("f₁₁ (h=2 mm)", "pi/a^2*sqrt(E*1e9*8e-9/(12*0.91)/(rho*2e-3))", "Gs", "tension"),
                fr("f₁₂ = f₂₁ (h=2 mm)", "5*pi/(2*a^2)*sqrt(E*1e9*8e-9/(12*0.91)/(rho*2e-3))", "Gs", "compress"),
                fr("f₁₂/f₁₁", "2.5", "marta", "rule"),
                fr("f₂₂/f₁₁", "4", "marta", "mark")],
      note="ω_mn = π²(m²/a² + n²/b²)√(D/ρh): kvadrat plastinada f₁₂ = f₂₁ — ikki tomonlama karrali chastota."),
  fig("Chastota va qalinlik: rezonansdan qochish",
      "Ishchi chastotadan uzoqlashish uchun qalinlik tanlanadi.",
      params=[fp("E", "Modul", 10, 400, 210, 5, "GPa"),
              fp("rho", "Zichlik", 1000, 9000, 7850, 50, "kg/m³"),
              fp("h", "Qalinlik", 0.5, 20, 3, 0.1, "mm")],
      curves=[fc("f₁₁(a), Gs", "pi/x^2*sqrt(E*1e9*(h*1e-3)^3/(12*0.91)/(rho*h*1e-3))", "tension"),
              fc("Dvigatel chastotasi 50 Gs", "50", "rule", dashed=True)],
      x=("tomon a, m", "f₁₁, Gs"), x_min="0.1", x_max="2",
      readouts=[fr("f₁₁ (a=0,5 m)", "pi/0.25*sqrt(E*1e9*(h*1e-3)^3/(12*0.91)/(rho*h*1e-3))", "Gs", "tension"),
                fr("50 Gs ga mos a", "sqrt(pi/50*sqrt(E*1e9*(h*1e-3)^3/(12*0.91)/(rho*h*1e-3)))", "m", "mark"),
                fr("Chastota h ga bog'liqligi", "1", "daraja", "compress")],
      note="Chastota qalinlikka BIRINCHI darajada proporsional (D ~ h³, massa ~ h) — qalinlashtirish samarali chora."),
 ],
 "pq-23": [
  fig("Rezonans egri chizig'i va demflash",
      "Demflash rezonans cho'qqisini cheklaydi.",
      params=[fp("z", "Demflash koeffitsienti ζ", 0.005, 0.5, 0.02, 0.005, "")],
      curves=[fc("Kuchayish |H|", "1/sqrt((1 - x^2)^2 + (2*z*x)^2)", "tension"),
              fc("Statik daraja", "1", "rule", dashed=True)],
      x=("chastota nisbati ω/ω₁", "dinamik kuchayish"), x_min="0", x_max="3",
      readouts=[fr("Rezonansdagi kuchayish", "1/(2*z)", "marta", "tension"),
                fr("Sifat omili Q", "1/(2*z)", "", "mark"),
                fr("ω/ω₁=2 da", "1/sqrt(9 + 16*z^2)", "marta", "compress")],
      note="ζ = 0,02 da rezonansda kuchayish 25 marta — demflashsiz plastina juda tez buziladi."),
  fig("Zarbaviy javob: to'g'ri to'rtburchak impuls spektri",
      "Dinamiklik koeffitsienti impuls davomiyligi bilan xususiy davr nisbatiga bog'liq.",
      params=[fp("T", "Xususiy davr", 0.005, 0.4, 0.05, 0.005, "s")],
      curves=[fc("D = 2sin(π·t_d/T), t_d/T ≤ 0,5", "2*sin(pi*min(x*1e-3/T, 0.5))", "tension"),
              fc("Chegara D = 2", "2", "compress", dashed=True),
              fc("Statik daraja", "1", "rule", dashed=True)],
      x=("impuls davomiyligi t_d, ms", "dinamiklik koeffitsienti D"), x_min="0", x_max="200",
      readouts=[fr("D (t_d/T=0,1)", "2*sin(pi*0.1)", "", "tension"),
                fr("D (t_d/T=0,25)", "2*sin(pi*0.25)", "", "compress"),
                fr("D (t_d/T ≥ 0,5)", "2", "", "mark"),
                fr("Xususiy chastota", "1/T", "Gs", "rule")],
      note="Demflashsiz tizim uchun aniq natija: t_d ≥ T/2 bo'lganda D har doim 2 ga teng, qisqa impulsda esa D = 2sin(πt_d/T) — masalan t_d/T = 0,1 da atigi 0,618."),
 ],
 "pq-24": [
  fig("Mindlin nazariyasi: sdvig tuzatmasi",
      "Qalin plastinada sdvig og'ishga sezilarli hissa qo'shadi.",
      params=[fp("nu", "ν", 0, 0.45, 0.3, 0.01, ""),
              fp("k", "Sdvig koeffitsienti", 0.5, 1, 0.8333, 0.0001, "")],
      curves=[fc("w_M/w_K = 1 + c(h/a)²", "1 + 2*(1 + nu)/(k*(1 - nu))*0.32*x^2", "tension"),
              fc("Kirxhoff", "1", "rule", dashed=True)],
      x=("h/a nisbati", "og'ish nisbati"), x_min="0", x_max="0.3",
      readouts=[fr("h/a=1/20 da oshish", "100*2*(1 + nu)/(k*(1 - nu))*0.32/400", "%", "tension"),
                fr("h/a=1/10 da oshish", "100*2*(1 + nu)/(k*(1 - nu))*0.32/100", "%", "compress"),
                fr("h/a=1/5 da oshish", "100*2*(1 + nu)/(k*(1 - nu))*0.32/25", "%", "mark")],
      note="Muhandislik bahosi. h/a = 1/20 da sdvig tuzatmasi 0,4% — aynan shundan Kirxhoff nazariyasining amal qilish chegarasi kelib chiqadi; h/a = 1/5 da esa u 5,7% ga chiqadi."),
  fig("Sdvig koeffitsienti va sdvig bikrligi",
      "k = 5/6 to'rtburchak kesim uchun energiya tengligidan olinadi.",
      params=[fp("G", "Siljish moduli", 1, 100, 81, 1, "GPa"),
              fp("h", "Qalinlik", 1, 100, 20, 1, "mm")],
      curves=[fc("Sdvig bikrligi kGh, MN/m", "x*G*1e9*h*1e-3/1e6", "tension"),
              fc("k=5/6 daraja", "0.8333*G*1e9*h*1e-3/1e6", "rule", dashed=True)],
      x=("sdvig koeffitsienti k", "kGh, MN/m"), x_min="0.5", x_max="1",
      readouts=[fr("kGh (k=5/6)", "0.8333*G*1e9*h*1e-3/1e6", "MN/m", "tension"),
                fr("Egish bikrligi D (ν=0,3)", "2*G*1e9*(h*1e-3)^3/(12*0.7)", "N·m", "compress"),
                fr("k = 5/6", "5/6", "", "mark")],
      note="k = 5/6 parabolik τ taqsimotining energiyasini tekis taqsimotga tenglashtirishdan chiqadi."),
 ],
 "pq-25": [
  fig("Gauss egriligi va sirt turlari",
      "Ishorasi qobiqning bikrlik xarakterini belgilaydi.",
      params=[fp("R1", "Birinchi egrilik radiusi", -10, 10, 2, 0.1, "m")],
      curves=[fc("K = 1/(R₁R₂), 1/m²", "1/(R1*x)", "tension"),
              fc("Nol egrilik (silindr)", "0", "rule", dashed=True)],
      x=("ikkinchi radius R₂, m", "Gauss egriligi K, 1/m²"), x_min="-10", x_max="10",
      readouts=[fr("Sfera (R₂=R₁)", "1/R1^2", "1/m²", "tension"),
                fr("Egar (R₂=−R₁)", "-1/R1^2", "1/m²", "compress"),
                fr("Silindr (R₂→∞)", "0", "1/m²", "rule")],
      note="K > 0 sfera (yassilanmaydi), K = 0 silindr (yassilanadi), K < 0 egar — bu qobiq ishini butunlay o'zgartiradi."),
  fig("O'rtacha egrilik va membrana kuchlari",
      "Laplas qonuni ikki radiusni bosim bilan bog'laydi.",
      params=[fp("p", "Ichki bosim", 0.01, 20, 1, 0.01, "MPa"),
              fp("t", "Qobiq qalinligi", 1, 50, 5, 0.5, "mm")],
      curves=[fc("σ = pR/(2t) (sfera), MPa", "p*x/(2*t*1e-3)*1e-3/1e3*1e3", "tension"),
              fc("σ = pR/t (silindr halqasimon)", "p*x/(t*1e-3)*1e-3/1e3*1e3", "compress")],
      x=("radius R, m", "kuchlanish, MPa"), x_min="0.05", x_max="3",
      readouts=[fr("Sfera (R=1 m)", "p*1/(2*t*1e-3)*1e-3", "MPa", "tension"),
                fr("Silindr (R=1 m)", "p*1/(t*1e-3)*1e-3", "MPa", "compress"),
                fr("Nisbat", "2", "marta", "mark")],
      note="Bir xil bosim va radiusda silindr sferadan ikki barobar ko'p kuchlanadi — ballon uchlari shuning uchun sferik."),
 ],
 "pq-26": [
  fig("Silindrik idish: ikki yo'nalishdagi kuchlanish",
      "Halqasimon kuchlanish o'qiydan ikki barobar katta.",
      params=[fp("p", "Bosim", 0.01, 20, 2, 0.01, "MPa"),
              fp("R", "Radius", 0.05, 3, 0.5, 0.01, "m")],
      curves=[fc("σ_t = pR/t, MPa", "p*R/(x*1e-3)*1e-3", "tension"),
              fc("σ_a = pR/(2t)", "p*R/(2*x*1e-3)*1e-3", "compress"),
              fc("[σ] = 160 MPa", "160", "rule", dashed=True)],
      x=("qalinlik t, mm", "kuchlanish, MPa"), x_min="1", x_max="40",
      readouts=[fr("σ_t (t=5 mm)", "p*R/5e-3*1e-3", "MPa", "tension"),
                fr("σ_a (t=5 mm)", "p*R/1e-2*1e-3", "MPa", "compress"),
                fr("Kerakli t ([σ]=160)", "p*R/160*1000", "mm", "mark")],
      note="Buzilish odatda o'q bo'ylab darz bilan boshlanadi — chunki uni halqasimon kuchlanish ochadi."),
  fig("Konus qobiq: kuchlanishning radius bo'ylab o'sishi",
      "Konusda kuchlanish uchdan asosga qarab chiziqli oshadi.",
      params=[fp("p", "Bosim", 0.01, 20, 1, 0.01, "MPa"),
              fp("t", "Qalinlik", 1, 40, 5, 0.5, "mm"),
              fp("al", "Yarim burchak", 5, 75, 30, 1, "°")],
      curves=[fc("σ_t = pr/(t·cos α), MPa", "p*x/(t*1e-3*cos(al*pi/180))*1e-3", "tension"),
              fc("Silindr (α=0) darajasi", "p*x/(t*1e-3)*1e-3", "rule", dashed=True)],
      x=("radius r, m", "σ_t, MPa"), x_min="0", x_max="1",
      readouts=[fr("σ_t (r=0,5 m)", "p*0.5/(t*1e-3*cos(al*pi/180))*1e-3", "MPa", "tension"),
                fr("Konus/silindr", "1/cos(al*pi/180)", "marta", "mark"),
                fr("Uchda (r=0)", "0", "MPa", "compress")],
      note="α = 30° da konus silindrdan 15% ko'p kuchlanadi; α = 60° da esa ikki barobar."),
 ],
 "pq-27": [
  fig("Silindrik qobiqdagi chekka effekti",
      "Chekka buzilishi eksponensial so'nadi.",
      params=[fp("R", "Radius", 0.05, 3, 0.5, 0.01, "m"),
              fp("t", "Qalinlik", 1, 40, 5, 0.5, "mm"),
              fp("nu", "ν", 0, 0.45, 0.3, 0.01, "")],
      curves=[fc("e^{−βx} so'nish", "exp(-x/((R*t*1e-3)^0.5/(3*(1 - nu^2))^0.25))", "tension"),
              fc("5% daraja", "0.05", "rule", dashed=True)],
      x=("chekkadan masofa x, m", "nisbiy amplituda"), x_min="0", x_max="0.5",
      readouts=[fr("So'nish uzunligi 1/β", "(R*t*1e-3)^0.5/(3*(1 - nu^2))^0.25", "m", "tension"),
                fr("Ta'sir zonasi ≈ 2,4√(Rt)", "2.4*sqrt(R*t*1e-3)", "m", "compress"),
                fr("√(Rt)", "sqrt(R*t*1e-3)", "m", "mark")],
      note="Chekka effekti ~2,4√(Rt) masofada tugaydi — R=0,5 m, t=5 mm uchun bu atigi 12 sm."),
  fig("Chekka momenti va mahalliy kuchlanish",
      "Qistirilgan chekkada qo'shimcha egish kuchlanishi paydo bo'ladi.",
      params=[fp("p", "Bosim", 0.01, 20, 1, 0.01, "MPa"),
              fp("R", "Radius", 0.05, 3, 0.5, 0.01, "m")],
      curves=[fc("Halqasimon membrana σ_t = pR/t, MPa", "p*R/(x*1e-3)*1e-3", "tension"),
              fc("Chekkadagi o'qiy kuchlanish (2,043pR/t)", "2.043*p*R/(x*1e-3)*1e-3", "compress")],
      x=("qalinlik t, mm", "kuchlanish, MPa"), x_min="1", x_max="40",
      readouts=[fr("Membrana σ_t (t=5 mm)", "p*R/5e-3*1e-3", "MPa", "tension"),
                fr("Chekka egish qismi (1,543pR/t)", "1.543*p*R/5e-3*1e-3", "MPa", "mark"),
                fr("Chekkada to'liq o'qiy", "2.043*p*R/5e-3*1e-3", "MPa", "compress"),
                fr("M₀ = p(1−ν/2)/(2β²)", "0.2572*p*1e6*R*5e-3", "N·m/m", "rule")],
      note="Qistirilgan chekkada M₀ = p(1−ν/2)/(2β²) = 0,2572pRt; egish kuchlanishi 1,543pR/t, o'qiy membrana bilan birga 2,043pR/t — halqasimon membranadan ikki barobardan ortiq (ν = 0,3 uchun hisoblangan)."),
 ],
 "pq-28": [
  fig("Sfera va silindr tutashuvi: mos kelmaslik",
      "Radial ko'chishlar farqi chekka kuchini keltirib chiqaradi.",
      params=[fp("p", "Bosim", 0.01, 20, 2, 0.01, "MPa"),
              fp("R", "Radius", 0.05, 3, 0.5, 0.01, "m"),
              fp("E", "Modul", 10, 400, 210, 5, "GPa"),
              fp("nu", "ν", 0, 0.45, 0.3, 0.01, "")],
      curves=[fc("Silindr Δ, mm", "p*1e6*R^2/(E*1e9*x*1e-3)*(1 - nu/2)*1000", "tension"),
              fc("Sfera Δ", "p*1e6*R^2/(E*1e9*x*1e-3)*(1 - nu)/2*1000", "compress")],
      x=("qalinlik t, mm", "radial ko'chish, mm"), x_min="1", x_max="40",
      readouts=[fr("Silindr (t=5 mm)", "p*1e6*R^2/(E*1e9*5e-3)*(1 - nu/2)*1000", "mm", "tension"),
                fr("Sfera (t=5 mm)", "p*1e6*R^2/(E*1e9*5e-3)*(1 - nu)/2*1000", "mm", "compress"),
                fr("Farq", "p*1e6*R^2/(E*1e9*5e-3)*((1 - nu/2) - (1 - nu)/2)*1000", "mm", "mark")],
      note="Ko'chishlar farqi tutashuvda chekka momenti va kesuvchi kuch tug'diradi — u membrana hisobida umuman ko'rinmaydi."),
  fig("Nega bosimli idish tubi yassi bo'lmaydi",
      "Bir xil qalinlikdagi yassi tub qobiq tubidan o'nlab barobar ko'p kuchlanadi.",
      params=[fp("p", "Bosim", 0.01, 20, 2, 0.01, "MPa"),
              fp("t", "Qalinlik", 1, 40, 5, 0.5, "mm")],
      curves=[fc("Yassi tub: σ = 3pR²/(4t²), MPa", "0.75*p*(x*1e-3)^2/(t*1e-3)^2", "tension"),
              fc("Silindr: σ_t = pR/t", "p*(x*1e-3)/(t*1e-3)", "compress"),
              fc("Yarim sferik tub: pR/(2t)", "p*(x*1e-3)/(2*t*1e-3)", "rule", dashed=True)],
      x=("radius R, mm", "σ, MPa"), x_min="50", x_max="1000",
      readouts=[fr("Yassi tub (R=500 mm)", "0.75*p*0.25/(t*1e-3)^2", "MPa", "tension"),
                fr("Silindr (R=500 mm)", "p*0.5/(t*1e-3)", "MPa", "compress"),
                fr("Yarim sferik (R=500 mm)", "p*0.5/(2*t*1e-3)", "MPa", "rule"),
                fr("Yassi/silindr = 0,75R/t", "0.75*0.5/(t*1e-3)", "marta", "mark")],
      note="Qistirilgan doiraviy plastina uchun σ_max = 3pR²/(4t²), qobiq uchun esa pR/t: nisbat aynan 0,75R/t. R/t = 100 da yassi tub 75 marta ko'p kuchlanadi — shuning uchun idish tublari sferik yoki ellipsoid qilinadi."),
 ],
 "pq-29": [
  fig("Silindrik qobiq ustuvorligi: nazariya va tajriba",
      "Nuqsonlar kritik yukni bir necha barobar kamaytiradi.",
      params=[fp("E", "Modul", 10, 400, 210, 5, "GPa"),
              fp("R", "Radius", 0.05, 3, 0.5, 0.01, "m"),
              fp("nu", "ν", 0, 0.45, 0.3, 0.01, "")],
      curves=[fc("Klassik σ_kr = Eh/(R√(3(1−ν²)))", "E*1e9*x*1e-3/(R*sqrt(3*(1 - nu^2)))/1e6", "tension"),
              fc("Tajribaviy (~0,3×)", "0.3*E*1e9*x*1e-3/(R*sqrt(3*(1 - nu^2)))/1e6", "compress")],
      x=("qalinlik h, mm", "σ_kr, MPa"), x_min="0.5", x_max="20",
      readouts=[fr("Klassik (h=2 mm)", "E*1e9*2e-3/(R*sqrt(3*(1 - nu^2)))/1e6", "MPa", "tension"),
                fr("Tajribaviy (h=2 mm)", "0.3*E*1e9*2e-3/(R*sqrt(3*(1 - nu^2)))/1e6", "MPa", "compress"),
                fr("R/h nisbati (h=2)", "R/2e-3", "", "mark")],
      note="0,3 koeffitsienti R/t ≈ 500 ga mos keladi (keyingi chizmadagi NASA SP-8007 egri chizig'iga qarang) — qobiqlar ustuvorligi nazariya tajribadan uch barobar yuqori chiqadigan kam sonli sohalardan biri."),
  fig("NASA SP-8007 pasaytirish koeffitsienti",
      "Loyihalash normalari nuqsonlarni R/t orqali hisobga oladi.",
      params=[fp("scl", "Klassik σ_kr", 50, 2000, 500, 10, "MPa")],
      curves=[fc("Loyihaviy σ = γσ_kl, MPa", "scl*(1 - 0.901*(1 - exp(-sqrt(x)/16)))", "tension"),
              fc("Nuqsonsiz nazariya σ_kl", "scl", "rule", dashed=True)],
      x=("R/t nisbati", "kritik kuchlanish, MPa"), x_min="50", x_max="2000",
      readouts=[fr("γ (R/t=100)", "1 - 0.901*(1 - exp(-sqrt(100)/16))", "", "tension"),
                fr("γ (R/t=500)", "1 - 0.901*(1 - exp(-sqrt(500)/16))", "", "compress"),
                fr("γ (R/t=1000)", "1 - 0.901*(1 - exp(-sqrt(1000)/16))", "", "mark"),
                fr("Loyihaviy σ (R/t=500)", "scl*(1 - 0.901*(1 - exp(-sqrt(500)/16)))", "MPa", "rule")],
      note="R/t = 100 da γ = 0,58, R/t = 1000 da esa 0,22: yupqa qobiq qanchalik yupqa bo'lsa, nuqsonlarga shunchalik sezgir."),
 ],
 "pq-30": [
  fig("Qobiq tebranishlari: chastotalarning zichligi",
      "Qobiqda chastotalar plastinadagidan zichroq joylashgan.",
      params=[fp("E", "Modul", 10, 400, 210, 5, "GPa"),
              fp("rho", "Zichlik", 1000, 9000, 7850, 50, "kg/m³"),
              fp("R", "Radius", 0.05, 3, 0.5, 0.01, "m")],
      curves=[fc("Halqa chastotasi f_r = c/(2πR), Gs", "sqrt(E*1e9/rho)/(2*pi*x)", "tension"),
              fc("1000 Gs daraja", "1000", "rule", dashed=True),
              fc("Joriy radius", "sqrt(E*1e9/rho)/(2*pi*R)", "mark", dashed=True)],
      x=("radius R, m", "halqa chastotasi, Gs"), x_min="0.05", x_max="3",
      readouts=[fr("f_r (R=0,5 m)", "sqrt(E*1e9/rho)/(2*pi*0.5)", "Gs", "tension"),
                fr("Tovush tezligi materialda", "sqrt(E*1e9/rho)", "m/s", "compress"),
                fr("f_r (R=1 m)", "sqrt(E*1e9/rho)/(2*pi)", "Gs", "mark")],
      note="Halqa chastotasi — qobiq akustikasining tabiiy chegarasi: undan pastda egish, yuqorida membrana rejimi hukmron."),
  fig("Donnell tenglamasi: egish va membrana hissalari",
      "To'lqin uzunligi ikki mexanizm orasidagi muvozanatni belgilaydi.",
      params=[fp("R", "Radius", 0.05, 3, 0.5, 0.01, "m"),
              fp("h", "Qalinlik", 0.5, 20, 2, 0.1, "mm"),
              fp("nu", "ν", 0, 0.45, 0.3, 0.01, "")],
      curves=[fc("Egish hissasi ~ (h/λ)²", "(h*1e-3/x)^2*1000", "tension"),
              fc("Membrana hissasi ~ (λ/R)²/12", "(x/R)^2/12*1000", "compress")],
      x=("to'lqin uzunligi λ, m", "nisbiy hissa ×10³"), x_min="0.01", x_max="1",
      readouts=[fr("Chekka effekti uzunligi 1/β", "sqrt(R*h*1e-3)/(3*(1 - nu^2))^0.25", "m", "rule"),
                fr("Teng hissa λ", "sqrt(h*1e-3*R*sqrt(12))", "m", "mark"),
                fr("√(Rh)", "sqrt(R*h*1e-3)", "m", "tension"),
                fr("Nisbat λ/√(Rh)", "12^0.25", "", "compress")],
      note="Ikki mexanizm λ ≈ 1,86√(Rh) da teng hissa qo'shadi — chekka effekti uzunligi ham aynan shu tartibda."),
 ],
}
