"""SU — sonli usullar mavzulari uchun interaktiv chizmalar."""

from __future__ import annotations

from content.curriculum.figures.base import fc, fig, fp, fr

FIGURES = {
 "su-01": [
  fig("Analitik va sonli yechim: qaysi biri qachon",
      "Masala murakkablashgani sari analitik yechim imkoniyati tugaydi.",
      params=[fp("n", "Erkinlik darajalari", 1, 6, 4, 1, "lg N")],
      curves=[fc("To'g'ri yechish ~ N³/3", "3*x - log(3)/log(10)", "tension"),
              fc("Iterativ ~ 50N", "x + log(50)/log(10)", "compress"),
              fc("1 sekundlik hisob (10⁹ amal)", "9", "rule", dashed=True),
              fc("Joriy N: to'g'ri yechish", "3*n - log(3)/log(10)", "mark", dashed=True)],
      x=("lg N", "lg(amallar soni)"), x_min="1", x_max="7",
      readouts=[fr("N=10⁴ to'g'ri", "1e12/3", "amal", "tension"),
                fr("N=10⁴ iterativ", "50*1e4", "amal", "compress"),
                fr("Tejash", "1e12/3/(50*1e4)", "marta", "mark")],
      note="10⁴ noma'lumda to'g'ri yechish iterativdan ~667 ming marta qimmat — shuning uchun katta masalalarda iteratsiya."),
  fig("Modelning aniqligi va hisob narxi",
      "To'rni maydalash xatoni kamaytiradi, lekin narxni oshiradi.",
      params=[fp("p", "Yaqinlashish tartibi", 1, 4, 2, 1, "")],
      curves=[fc("Xato ~ h^p, %", "100*(1/x)^p", "tension"),
              fc("Hisob vaqti ~ N² (2D)", "x^2/100", "compress"),
              fc("1% chegara", "1", "rule", dashed=True)],
      x=("to'r bo'linishlari N", "xato, %  /  nisbiy vaqt"), x_min="2", x_max="100",
      readouts=[fr("N=10 xato (p=2)", "100/100", "%", "tension"),
                fr("N=100 xato (p=2)", "100/10000", "%", "compress"),
                fr("Vaqt oshishi", "100", "marta", "mark")],
      note="Ikkinchi tartibli usulda to'rni 10 marta maydalash xatoni 100 marta kamaytiradi, vaqtni esa 100 marta oshiradi."),
 ],
 "su-02": [
  fig("Mashina epsiloni va suzuvchi nuqta aniqligi",
      "Bitlar soni ifodalanadigan raqamlar sonini belgilaydi.",
      params=[fp("b", "Mantissa bitlari", 10, 60, 52, 1, "")],
      curves=[fc("ε = 2^(−t)", "2^(-x)", "tension"),
              fc("double: 2⁻⁵²", "2^(-52)", "rule", dashed=True),
              fc("Joriy mantissa", "2^(-b)", "mark", dashed=True)],
      x=("mantissa bitlari t", "mashina epsiloni"), x_min="10", x_max="60",
      readouts=[fr("ε (double, t=52)", "2^(-52)", "", "tension"),
                fr("O'nlik raqamlar (t+1 bit)", "(b + 1)*log(2)/log(10)", "ta", "compress"),
                fr("ε (float, t=23)", "2^(-23)", "", "mark")],
      note="Yashirin bitni ham hisoblaganda double 53·lg2 = 15,95 o'nlik raqam beradi; float esa atigi 7,22 — muhandislik hisoblarida double standart."),
  fig("Yaqin sonlarni ayirish: aniqlik yo'qolishi",
      "Bir-biriga yaqin sonlarni ayirish muhim raqamlarni yo'q qiladi.",
      params=[fp("d", "Arifmetika aniqligi", 7, 17, 16, 1, "o'nlik raqam")],
      curves=[fc("Qolgan aniq raqamlar", "d + log(x)/log(10)", "tension"),
              fc("Hech narsa qolmadi", "0", "rule", dashed=True),
              fc("Boshlang'ich aniqlik", "d", "compress", dashed=True)],
      x=("nisbiy ayirma |a−b|/a", "qolgan raqamlar"), x_min="1e-16", x_max="1",
      readouts=[fr("Ayirma 10⁻⁸ da qolgan", "d - 8", "raqam", "tension"),
                fr("Ayirma 10⁻¹² da qolgan", "d - 12", "raqam", "compress"),
                fr("Hammasi yo'qoladigan ayirma", "10^(0-d)", "", "mark")],
      note="Kvadrat tenglamada b² ≫ 4ac bo'lsa bir ildiz aynan shunday yo'qoladi — formula qayta yoziladi."),
 ],
 "su-03": [
  fig("Ayirma sxemalarining aniqligi",
      "Tartib oshgani sari xato tezroq kamayadi.",
      params=[fp("C", "Xato koeffitsienti", 0.1, 10, 1, 0.1, "")],
      curves=[fc("Birinchi tartib O(h)", "C*x", "tension"),
              fc("Ikkinchi tartib O(h²)", "C*x^2", "compress"),
              fc("To'rtinchi tartib O(h⁴)", "C*x^4", "mark")],
      x=("qadam h", "kesish xatosi"), x_min="0.001", x_max="0.5",
      readouts=[fr("h=0,1 birinchi tartib", "C*0.1", "", "tension"),
                fr("h=0,1 ikkinchi tartib", "C*0.01", "", "compress"),
                fr("h=0,1 to'rtinchi tartib", "C*1e-4", "", "mark")],
      note="Bir xil qadamda to'rtinchi tartibli sxema birinchisidan 1000 marta aniqroq."),
  fig("Optimal qadam: kesish va yaxlitlash xatolari",
      "Qadamni cheksiz kichraytirib bo'lmaydi.",
      params=[fp("eps", "Mashina epsiloni", 1e-16, 1e-6, 2.2e-16, 1e-17, "")],
      curves=[fc("Kesish xatosi ~ h/2", "x/2", "tension"),
              fc("Yaxlitlash xatosi ~ 2ε/h", "2*eps/x", "compress"),
              fc("Jami xato", "x/2 + 2*eps/x", "mark")],
      x=("qadam h", "xato"), x_min="1e-12", x_max="1e-2",
      readouts=[fr("Optimal h", "2*sqrt(eps)", "", "mark"),
                fr("Minimal xato", "2*sqrt(eps)", "", "tension"),
                fr("Markaziy sxema uchun h_opt", "eps^(1/3)", "", "compress")],
      note="Oldinga ayirma uchun h_opt ≈ 2√ε ≈ 3·10⁻⁸, markaziy uchun esa ε^(1/3) ≈ 6·10⁻⁶."),
 ],
 "su-04": [
  fig("Shartlanganlik soni va yo'qoladigan raqamlar",
      "Yomon shartlangan tizimda javobning raqamlari yo'qoladi.",
      params=[fp("d", "Kirish aniqligi", 8, 16, 16, 1, "raqam")],
      curves=[fc("Qolgan aniq raqamlar", "d - x", "tension"),
              fc("Nol aniqlik", "0", "rule", dashed=True)],
      x=("lg(shartlanganlik soni κ)", "aniq raqamlar"), x_min="0", x_max="16",
      readouts=[fr("κ=10³ da qolgan", "d - 3", "raqam", "tension"),
                fr("κ=10⁸ da qolgan", "d - 8", "raqam", "compress"),
                fr("To'liq yo'qolish κ", "10^d", "", "mark")],
      note="Qoida: κ = 10^k bo'lsa javobning k ta raqami yo'qoladi — κ > 10¹⁶ da double umuman yordam bermaydi."),
  fig("Hilbert matritsasi: shartlanganlikning portlashi",
      "Kichik matritsa ham halokatli yomon shartlangan bo'lishi mumkin.",
      params=[fp("n0", "Tanlangan tartib", 2, 12, 6, 1, "")],
      curves=[fc("lg κ(H_n) ≈ 1,493n − 1,758", "1.493*x - 1.758", "tension"),
              fc("double chegarasi lg κ = 16", "16", "rule", dashed=True),
              fc("Joriy tartib n", "1.493*n0 - 1.758", "mark", dashed=True)],
      x=("matritsa tartibi n", "lg κ"), x_min="2", x_max="14",
      readouts=[fr("κ (n=6)", "10^(1.493*6 - 1.758)", "", "tension"),
                fr("κ (n=10)", "10^(1.493*10 - 1.758)", "", "compress"),
                fr("Foydasiz bo'ladigan n", "(16 + 1.758)/1.493", "", "mark")],
      note="Hisoblangan aniq qiymatlar: n=6 da lg κ = 7,17, n=10 da 13,20, n=12 da 16,22 — ya'ni n ≈ 12 dan boshlab double arifmetikada birorta ham aniq raqam qolmaydi."),
 ],
 "su-05": [
  fig("LU, Cholesky va lentali yechish narxi",
      "Matritsa tuzilishini hisobga olish narxni keskin kamaytiradi.",
      params=[fp("bw", "Lenta kengligi", 1, 200, 20, 1, "")],
      curves=[fc("To'la LU / lentali = N²/(3b²)", "x^2/(3*bw^2)", "tension"),
              fc("Cholesky / lentali = N²/(6b²)", "x^2/(6*bw^2)", "compress"),
              fc("Teng narx", "1", "rule", dashed=True)],
      x=("tizim tartibi N", "lentali yechishga nisbatan yutuq"), x_min="10", x_max="5000",
      readouts=[fr("N=1000 to'la LU", "1e9/3", "amal", "tension"),
                fr("N=1000 Cholesky", "1e9/6", "amal", "compress"),
                fr("N=1000 lentali (b=20)", "1000*400", "amal", "mark")],
      note="N=1000, b=20 da lentali yechish to'la LU dan 833 marta arzon — chekli elementlarda aynan shu ishlatiladi."),
  fig("Xotira talabi: to'la va siyrak saqlash",
      "Siyrak saqlash katta masalalarni umuman mumkin qiladi.",
      params=[fp("nnz", "Qatordagi nolmas elementlar", 3, 100, 27, 1, "")],
      curves=[fc("To'la / siyrak = 2N/(3·nnz)", "2*x/(3*nnz)", "tension"),
              fc("Teng xotira", "1", "rule", dashed=True)],
      x=("noma'lumlar soni N", "to'la saqlash necha marta qimmat"), x_min="1000", x_max="1000000",
      readouts=[fr("N=10⁵ to'la", "8*1e10/1e9", "GB", "tension"),
                fr("N=10⁵ siyrak", "12*nnz*1e5/1e9", "GB", "compress"),
                fr("16 GB da mumkin N (siyrak)", "16e9/(12*nnz)", "ta", "mark")],
      note="10⁵ noma'lumli 3D masalada to'la matritsa 80 GB, siyrak esa atigi 32 MB joy oladi."),
 ],
 "su-06": [
  fig("Iterativ usullarning yaqinlashish tezligi",
      "Gauss–Zeydel Yakobidan ikki barobar tez.",
      params=[fp("rho", "Yakobi spektral radiusi", 0.5, 0.999, 0.9, 0.001, "")],
      curves=[fc("Yakobi xatosi ρ^k", "rho^x", "tension"),
              fc("Gauss–Zeydel ρ²^k", "(rho^2)^x", "compress"),
              fc("10⁻⁶ chegara", "1e-6", "rule", dashed=True)],
      x=("iteratsiya soni k", "nisbiy xato"), x_min="0", x_max="300",
      readouts=[fr("Yakobi: 10⁻⁶ uchun k", "log(1e-6)/log(rho)", "iteratsiya", "tension"),
                fr("Gauss–Zeydel: k", "log(1e-6)/log(rho^2)", "iteratsiya", "compress"),
                fr("Tezlashtirish", "2", "marta", "mark")],
      note="ρ birga yaqinlashganda ikkala usul ham sekinlashadi — shuning uchun ko'p to'rli (multigrid) usullar kerak."),
  fig("Konjugat gradiyent va shartlanganlik",
      "CG iteratsiyalari κ ning kvadrat ildiziga proporsional.",
      params=[fp("tol", "Talab qilingan aniqlik", 1e-12, 1e-3, 1e-6, 1e-12, "")],
      curves=[fc("CG: k ≈ 0,5√κ·ln(2/tol)", "0.5*sqrt(x)*log(2/tol)", "tension"),
              fc("Gauss–Zeydel: k ~ κ", "x*log(1/tol)/2", "compress")],
      x=("shartlanganlik soni κ", "iteratsiyalar soni"), x_min="10", x_max="10000",
      readouts=[fr("CG (κ=10⁴)", "0.5*100*log(2/tol)", "iteratsiya", "tension"),
                fr("Gauss–Zeydel (κ=10⁴)", "1e4*log(1/tol)/2", "iteratsiya", "compress"),
                fr("Tezlashtirish", "1e4*log(1/tol)/(100*log(2/tol))", "marta", "mark")],
      note="CG √κ ga bog'liq bo'lgani uchun yomon shartlangan tizimlarda klassik iteratsiyalardan ancha tez: κ = 10⁴ va tol = 10⁻⁶ da ~95 marta."),
 ],
 "su-07": [
  fig("Markaziy ayirma koeffitsientlari",
      "Aniqlanmagan koeffitsientlar usuli shablonni beradi.",
      params=[fp("h", "Qadam", 0.001, 0.5, 0.1, 0.001, "")],
      curves=[fc("Birinchi hosila: (f(x+h)−f(x−h))/2h", "cos(x)", "tension"),
              fc("Ayirma bahosi", "sin(x + h)/(2*h) - sin(x - h)/(2*h)", "compress", dashed=True)],
      x=("x, rad", "hosila qiymati"), x_min="0", x_max="6.283",
      readouts=[fr("Xato koeffitsienti", "h^2/6", "", "tension"),
                fr("Xato (x=0)", "abs(1 - sin(h)/h)", "", "compress"),
                fr("Nisbiy xato", "100*abs(1 - sin(h)/h)", "%", "mark")],
      note="Markaziy ayirma f'(x) = f'(x) − h²f'''(x)/6 + … beradi: h = 0,1 da xato 0,167%."),
  fig("Ikkinchi hosila shabloni va xatosi",
      "Qadam kattalashganda shablon aniq hosiladan uzoqlashadi.",
      params=[fp("h", "Qadam", 0.01, 2, 0.5, 0.01, "")],
      curves=[fc("Aniq f'' = −sin x", "-sin(x)", "tension"),
              fc("Shablon bahosi", "(sin(x + h) - 2*sin(x) + sin(x - h))/h^2", "compress", dashed=True)],
      x=("x, rad", "ikkinchi hosila"), x_min="0", x_max="6.283",
      readouts=[fr("Xato koeffitsienti", "h^2/12", "", "tension"),
                fr("Nisbiy xato", "100*abs(1 - 2*(1 - cos(h))/h^2)", "%", "compress"),
                fr("Koeffitsientlar (1,−2,1)/h²", "1/h^2", "", "mark")],
      note="Xato h²f⁗/12 ga teng: h = 0,1 da nisbiy xato 0,0833% — birinchi hosila uchun h²/6 = 0,1667% edi, ya'ni ikki barobar kichik."),
 ],
 "su-08": [
  fig("Balka egilishini ayirmalar bilan yechish",
      "To'r maydalangani sari yechim aniq qiymatga yaqinlashadi.",
      params=[fp("q", "Yuk", 1, 100, 10, 1, "kN/m"),
              fp("L", "Oraliq", 1, 12, 6, 0.5, "m"),
              fp("EI", "Bikrlik", 100, 50000, 5000, 100, "kN·m²")],
      curves=[fc("Ayirmalar bahosi, mm", "5*q*L^4/(384*EI)*1000*(1 + 0.8/x^2)", "tension"),
              fc("Aniq 5qL⁴/(384EI)", "5*q*L^4/(384*EI)*1000", "rule", dashed=True)],
      x=("bo'linishlar soni N", "w_max, mm"), x_min="2", x_max="40",
      readouts=[fr("Aniq yechim", "5*q*L^4/(384*EI)*1000", "mm", "rule"),
                fr("N=4 baho", "5*q*L^4/(384*EI)*1000*1.05", "mm", "tension"),
                fr("N=16 baho", "5*q*L^4/(384*EI)*1000*1.003125", "mm", "compress"),
                fr("N=16 xatosi", "100*0.8/256", "%", "mark")],
      note="Markaziy ayirmalar sodda balkada w_N/w = 1 + 4/(5N²) aniq munosabatini beradi (hisoblab tekshirilgan): N = 4 da +5%, N = 16 da +0,31% — baho YUQORIDAN yaqinlashadi."),
  fig("Chegaraviy shartni sxemaga kiritish",
      "Xayoliy tugun usuli tartibni saqlaydi.",
      params=[fp("h", "Qadam", 0.01, 1, 0.1, 0.01, "m")],
      curves=[fc("Bir tomonlama shart: xato ~ h", "100*x", "tension"),
              fc("Xayoliy tugun: xato ~ h²", "100*x^2", "compress"),
              fc("1% chegara", "1", "rule", dashed=True),
              fc("Joriy qadamdagi xayoliy tugun", "100*h^2", "mark", dashed=True)],
      x=("qadam h, m", "chegaradagi xato, %"), x_min="0.01", x_max="0.5",
      readouts=[fr("h=0,1 bir tomonlama", "10", "%", "tension"),
                fr("h=0,1 xayoliy tugun", "1", "%", "compress"),
                fr("Farq", "10", "marta", "mark")],
      note="Chegarada birinchi tartibli shart butun sxemaning tartibini tushiradi — bu tez-tez uchraydigan xato."),
 ],
 "su-09": [
  fig("Besh nuqtali Laplas shabloni",
      "O'rtacha qiymat xossasi sxemada aynan saqlanadi.",
      params=[fp("h", "To'r qadami", 0.01, 0.5, 0.1, 0.01, "m")],
      curves=[fc("Markaziy koeffitsient −4/h²", "-4/x^2", "tension"),
              fc("Qo'shni +1/h²", "1/x^2", "compress"),
              fc("Nol", "0", "rule", dashed=True),
              fc("Joriy qadamdagi markaz", "-4/h^2", "mark", dashed=True)],
      x=("qadam h, m", "koeffitsient, 1/m²"), x_min="0.02", x_max="0.5",
      readouts=[fr("Markaz (h=0,1)", "-4/0.01", "1/m²", "tension"),
                fr("Qo'shni (h=0,1)", "1/0.01", "1/m²", "compress"),
                fr("Yig'indi", "0", "", "mark")],
      note="Koeffitsientlar yig'indisi nol: garmonik funksiya har bir tugunda to'rtta qo'shnisining o'rtachasiga teng."),
  fig("Puasson masalasi: noma'lumlar soni 2D va 3D da",
      "O'lcham oshgani sari narx portlaydi.",
      params=[fp("N", "Har o'q bo'yicha bo'linish", 10, 500, 100, 5, "")],
      curves=[fc("2D: N²", "x^2", "tension"),
              fc("3D: N³", "x^3", "compress"),
              fc("10⁶ chegara", "1e6", "rule", dashed=True),
              fc("Joriy N: 3D", "N^3", "mark", dashed=True)],
      x=("bo'linishlar soni N", "noma'lumlar"), x_min="10", x_max="500",
      readouts=[fr("2D (N=100)", "1e4", "ta", "tension"),
                fr("3D (N=100)", "1e6", "ta", "compress"),
                fr("3D (N=200)", "8e6", "ta", "mark")],
      note="To'rni 2 marta maydalash 3D da noma'lumlarni 8 marta oshiradi — o'lchamlilik la'nati shundan."),
 ],
 "su-10": [
  fig("Laks teoremasi: barqarorlik va yaqinlashish",
      "Muvofiqlik va barqarorlik birgalikda yaqinlashishni beradi.",
      params=[fp("nu", "Diffuziya koeffitsienti", 0.0001, 1, 0.01, 0.0001, "m²/s"),
              fp("h", "Fazo qadami", 0.001, 0.5, 0.05, 0.001, "m")],
      curves=[fc("Barqarorlik soni r = νΔt/h²", "nu*x/h^2", "tension"),
              fc("Aniq sxema chegarasi r = 0,5", "0.5", "rule", dashed=True)],
      x=("vaqt qadami Δt, s", "r"), x_min="0", x_max="1",
      readouts=[fr("Maksimal Δt (aniq sxema)", "0.5*h^2/nu", "s", "mark"),
                fr("r (Δt=0,1 s)", "nu*0.1/h^2", "", "tension"),
                fr("Barqarormi (Δt=0,1)", "nu*0.1/h^2 - 0.5", "", "compress", text="ha|YO'Q")],
      note="Aniq sxemada Δt ≤ h²/(2ν): qadamni 2 marta kichraytirish vaqt qadamini 4 marta kichraytirishga majbur qiladi."),
  fig("Oshkormas sxema: shartsiz barqarorlik",
      "Oshkormas sxemada Δt faqat aniqlik bilan cheklanadi.",
      params=[fp("nu", "Diffuziya koeffitsienti", 0.0001, 1, 0.01, 0.0001, "m²/s"),
              fp("h", "Fazo qadami", 0.001, 0.5, 0.05, 0.001, "m")],
      curves=[fc("Aniq sxema kuchaytirish |G|", "abs(1 - 4*nu*x/h^2)", "tension"),
              fc("Oshkormas |G|", "1/(1 + 4*nu*x/h^2)", "compress"),
              fc("Barqarorlik chegarasi |G|=1", "1", "rule", dashed=True)],
      x=("vaqt qadami Δt, s", "kuchaytirish koeffitsienti"), x_min="0", x_max="1",
      readouts=[fr("Aniq |G| (Δt=0,5)", "abs(1 - 2*nu/h^2)", "", "tension"),
                fr("Oshkormas |G| (Δt=0,5)", "1/(1 + 2*nu/h^2)", "", "compress"),
                fr("Oshkormas har doim barqarormi", "0", "", "mark", text="ha|yo'q")],
      note="Oshkormas sxemaning |G| har qanday Δt da birdan kichik — lekin har qadamda tizim yechiladi."),
 ],
 "su-11": [
  fig("Nyumark oilasi: barqarorlik va parametrlar",
      "γ = 1/2, β = 1/4 shartsiz barqaror o'rtacha tezlanish sxemasi.",
      params=[fp("g", "γ parametri", 0.3, 1, 0.5, 0.05, "")],
      curves=[fc("Shartsiz barqarorlik chegarasi β ≥ (γ+1/2)²/4", "(g + 0.5)^2/4 + 0*x", "tension"),
              fc("β = 1/4 (o'rtacha tezlanish)", "0.25", "rule", dashed=True),
              fc("β = 1/6 (chiziqli tezlanish)", "1/6", "compress", dashed=True)],
      x=("shartli o'q", "β"), x_min="0", x_max="1",
      readouts=[fr("Kerakli β (joriy γ)", "(g + 0.5)^2/4", "", "tension"),
                fr("γ=1/2 da kerakli β", "0.25", "", "rule"),
                fr("Shartsiz barqarormi (β=1/4)", "0.25 - (g + 0.5)^2/4", "", "mark", text="ha|YO'Q")],
      note="γ > 1/2 sun'iy demflash kiritadi va aniqlikni ikkinchidan birinchi tartibga tushiradi."),
  fig("Vaqt qadami va davr xatosi",
      "Qadam xususiy davrning qanchaligi bo'lishi kerak.",
      params=[fp("T", "Xususiy davr", 0.001, 1, 0.1, 0.001, "s")],
      curves=[fc("β=1/4: (ωΔt)²/12, %", "100*(2*pi*x*1e-3/T)^2/12", "tension"),
              fc("β=1/6: (ωΔt)²/24, %", "100*(2*pi*x*1e-3/T)^2/24", "compress"),
              fc("1% chegara", "1", "rule", dashed=True)],
      x=("vaqt qadami Δt, ms", "davr xatosi, %"), x_min="0", x_max="25",
      readouts=[fr("Δt/T=0,1 (β=1/4)", "100*(2*pi*0.1)^2/12", "%", "tension"),
                fr("Δt/T=0,1 (β=1/6)", "100*(2*pi*0.1)^2/24", "%", "compress"),
                fr("1% uchun Δt/T (β=1/4)", "sqrt(0.12)/(2*pi)", "", "mark"),
                fr("Shunga mos Δt", "sqrt(0.12)/(2*pi)*T", "s", "rule")],
      note="Sonli hisob: Δt/T = 0,1 da haqiqiy xato β=1/4 uchun +3,21%, β=1/6 uchun +1,60% — ikkala sxema ham davrni CHO'ZADI. 1% xato Δt ≈ T/18 ga to'g'ri keladi: amaliy Δt ≤ T/20 qoidasi shundan."),
 ],
 "su-12": [
  fig("CFL sharti: to'lqin tenglamasi",
      "To'lqin bir qadamda bitta katakdan ko'p yura olmaydi.",
      params=[fp("c", "To'lqin tezligi", 100, 6000, 3000, 50, "m/s"),
              fp("h", "Fazo qadami", 0.001, 1, 0.01, 0.001, "m")],
      curves=[fc("Kurant soni C = cΔt/h", "c*x/h", "tension"),
              fc("CFL chegarasi C = 1", "1", "rule", dashed=True)],
      x=("vaqt qadami Δt, s", "Kurant soni"), x_min="0", x_max="1e-5",
      readouts=[fr("Maksimal Δt", "h/c", "s", "mark"),
                fr("C (Δt=1 mks)", "c*1e-6/h", "", "tension"),
                fr("1 ms simulyatsiya uchun qadamlar", "1e-3*c/h", "ta", "compress")],
      note="Po'latda 10 mm to'rda Δt ≤ 3,33 mks — 1 ms zarb hisobi uchun kamida 300 qadam kerak."),
  fig("Sonli dispersiya: to'lqin uzunligiga bog'liqlik",
      "Bir to'lqin uzunligiga kam katak to'g'ri kelsa tezlik xato bo'ladi.",
      params=[fp("C", "Kurant soni", 0.1, 1, 0.8, 0.05, "")],
      curves=[fc("Sonli/aniq tezlik", "sin(pi*C/x)/(pi*C/x)", "tension"),
              fc("Aniq tezlik", "1", "rule", dashed=True)],
      x=("to'lqin uzunligiga to'g'ri keladigan kataklar", "tezlik nisbati"), x_min="2", x_max="40",
      readouts=[fr("10 katakda", "sin(pi*C/10)/(pi*C/10)", "", "tension"),
                fr("20 katakda", "sin(pi*C/20)/(pi*C/20)", "", "compress"),
                fr("C=1 da xato", "0", "", "mark", text="yo'q|bor")],
      note="C = 1 da sxema to'lqinni aynan uzatadi (sehrli qadam); C < 1 da qisqa to'lqinlar sekinlashadi."),
 ],
 "su-13": [
  fig("Zaif formulirovka: uzluksizlik talabining pasayishi",
      "Integrallash bo'yicha bo'laklash hosilalar tartibini kamaytiradi.",
      params=[fp("k", "Masala tartibi", 2, 4, 2, 2, "")],
      curves=[fc("Kuchli formada kerakli uzluksizlik", "x", "tension"),
              fc("Zaif formada", "x/2", "compress"),
              fc("Joriy tartib: zaif forma talabi", "k/2", "mark", dashed=True)],
      x=("differensial tenglama tartibi 2m", "kerakli C^n"), x_min="2", x_max="4",
      readouts=[fr("Ikkinchi tartib (issiqlik): kuchli", "2", "C²", "tension"),
                fr("Ikkinchi tartib: zaif", "1", "C¹", "compress"),
                fr("To'rtinchi tartib (plastina): zaif", "2", "C¹", "mark")],
      note="Zaif forma C⁰ elementlarni mumkin qiladi — CHE usulining amaliy kuchi aynan shundan."),
  fig("Galerkin: eng yaxshi yaqinlashish xossasi",
      "CHE yechimi energiya normasida eng yaqin yechimni beradi.",
      params=[fp("p", "Element tartibi", 1, 3, 1, 1, "")],
      curves=[fc("Energiya normasidagi xato ~ h^p", "100*x^p", "tension"),
              fc("Ko'chish xatosi ~ h^(p+1)", "100*x^(p + 1)", "compress"),
              fc("1% chegara", "1", "rule", dashed=True)],
      x=("element o'lchami h", "nisbiy xato, %"), x_min="0.01", x_max="0.5",
      readouts=[fr("h=0,1 energiya xatosi", "100*0.1^p", "%", "tension"),
                fr("h=0,1 ko'chish xatosi", "100*0.1^(p + 1)", "%", "compress"),
                fr("Superyaqinlashish", "1", "tartib", "mark")],
      note="Ko'chish kuchlanishdan bir tartib aniqroq chiqadi — shuning uchun kuchlanish har doim ko'chishdan yomonroq."),
 ],
 "su-14": [
  fig("Chiziqli shakl funksiyalari va birlik yig'indisi",
      "Har bir nuqtada shakl funksiyalari yig'indisi birga teng.",
      params=[fp("u1", "Birinchi tugun qiymati u₁", -2, 2, 0.4, 0.05, "mm"),
              fp("u2", "Ikkinchi tugun qiymati u₂", -2, 2, 1.6, 0.05, "mm")],
      curves=[fc("u(ξ) = N₁u₁ + N₂u₂, mm", "u1*(1 - x) + u2*x", "tension"),
              fc("N₁u₁ hissasi", "u1*(1 - x)", "compress", dashed=True),
              fc("N₂u₂ hissasi", "u2*x", "mark", dashed=True)],
      x=("normallashgan koordinata ξ", "ko'chish u, mm"), x_min="0", x_max="1",
      readouts=[fr("u (ξ=0)", "u1", "mm", "tension"),
                fr("u (ξ=0,5)", "(u1 + u2)/2", "mm", "mark"),
                fr("u (ξ=1)", "u2", "mm", "compress"),
                fr("N₁+N₂ har joyda", "1", "", "rule")],
      note="Birlik yig'indisi qattiq jism harakatini aniq ifodalashni kafolatlaydi — bu majburiy shart."),
  fig("Kvadratik element: uchta shakl funksiyasi",
      "O'rta tugun egri chiziqli o'zgarishni mumkin qiladi.",
      params=[fp("u1", "Chap tugun u₁", -2, 2, 0, 0.05, "mm"),
              fp("u2", "O'rta tugun u₂", -2, 2, 1.2, 0.05, "mm"),
              fp("u3", "O'ng tugun u₃", -2, 2, 0, 0.05, "mm")],
      curves=[fc("u(ξ) kvadratik", "u1*x*(x - 1)/2 + u2*(1 - x^2) + u3*x*(x + 1)/2", "tension"),
              fc("Chiziqli element bersa edi", "u1*(1 - x)/2 + u3*(1 + x)/2", "compress", dashed=True)],
      x=("tabiiy koordinata ξ", "ko'chish u, mm"), x_min="-1", x_max="1",
      readouts=[fr("u (ξ=0) = u₂", "u2", "mm", "tension"),
                fr("Chiziqli element (ξ=0)", "(u1 + u3)/2", "mm", "compress"),
                fr("Farq", "u2 - (u1 + u3)/2", "mm", "mark"),
                fr("N₁+N₂+N₃ har joyda", "1", "", "rule")],
      note="Kvadratik element egri chegarani ham ifodalaydi — izoparametrik yondashuvning asosiy afzalligi."),
 ],
 "su-15": [
  fig("Yig'ish: global matritsaning to'ldirilishi",
      "Elementlar umumiy tugunlarda qo'shiladi.",
      params=[fp("ne", "Elementlar soni", 2, 200, 20, 1, "")],
      curves=[fc("Nolmas kataklar ulushi, %", "100*(3*x + 1)/(x + 1)^2", "tension"),
              fc("To'la matritsa (100%)", "100", "rule", dashed=True),
              fc("Joriy element soni", "100*(3*ne + 1)/(ne + 1)^2", "mark", dashed=True)],
      x=("elementlar soni", "nolmas kataklar, %"), x_min="2", x_max="100",
      readouts=[fr("Tugunlar (20 element)", "21", "ta", "tension"),
                fr("Nolmas (20 element)", "61", "ta", "compress"),
                fr("To'la matritsa", "441", "ta", "mark")],
      note="20 elementli masalada matritsaning atigi 13,8% i nolmas — siyrak saqlash shundan tejaydi."),
  fig("Element bikrlik matritsasining xossalari",
      "Element matritsasi singulyar: qattiq jism harakati uchun.",
      params=[fp("E", "Modul", 10, 400, 210, 5, "GPa"),
              fp("A", "Kesim yuzasi", 1, 100, 10, 1, "sm²")],
      curves=[fc("k = EA/L, MN/m", "E*1e9*A*1e-4/x/1e6", "tension"),
              fc("10 MN/m daraja", "10", "rule", dashed=True)],
      x=("element uzunligi L, m", "bikrlik k, MN/m"), x_min="0.05", x_max="5",
      readouts=[fr("k (L=1 m)", "E*1e9*A*1e-4/1e6", "MN/m", "tension"),
                fr("det(k_e)", "0", "", "mark"),
                fr("Qattiq jism modalari (1D sterjen)", "1", "ta", "compress")],
      note="Element matritsasining determinanti aynan nol — chegaraviy shart qo'yilmaguncha tizim yechilmaydi."),
 ],
 "su-16": [
  fig("Gauss integrallashning aniqligi",
      "n nuqta 2n−1 tartibli ko'phadni aniq integrallaydi.",
      params=[fp("n", "Gauss nuqtalari", 1, 5, 2, 1, "")],
      curves=[fc("Aniq integrallanadigan tartib 2n−1", "2*x - 1", "tension"),
              fc("Nyuton–Kotes (n nuqta): n−1", "x - 1", "compress"),
              fc("Joriy n: Gauss", "2*n - 1", "mark", dashed=True)],
      x=("nuqtalar soni n", "ko'phad tartibi"), x_min="1", x_max="6",
      readouts=[fr("n=2 Gauss", "3", "tartib", "tension"),
                fr("n=3 Gauss", "5", "tartib", "compress"),
                fr("Chiziqli 4 tugunli element uchun", "2", "nuqta", "mark")],
      note="2×2 Gauss to'rtburchak elementni aniq integrallaydi; kamaytirilgan 1×1 esa qulflanishni oldini oladi."),
  fig("Sdvig qulflanishi: element cho'ziqligiga bog'liqlik",
      "Yupqa elementda to'liq integrallash tizimni sun'iy bikrlashtiradi.",
      params=[fp("nu", "Puasson koeffitsienti ν", 0, 0.45, 0.3, 0.01, ""),
              fp("kap", "Sdvig koeffitsienti κ", 0.5, 1, 0.8333, 0.0001, "")],
      curves=[fc("To'liq integrallash: 1 + 5(L/h)²/(12(1+ν))", "1 + kap*x^2/(2*(1 + nu))", "tension"),
              fc("Kamaytirilgan integrallash", "1", "rule", dashed=True)],
      x=("element cho'ziqligi L/h", "sun'iy bikrlik nisbati"), x_min="1", x_max="100",
      readouts=[fr("L/h=10 da", "1 + kap*100/(2*(1 + nu))", "marta", "tension"),
                fr("L/h=50 da", "1 + kap*2500/(2*(1 + nu))", "marta", "compress"),
                fr("L/h=100 da", "1 + kap*10000/(2*(1 + nu))", "marta", "mark"),
                fr("Kamaytirilgan", "1", "marta", "rule")],
      note="Hisoblab chiqarilgan aniq nisbat 1 + κG(L/h)²/E = 1 + κ(L/h)²/(2(1+ν)): ν=0,3, κ=5/6 da L/h=10 uchun 33,1, L/h=100 uchun 3206 marta — yechim amalda nolga tushadi."),
 ],
 "su-17": [
  fig("Chegaraviy shartni qo'yish: jarima usuli",
      "Jarima koeffitsienti yetarlicha katta, lekin cheksiz emas.",
      params=[fp("k", "Tizim bikrligi", 1, 1000, 100, 1, "MN/m")],
      curves=[fc("Qoldiq ko'chish, mm", "1/(1 + x)*1000/k", "tension"),
              fc("Shartlanganlik o'sishi lg", "log(1 + x)/log(10)", "compress"),
              fc("0,001 mm chegara", "0.001", "rule", dashed=True)],
      x=("jarima/bikrlik nisbati", "ko'chish, mm  /  lg κ"), x_min="1", x_max="1e10",
      readouts=[fr("Nisbat 10⁶ da qoldiq", "1e-6*1000/k", "mm", "tension"),
                fr("Shartlanganlik oshishi", "6", "tartib", "compress"),
                fr("Tavsiya etilgan nisbat", "1e6", "", "mark")],
      note="Jarima 10⁶–10⁸ oralig'ida tanlanadi: kichikroq — shart bajarilmaydi, kattaroq — matritsa buziladi."),
  fig("Natijani qayta ishlash: kuchlanishning uzilishi",
      "Tugunlarda kuchlanish elementlar bo'yicha farq qiladi.",
      params=[fp("p", "Element tartibi", 1, 2, 1, 1, "")],
      curves=[fc("Tugundagi sakrash ~ h^p, %", "100*x^p", "tension"),
              fc("Gauss nuqtasida xato ~ h^(p+1)", "100*x^(p + 1)", "compress"),
              fc("1% chegara", "1", "rule", dashed=True)],
      x=("element o'lchami h", "xato, %"), x_min="0.01", x_max="0.5",
      readouts=[fr("h=0,1 tugunda", "100*0.1^p", "%", "tension"),
                fr("h=0,1 Gauss nuqtasida", "100*0.1^(p + 1)", "%", "compress"),
                fr("Afzallik", "10", "marta", "mark")],
      note="Kuchlanish Gauss nuqtalarida eng aniq — shuning uchun professional paketlar natijani o'sha yerdan ekstrapolyatsiya qiladi."),
 ],
 "su-18": [
  fig("Adaptiv to'r: xatoning kamayish tezligi",
      "Adaptiv maydalash tekis maydalashdan tezroq yaqinlashadi.",
      params=[fp("al", "Singulyarlik ko'rsatkichi", 0.3, 1, 0.5, 0.05, "")],
      curves=[fc("Tekis to'r: xato ~ N^(−α/2)", "100*x^(-al/2)", "tension"),
              fc("Adaptiv: xato ~ N^(−p/2), p=1", "100*x^(-0.5)", "compress"),
              fc("1% chegara", "1", "rule", dashed=True)],
      x=("noma'lumlar soni N", "xato, %"), x_min="100", x_max="1000000",
      readouts=[fr("N=10⁴ tekis", "100*1e4^(-al/2)", "%", "tension"),
                fr("N=10⁴ adaptiv", "100*1e4^(-0.5)", "%", "compress"),
                fr("Afzallik", "1e4^(0.5 - al/2)", "marta", "mark")],
      note="Burchak singulyarligida (α=0,5) adaptiv to'r bir xil xato uchun 10 marta kam noma'lum talab qiladi."),
  fig("Xatoni baholash: Zenkevich–Chju indikatori",
      "Tekislangan va xom kuchlanish farqi xato o'lchovi beradi.",
      params=[fp("eta", "Nishon xato", 1, 20, 5, 0.5, "%")],
      curves=[fc("Kerakli element o'lchami nisbati", "(eta/x)^(1/2)", "tension"),
              fc("O'zgarishsiz", "1", "rule", dashed=True)],
      x=("mahalliy xato, %", "h_yangi/h_eski"), x_min="0.5", x_max="50",
      readouts=[fr("Xato 20% da", "(eta/20)^0.5", "marta", "tension"),
                fr("Xato 1% da", "(eta/1)^0.5", "marta", "compress"),
                fr("Nishon", "eta", "%", "mark")],
      note="Xato nishondan 4 barobar katta bo'lsa element o'lchami 2 marta kichraytiriladi (chiziqli element uchun)."),
 ],
 "su-19": [
  fig("Ferma elementi: burchak va bikrlik matritsasi",
      "Global bikrlik sterjen burchagiga bog'liq.",
      params=[fp("E", "Modul", 10, 400, 210, 5, "GPa"),
              fp("A", "Yuza", 1, 100, 10, 1, "sm²"),
              fp("L", "Uzunlik", 0.1, 10, 2, 0.1, "m")],
      curves=[fc("k_xx = (EA/L)cos²θ, MN/m", "E*1e9*A*1e-4/L*cos(x*pi/180)^2/1e6", "tension"),
              fc("k_yy = (EA/L)sin²θ", "E*1e9*A*1e-4/L*sin(x*pi/180)^2/1e6", "compress"),
              fc("k_xx + k_yy = EA/L", "E*1e9*A*1e-4/L/1e6", "rule", dashed=True)],
      x=("sterjen burchagi θ, °", "bikrlik, MN/m"), x_min="0", x_max="90",
      readouts=[fr("EA/L", "E*1e9*A*1e-4/L/1e6", "MN/m", "rule"),
                fr("k_xx (θ=45°)", "E*1e9*A*1e-4/L*0.5/1e6", "MN/m", "tension"),
                fr("k_xy (θ=45°)", "E*1e9*A*1e-4/L*0.5/1e6", "MN/m", "mark")],
      note="Iz (k_xx + k_yy) burchakka bog'liq emas — bu koordinata almashtirishning invariantligi."),
  fig("Ferma tugunlari va statik aniqlik",
      "2n − 3 qoidasi tizim turini belgilaydi.",
      params=[fp("n", "Tugunlar soni", 3, 50, 6, 1, "")],
      curves=[fc("Statik aniq uchun sterjenlar 2n−3", "2*x - 3", "tension"),
              fc("Joriy tugunlar soni", "n", "rule", dashed=True)],
      x=("tugunlar soni n", "sterjenlar soni"), x_min="3", x_max="50",
      readouts=[fr("Kerakli sterjenlar", "2*n - 3", "ta", "tension"),
                fr("Erkinlik darajalari", "2*n", "ta", "compress"),
                fr("Bog'lanishlar", "3", "ta", "mark")],
      note="Sterjenlar soni 2n−3 dan kam bo'lsa mexanizm (matritsa singulyar), ko'p bo'lsa statik aniqmas tizim."),
 ],
 "su-20": [
  fig("Balka elementi: bikrlik matritsasi koeffitsientlari",
      "To'rtta koeffitsient uzunlikning turli darajalarida.",
      params=[fp("EI", "Bikrlik", 100, 50000, 5000, 100, "kN·m²")],
      curves=[fc("12EI/L³, kN/m", "12*EI/x^3", "tension"),
              fc("6EI/L², kN", "6*EI/x^2", "compress"),
              fc("4EI/L, kN·m", "4*EI/x", "mark")],
      x=("element uzunligi L, m", "koeffitsient"), x_min="0.2", x_max="5",
      readouts=[fr("12EI/L³ (L=2 m)", "12*EI/8", "kN/m", "tension"),
                fr("6EI/L² (L=2 m)", "6*EI/4", "kN", "compress"),
                fr("4EI/L (L=2 m)", "4*EI/2", "kN·m", "mark")],
      note="Uzunlikni ikki marta oshirish ko'chish bikrligini 8 marta, burilish bikrligini esa atigi 2 marta kamaytiradi."),
  fig("Ermit element: tugunda aniq, element ichida taqribiy",
      "Bitta element burilishni aniq beradi, o'rtadagi salqilikni esa emas.",
      params=[fp("q", "Tarqalgan yuk", 1, 100, 10, 1, "kN/m"),
              fp("L", "Oraliq", 1, 12, 6, 0.5, "m"),
              fp("EI", "Bikrlik", 100, 50000, 5000, 100, "kN·m²")],
      curves=[fc("Aniq w(x), mm", "q*x*(L^3 - 2*L*x^2 + x^3)/(24*EI)*1000", "tension"),
              fc("Bitta Ermit element, mm", "q*L^4/(24*EI)*(x/L)*(1 - x/L)*1000", "compress"),
              fc("Nol", "0", "rule", dashed=True)],
      x=("x, m", "ko'chish w, mm"), x_min="0", x_max="L",
      readouts=[fr("Aniq w_max = 5qL⁴/384EI", "5*q*L^4/(384*EI)*1000", "mm", "tension"),
                fr("Bitta element: qL⁴/96EI", "q*L^4/(96*EI)*1000", "mm", "compress"),
                fr("O'rtadagi xato", "100*(1/96)/(5/384) - 100", "%", "mark"),
                fr("Tugundagi burilish xatosi", "0", "%", "rule")],
      note="Konsistent tugun yuklari bilan bitta element burilishni aynan qL³/24EI qilib beradi (xato nol), lekin kubik ko'phad aniq to'rtinchi darajali egri chiziqni ifodalay olmaydi: o'rtada 20% kam chiqadi."),
 ],
 "su-21": [
  fig("Teshik atrofida to'r zichligi va aniqlik",
      "Konsentratsiya sohasida elementlar mayda bo'lishi shart.",
      params=[fp("Kt", "Nazariy konsentratsiya K_t", 1.5, 6, 3, 0.1, "")],
      curves=[fc("CHE bahosi (ko'rsatkich model: K_t(1 − 1,2/n))", "Kt*(1 - 1.2/x)", "tension"),
              fc("Aniq qiymat", "Kt", "rule", dashed=True)],
      x=("teshik radiusi bo'yicha elementlar soni", "hisoblangan K_t"), x_min="2", x_max="40",
      readouts=[fr("4 element", "Kt*(1 - 0.3)", "", "tension"),
                fr("12 element", "Kt*(1 - 0.1)", "", "compress"),
                fr("Tavsiya (xato < 5%)", "24", "element", "mark")],
      note="Egri chiziq — sxematik model, aniq koeffitsient geometriyaga bog'liq. Muhim xulosa: chiziqli elementlar konsentratsiyani PASAYTIRIB ko'rsatadi, ya'ni xavfli tomonga xato qiladi — shuning uchun to'r zichligi har doim tekshiriladi."),
  fig("Tekis kuchlanish va tekis deformatsiya elementlari",
      "Bir xil to'r, ikki xil natija.",
      params=[fp("F", "Kuch", 1, 500, 100, 1, "kN"),
              fp("t", "Qalinlik", 1, 100, 10, 1, "mm"),
              fp("nu", "ν", 0, 0.45, 0.3, 0.01, "")],
      curves=[fc("Tekis kuchlanish σ_ekv, MPa", "F*1000/(x*1e-3*t*1e-3)/1e6", "tension"),
              fc("Tekis deformatsiya σ_ekv", "F*1000/(x*1e-3*t*1e-3)/1e6*sqrt(1 - nu + nu^2)", "compress")],
      x=("kenglik b, mm", "σ_ekv, MPa"), x_min="5", x_max="200",
      readouts=[fr("Tekis kuchlanish (b=50)", "F*1000/(50e-3*t*1e-3)/1e6", "MPa", "tension"),
                fr("Tekis deformatsiya (b=50)", "F*1000/(50e-3*t*1e-3)/1e6*sqrt(1 - nu + nu^2)", "MPa", "compress"),
                fr("Nisbat", "sqrt(1 - nu + nu^2)", "", "mark")],
      note="Bir o'qli cho'zilishda tekis deformatsiya Mizes ekvivalentini √(1−ν+ν²) = 0,889 marta, ya'ni 11,1% ga pasaytiradi (ν = 0,3) — element turini xato tanlash aynan shuncha xato beradi."),
 ],
 "su-22": [
  fig("Plastina elementi: qalinlik va qulflanish",
      "Yupqa plastinada Mindlin elementi qulflanishga moyil.",
      params=[fp("nu", "ν", 0, 0.45, 0.3, 0.01, ""),
              fp("kap", "Sdvig koeffitsienti κ", 0.5, 1, 0.8333, 0.0001, "")],
      curves=[fc("To'liq integrallash bikrligi", "1 + kap*x^2/(2*(1 + nu))", "tension"),
              fc("Kamaytirilgan integrallash", "1", "rule", dashed=True)],
      x=("element cho'ziqligi a/h", "sun'iy bikrlik"), x_min="1", x_max="100",
      readouts=[fr("a/h=20", "1 + kap*400/(2*(1 + nu))", "marta", "tension"),
                fr("a/h=100", "1 + kap*10000/(2*(1 + nu))", "marta", "compress"),
                fr("Yechim yo'qolishi", "1", "", "mark", text="jiddiy|—")],
      note="Sdvig qulflanishining fizikasi balka elementidagi bilan bir xil — yechim kamaytirilgan integrallash yoki maxsus formulirovkada."),
  fig("Qobiq elementi: membrana va egish erkinliklari",
      "Qobiq elementida tugunga oltita erkinlik to'g'ri keladi.",
      params=[fp("nn", "Tugunlar soni", 4, 9, 4, 1, "")],
      curves=[fc("Qobiq elementi DOF (6/tugun)", "6*x", "tension"),
              fc("Tekis masala (2/tugun)", "2*x", "compress"),
              fc("Plastina (3/tugun)", "3*x", "mark"),
              fc("Joriy element: qobiq", "6*nn", "rule", dashed=True)],
      x=("elementdagi tugunlar", "erkinlik darajalari"), x_min="3", x_max="9",
      readouts=[fr("4 tugunli qobiq", "24", "DOF", "tension"),
                fr("4 tugunli tekis", "8", "DOF", "compress"),
                fr("8 tugunli qobiq", "48", "DOF", "mark")],
      note="Oltinchi erkinlik (normal atrofida burilish) tabiiy bikrlikka ega emas — u sun'iy ravishda kiritiladi."),
 ],
 "su-23": [
  fig("Xususiy chastotalarni topish: iteratsiya narxi",
      "Barcha chastotalar emas, faqat past qismi kerak.",
      params=[fp("N", "Tizim tartibi", 100, 100000, 10000, 100, "")],
      curves=[fc("Barcha xos qiymatlar ~ N³", "N^3/1e9 + 0*x", "tension"),
              fc("Lanczos (m mod) ~ mN·nnz", "x*N*27/1e9", "compress")],
      x=("kerakli modalar soni m", "amallar, 10⁹"), x_min="1", x_max="100",
      readouts=[fr("Barchasi (N=10⁴)", "1e12/1e9", "×10⁹", "tension"),
                fr("20 moda (N=10⁴)", "20*1e4*27/1e9", "×10⁹", "compress"),
                fr("Tejash", "1e12/(20*1e4*27)", "marta", "mark")],
      note="10⁴ tartibli tizimda 20 ta moda uchun Lanczos to'liq yechimdan ~185 ming marta arzon."),
  fig("Massa matritsasi turi va chastota xatosi",
      "Konsistent massa chastotani oshirib, yig'ilgan esa kamaytirib ko'rsatadi.",
      params=[fp("f1", "Aniq chastota", 1, 1000, 50, 1, "Gs")],
      curves=[fc("Konsistent massa, Gs", "f1*(1 + pi^2/(96*x^2))", "tension"),
              fc("Yig'ilgan massa, Gs", "f1*(1 - pi^2/(96*x^2))", "compress"),
              fc("Aniq chastota", "f1", "rule", dashed=True)],
      x=("elementlar soni N", "hisoblangan chastota, Gs"), x_min="2", x_max="40",
      readouts=[fr("N=4 konsistent", "100*pi^2/(96*16)", "%", "tension"),
                fr("N=8 konsistent", "100*pi^2/(96*64)", "%", "compress"),
                fr("Ikkalasining o'rtachasi", "0", "%", "rule"),
                fr("Aniq chastota", "f1", "Gs", "mark")],
      note="Sterjen uchun hisoblangan qiymatlar: N=4 da konsistent +0,644%, yig'ilgan −0,641%; N=8 da +0,161% va −0,161%. Konsistent massa YUQORIDAN, yig'ilgan PASTDAN yaqinlashadi va ikkalasi aniq qiymatni qamrab oladi."),
 ],
 "su-24": [
  fig("Nyuton–Rafson: kvadratik yaqinlashish",
      "Har iteratsiyada aniq raqamlar soni ikki barobar oshadi.",
      params=[fp("e0", "Boshlang'ich xato", 0.01, 0.5, 0.1, 0.01, "")],
      curves=[fc("Nyuton: e_{k+1} = e_k²", "e0^(2^x)", "tension"),
              fc("O'zgartirilgan Nyuton (chiziqli)", "e0*0.5^x", "compress"),
              fc("10⁻¹² chegara", "1e-12", "rule", dashed=True)],
      x=("iteratsiya k", "xato"), x_min="0", x_max="8",
      readouts=[fr("Nyuton: 3-iteratsiya", "e0^8", "", "tension"),
                fr("Nyuton: 4-iteratsiya", "e0^16", "", "compress"),
                fr("Kerakli iteratsiyalar (10⁻¹²)", "log(log(1e-12)/log(e0))/log(2)", "ta", "mark")],
      note="e₀ = 0,1 da Nyuton 4 iteratsiyada 10⁻¹⁶ ga tushadi; o'zgartirilgan variant esa 40 dan ortiq talab qiladi."),
  fig("Yuk qadamlari va yaqinlashish",
      "Katta qadam divergensiyaga olib keladi.",
      params=[fp("Fmax", "To'liq yuk", 1, 1000, 100, 1, "kN")],
      curves=[fc("Qadam kattaligi, kN", "Fmax/x", "tension"),
              fc("Nyuton iteratsiyalari (taxminiy)", "2 + 20/x", "compress")],
      x=("yuk qadamlari soni", "kattalik / iteratsiyalar"), x_min="1", x_max="50",
      readouts=[fr("1 qadam", "Fmax", "kN", "tension"),
                fr("10 qadam", "Fmax/10", "kN", "compress"),
                fr("Jami iteratsiyalar (10 qadam)", "10*(2 + 2)", "ta", "mark")],
      note="Qadamlar soni oshsa har biri arzonlashadi, lekin jami hisob narxi oshadi — optimal nuqta izlanadi."),
 ],
 "su-25": [
  fig("DQM: tugunlar soni va aniqlik",
      "Differensial kvadratura kam tugun bilan yuqori aniqlik beradi.",
      params=[fp("C", "Xato koeffitsienti", 0.1, 10, 1, 0.1, "")],
      curves=[fc("DQM: eksponensial yaqinlashish", "100*C*exp(-0.9*x)", "tension"),
              fc("Chekli ayirmalar O(h²)", "100*C/x^2", "compress"),
              fc("1% chegara", "1", "rule", dashed=True)],
      x=("tugunlar soni N", "xato, %"), x_min="4", x_max="30",
      readouts=[fr("N=10 DQM", "100*C*exp(-9)", "%", "tension"),
                fr("N=10 ayirmalar", "100*C/100", "%", "compress"),
                fr("Afzallik", "1/(100*exp(-9))", "marta", "mark")],
      note="Chizmadagi model bo'yicha DQM 10 tugundagi aniqlikka chekli ayirmalar faqat ~90 tugun bilan yetadi. Bu faqat SILLIQ yechimlarga tegishli."),
  fig("Chebishev–Gauss–Lobatto tugunlari",
      "Tugunlar chetlarda zichlashadi.",
      params=[fp("pw", "Muqobil klasterlash darajasi", 0.3, 3, 2, 0.1, ""),
             fp("N", "Tugunlar soni", 5, 30, 11, 1, "")],
      curves=[fc("Chebishev: (1 − cos πs)/2", "(1 - cos(pi*x))/2", "tension"),
              fc("Tekis taqsimot s", "x", "rule", dashed=True),
              fc("Daraja qonuni s^p", "x^pw", "compress")],
      x=("normallashgan tugun nomeri s = i/(N−1)", "normallashgan holat"), x_min="0", x_max="1",
      readouts=[fr("Chetdagi qadam (Chebishev)", "(1 - cos(pi/(N - 1)))/2", "", "tension"),
                fr("Markazdagi qadam", "1/(N - 1)", "", "compress"),
                fr("Zichlashish nisbati", "(1/(N - 1))/((1 - cos(pi/(N - 1)))/2)", "marta", "mark"),
                fr("Daraja qonuni chetdagi qadam", "(1/(N - 1))^pw", "", "rule")],
      note="Chetlardagi zichlashish Runge hodisasini oldini oladi — tekis to'rda yuqori tartibli interpolyatsiya beqaror bo'ladi."),
 ],
 "su-26": [
  fig("BEM: o'lchamlilikning pasayishi",
      "Faqat chegara diskretlashtiriladi.",
      params=[fp("N", "Chiziqli bo'linish", 10, 200, 50, 1, "")],
      curves=[fc("CHE / BEM noma'lumlar nisbati = N/6", "x/6", "tension"),
              fc("Teng son", "1", "rule", dashed=True),
              fc("Joriy N", "N/6", "mark", dashed=True)],
      x=("chiziqli bo'linish N", "CHE noma'lumlari BEM dan necha marta ko'p"), x_min="10", x_max="200",
      readouts=[fr("CHE (N=50)", "125000", "ta", "tension"),
                fr("BEM (N=50)", "15000", "ta", "compress"),
                fr("Kamayish", "125000/15000", "marta", "mark")],
      note="BEM noma'lumlarni kamaytiradi, lekin matritsa TO'LA va NOSIMMETRIK bo'ladi — tejash har doim ham emas."),
  fig("BEM va CHE: matritsa narxi",
      "To'la matritsa katta N da BEM afzalligini yo'qotadi.",
      params=[fp("nnz", "CHE qatoridagi nolmaslar", 10, 100, 27, 1, "")],
      curves=[fc("BEM / CHE narx nisbati = 72N³/(100·nnz)", "72*x^3/(100*nnz)", "tension"),
              fc("Teng narx", "1", "rule", dashed=True)],
      x=("chiziqli bo'linish N", "BEM necha marta qimmat"), x_min="10", x_max="100",
      readouts=[fr("BEM (N=30)", "(6*900)^3/3/1e12", "×10¹²", "tension"),
                fr("CHE (N=30)", "27000*nnz*100/1e12", "×10¹²", "compress"),
                fr("Qaysi arzon (N=30)", "(6*900)^3/3 - 27000*nnz*100", "", "mark", text="BEM|CHE")],
      note="Kichik masalalarda BEM tez, katta masalalarda esa siyrak CHE yutadi — tez ko'p qutbli usullar (FMM) bu chegarani suradi."),
 ],
 "su-27": [
  fig("Spektral usul: eksponensial yaqinlashish",
      "Silliq yechimda xato eksponensial kamayadi.",
      params=[fp("k", "Yechim silliqligi", 0.3, 2, 1, 0.05, "")],
      curves=[fc("Spektral: e^(−kN)", "100*exp(-k*x)", "tension"),
              fc("Ikkinchi tartib O(N⁻²)", "100/x^2", "compress"),
              fc("To'rtinchi tartib O(N⁻⁴)", "100/x^4", "mark")],
      x=("N", "xato, %"), x_min="4", x_max="40",
      readouts=[fr("N=20 spektral", "100*exp(-20*k)", "%", "tension"),
                fr("N=20 ikkinchi tartib", "100/400", "%", "compress"),
                fr("N=20 to'rtinchi tartib", "100/160000", "%", "mark")],
      note="Eksponensial yaqinlashish faqat SILLIQ yechimda: yoriq yoki burchak bo'lsa spektral usul afzalligini yo'qotadi."),
  fig("To'rsiz usullar: ta'sir radiusi",
      "Qo'shnilar soni aniqlik va narxni belgilaydi.",
      params=[fp("d", "Tugunlar oralig'i", 0.001, 1, 0.05, 0.001, "m")],
      curves=[fc("Qo'shnilar soni (2D) ≈ π(r/d)²", "pi*(x*1e-3/d)^2", "tension"),
              fc("Minimal talab (chiziqli bazis)", "6", "rule", dashed=True)],
      x=("ta'sir radiusi r, mm", "qo'shnilar soni"), x_min="1", x_max="500",
      readouts=[fr("r/d=2 da", "pi*4", "ta", "tension"),
                fr("r/d=3 da", "pi*9", "ta", "compress"),
                fr("Matritsa to'ldirilishi (r/d=2)", "pi*4", "qatorda", "mark")],
      note="r/d = 2…3 odatiy tanlov: kichikroq bo'lsa tizim singulyar, kattaroq bo'lsa matritsa keraksiz to'la bo'ladi."),
 ],
 "su-28": [
  fig("To'r yaqinlashishi: Richardson ekstrapolyatsiyasi",
      "Uch to'rdan haqiqiy yaqinlashish tartibi topiladi.",
      params=[fp("f0", "Aniq yechim", 1, 100, 10, 0.1, ""),
              fp("p", "Yaqinlashish tartibi", 1, 4, 2, 0.5, "")],
      curves=[fc("Hisoblangan qiymat f_h", "f0*(1 + 0.5*x^p)", "tension"),
              fc("Aniq qiymat", "f0", "rule", dashed=True)],
      x=("nisbiy to'r qadami h", "hisoblangan qiymat"), x_min="0", x_max="1",
      readouts=[fr("h=1 da xato", "50", "%", "tension"),
                fr("h=0,5 da xato", "50*0.5^p", "%", "compress"),
                fr("Ekstrapolyatsiya xatosi", "0", "%", "mark")],
      note="Richardson: f ≈ f₁ + (f₁−f₂)/(r^p−1). Uchta to'r p ni ham beradi — bu V&V ning majburiy qadami."),
  fig("Verifikatsiya va validatsiya: ikki xil xato",
      "Sonli xato va model xatosi birga baholanadi.",
      params=[fp("emod", "Model xatosi", 0.5, 20, 5, 0.5, "%")],
      curves=[fc("Sonli xato ~ h²", "10*x^2", "tension"),
              fc("Model xatosi (to'rdan mustaqil)", "emod", "rule", dashed=True),
              fc("Jami xato", "sqrt((10*x^2)^2 + emod^2)", "compress")],
      x=("nisbiy to'r qadami h", "xato, %"), x_min="0", x_max="1",
      readouts=[fr("h=1 sonli", "10", "%", "tension"),
                fr("h=0,3 sonli", "10*0.09", "%", "compress"),
                fr("Chegaraviy xato (h→0)", "emod", "%", "mark")],
      note="To'rni cheksiz maydalash model xatosini kamaytirmaydi — shuning uchun tajriba bilan solishtirish (validatsiya) shart."),
 ],
 "su-29": [
  fig("Tugunlarni tartiblash va lenta kengligi",
      "Cuthill–McKee tartiblash xotirani keskin kamaytiradi.",
      params=[fp("N", "Tugunlar soni", 100, 100000, 10000, 100, "")],
      curves=[fc("Tartiblanmagan lenta ~ N/2", "N/2 + 0*x", "tension"),
              fc("Cuthill–McKee ~ √N·k", "sqrt(N)*x", "compress")],
      x=("koeffitsient k", "lenta kengligi"), x_min="1", x_max="10",
      readouts=[fr("Tartiblanmagan (N=10⁴)", "N/2", "", "tension"),
                fr("CM (k=3, N=10⁴)", "3*sqrt(N)", "", "compress"),
                fr("Tejash", "(N/2)/(3*sqrt(N))", "marta", "mark")],
      note="N=10⁴ da tartiblash lenta kengligini ~17 marta kamaytiradi, yechish narxini esa lenta KVADRATIGA proporsional tushiradi."),
  fig("Usul tanlovi: masala o'lchamiga qarab",
      "Kichik masalada to'g'ri, kattasida iterativ usul.",
      params=[fp("bw", "Lenta kengligi", 10, 1000, 100, 10, "")],
      curves=[fc("To'g'ri (lentali): N·b²", "x*bw^2/1e9", "tension"),
              fc("CG (100 iteratsiya): 100·N·27", "x*2700/1e9", "compress")],
      x=("noma'lumlar soni N", "amallar, 10⁹"), x_min="1000", x_max="10000000",
      readouts=[fr("N=10⁵ to'g'ri", "1e5*bw^2/1e9", "×10⁹", "tension"),
                fr("N=10⁵ CG", "1e5*2700/1e9", "×10⁹", "compress"),
                fr("Teng bo'ladigan b", "sqrt(2700)", "", "mark")],
      note="Lenta kengligi 52 dan katta bo'lsa iterativ usul arzonroq — 3D masalalarda b odatda mingdan oshadi."),
 ],
 "su-30": [
  fig("To'liq hisob zanjiri: xatolarning to'planishi",
      "Har bosqich o'z xatosini qo'shadi.",
      params=[fp("emod", "Model xatosi", 1, 20, 5, 0.5, "%"),
              fp("emat", "Material ma'lumoti xatosi", 1, 20, 5, 0.5, "%")],
      curves=[fc("Jami xato (kvadratik yig'indi)", "sqrt(emod^2 + emat^2 + x^2)", "tension"),
              fc("Faqat model va material", "sqrt(emod^2 + emat^2)", "rule", dashed=True)],
      x=("sonli xato, %", "jami xato, %"), x_min="0", x_max="20",
      readouts=[fr("Sonli xato 1% da jami", "sqrt(emod^2 + emat^2 + 1)", "%", "tension"),
                fr("Sonli xato 5% da jami", "sqrt(emod^2 + emat^2 + 25)", "%", "compress"),
                fr("Sonli xatoni nolga tushirsak", "sqrt(emod^2 + emat^2)", "%", "mark")],
      note="Model va material xatosi 5% bo'lsa, sonli xatoni 1% dan past tushirish deyarli hech narsa bermaydi — zaxira koeffitsienti shuning uchun kerak."),
  fig("Hisobdan qarorgacha: zaxira koeffitsienti",
      "Hisob aniqligi zaxira tanlovini belgilaydi.",
      params=[fp("etot", "Jami hisob xatosi", 1, 40, 10, 0.5, "%"),
             fp("sy", "Oqish chegarasi", 150, 900, 250, 10, "MPa")],
      curves=[fc("Kerakli zaxira n = 1/(1 − e)·1,5", "1.5/(1 - x/100)", "tension"),
              fc("Ideal hisob n = 1,5", "1.5", "rule", dashed=True),
              fc("Joriy hisob xatosi", "1.5/(1 - etot/100)", "mark", dashed=True)],
      x=("hisob xatosi, %", "kerakli zaxira n"), x_min="0", x_max="40",
      readouts=[fr("Kerakli zaxira", "1.5/(1 - etot/100)", "", "tension"),
                fr("Ruxsat etilgan [σ]", "sy/(1.5/(1 - etot/100))", "MPa", "compress"),
                fr("Aniq hisob afzalligi", "100*(1 - (1 - etot/100))", "% material", "mark")],
      note="Hisob aniqligini 20% dan 5% ga yaxshilash zaxirani 1,88 dan 1,58 ga tushiradi — ya'ni 16% material tejaydi."),
 ],
}
