"""TMM — tutash muhitlar mexanikasi mavzulari uchun interaktiv chizmalar."""

from __future__ import annotations

from content.curriculum.figures.base import fc, fig, fp, fr

FIGURES = {
 "tmm-01": [
  fig("Kontinuum gipotezasi qayerda buziladi",
      "Namuna hajmi kichrayganda o'rtacha zichlik statistik shovqinga ko'miladi.",
      params=[fp("n", "Molekulyar zichlik", 18, 27, 25, 0.5, "lg(1/m³)")],
      curves=[fc("Nisbiy tebranish 1/√N", "1/sqrt(10^n*(10^x)^3)*100", "tension"),
              fc("1% chegara", "1", "rule", dashed=True)],
      x=("lg(namuna o'lchami L, m)", "zichlikning nisbiy tebranishi, %"), x_min="-9", x_max="-4",
      readouts=[fr("L = 1 mkm da", "1/sqrt(10^n*1e-18)*100", "%", "tension"),
                fr("L = 1 nm da", "1/sqrt(10^n*1e-27)*100", "%", "compress"),
                fr("1% ga mos L", "(1e4/10^n)^(1/3)", "m", "mark")],
      note="Havoda kontinuum ~0,1 mkm dan boshlab ishlaydi; undan kichikda molekulyar dinamika kerak."),
  fig("Knudsen soni va model tanlash",
      "Kn = λ/L nisbati qaysi tenglamalar ishlashini belgilaydi.",
      params=[fp("lam", "Erkin yugurish yo'li λ", 10, 1000, 68, 1, "nm")],
      curves=[fc("Kn = λ/L", "lam*1e-9/x", "tension"),
              fc("Kn = 0,01 (kontinuum chegarasi)", "0.01", "rule", dashed=True),
              fc("Kn = 0,1 (sirpanish)", "0.1", "compress", dashed=True)],
      x=("xarakterli o'lcham L, m", "Knudsen soni"), x_min="1e-8", x_max="1e-3",
      readouts=[fr("Kn (L=1 mkm)", "lam*1e-9/1e-6", "", "tension"),
                fr("Kontinuum chegarasi L", "lam*1e-9/0.01", "m", "compress"),
                fr("L=1 mm da model", "lam*1e-9/1e-3 - 0.01", "", "mark", text="kontinuum|maxsus")],
      note="Kn < 0,01 — Navye–Stoks; 0,01…0,1 — sirpanish sharti; Kn > 10 — erkin molekulyar oqim."),
 ],
 "tmm-02": [
  fig("Tenzorning koordinata burilishidagi o'zgarishi",
      "Komponentalar o'zgaradi, invariantlar esa saqlanadi.",
      params=[fp("t11", "T₁₁", -100, 100, 60, 5, ""),
              fp("t22", "T₂₂", -100, 100, -20, 5, ""),
              fp("t12", "T₁₂", -100, 100, 30, 5, "")],
      curves=[fc("T'₁₁(θ)", "(t11+t22)/2 + (t11-t22)/2*cos(2*x*pi/180) + t12*sin(2*x*pi/180)", "tension"),
              fc("T'₂₂(θ)", "(t11+t22)/2 - (t11-t22)/2*cos(2*x*pi/180) - t12*sin(2*x*pi/180)", "compress"),
              fc("Iz T'₁₁+T'₂₂ (invariant)", "t11+t22", "rule", dashed=True)],
      x=("burilish burchagi θ, °", "komponenta qiymati"), x_min="0", x_max="180",
      readouts=[fr("Birinchi invariant", "t11+t22", "", "rule"),
                fr("Ikkinchi invariant (det)", "t11*t22 - t12^2", "", "mark"),
                fr("Asosiy qiymat λ₁", "(t11+t22)/2 + sqrt(((t11-t22)/2)^2 + t12^2)", "", "tension")],
      note="Invariantlar koordinatadan mustaqil — fizik qonunlar aynan shular orqali yoziladi."),
  fig("Indeksli yozuv: Kroneker delta va yig'indi qoidasi",
      "Takrorlangan indeks bo'yicha yig'indi olinadi.",
      params=[fp("a1", "a₁", -10, 10, 3, 0.5, ""),
              fp("a2", "a₂", -10, 10, 4, 0.5, ""),
              fp("a3", "a₃", -10, 10, 0, 0.5, "")],
      curves=[fc("aᵢaᵢ = |a|² (doimiy)", "a1^2 + a2^2 + a3^2", "rule", dashed=True),
              fc("aᵢbᵢ, b=(x,x,x)", "(a1 + a2 + a3)*x", "tension")],
      x=("b vektor komponentasi", "skalyar ko'paytma"), x_min="-5", x_max="5",
      readouts=[fr("|a|²", "a1^2 + a2^2 + a3^2", "", "rule"),
                fr("|a|", "sqrt(a1^2 + a2^2 + a3^2)", "", "tension"),
                fr("δᵢᵢ (3 o'lchamda)", "3", "", "mark")],
      note="δᵢᵢ = 3 — indeksli yozuvning eng ko'p uchraydigan xatosi shu yerda: δᵢᵢ ≠ 1."),
 ],
 "tmm-03": [
  fig("Lagranj va Eyler tavsifi: zarracha yo'li",
      "Bir xil harakat ikki xil usulda tasvirlanadi.",
      params=[fp("k", "Cho'zilish tezligi", 0.05, 2, 0.5, 0.05, "1/s"),
              fp("X0", "Boshlang'ich holat X", 0.1, 5, 1, 0.1, "m")],
      curves=[fc("x(t) = X₀e^{kt}", "X0*exp(k*x)", "tension"),
              fc("Boshlang'ich holat", "X0", "rule", dashed=True)],
      x=("vaqt t, s", "joriy holat x, m"), x_min="0", x_max="3",
      readouts=[fr("x (t=1 s)", "X0*exp(k)", "m", "tension"),
                fr("Tezlik v = kx (t=1)", "k*X0*exp(k)", "m/s", "compress"),
                fr("Cho'zilish λ (t=1)", "exp(k)", "", "mark")],
      note="Lagranj tavsifida zarracha kuzatiladi, Eylerda esa fazoning nuqtasi — bir xil oqim, ikki nigoh."),
  fig("Moddiy hosila: mahalliy va konvektiv qismlar",
      "Doimiy maydonda ham zarracha tezlanishga ega bo'lishi mumkin.",
      params=[fp("v0", "Kirish tezligi", 0.5, 20, 2, 0.1, "m/s"),
              fp("L", "Torayish uzunligi", 0.1, 5, 1, 0.1, "m")],
      curves=[fc("v(x) = v₀(1 + x/L)", "v0*(1 + x/L)", "tension"),
              fc("Konvektiv tezlanish v·dv/dx", "v0^2*(1 + x/L)/L", "compress")],
      x=("x, m", "v, m/s  /  a, m/s²"), x_min="0", x_max="L",
      readouts=[fr("Tezlik chiqishda", "2*v0", "m/s", "tension"),
                fr("Tezlanish chiqishda", "2*v0^2/L", "m/s²", "compress"),
                fr("Mahalliy ∂v/∂t", "0", "m/s²", "rule")],
      note="Statsionar oqimda ∂v/∂t = 0, lekin zarracha tezlanadi — bu konvektiv hadning ishi."),
 ],
 "tmm-04": [
  fig("Deformatsiya gradiyenti: cho'zilish va hajm o'zgarishi",
      "J = det F hajmning nisbiy o'zgarishini beradi.",
      params=[fp("l1", "λ₁ cho'zilish", 0.5, 2.5, 1.2, 0.05, ""),
              fp("l2", "λ₂ cho'zilish", 0.5, 2.5, 0.9, 0.05, "")],
      curves=[fc("J = λ₁λ₂λ₃", "l1*l2*x", "tension"),
              fc("Hajm o'zgarmasligi J=1", "1", "rule", dashed=True)],
      x=("λ₃", "yakobian J"), x_min="0.3", x_max="2.5",
      readouts=[fr("λ₃ (J=1 uchun)", "1/(l1*l2)", "", "mark"),
                fr("J (λ₃=1)", "l1*l2", "", "tension"),
                fr("Hajm o'zgarishi", "100*(l1*l2 - 1)", "%", "compress")],
      note="J > 0 sharti fizik jihatdan majburiy: material o'zini teskari agdara olmaydi."),
  fig("Polar dekompozitsiya: F = RU",
      "Har qanday deformatsiya sof cho'zilish va burilishga ajraladi.",
      params=[fp("lam", "Cho'zilish λ", 0.5, 2.5, 1.5, 0.05, "")],
      curves=[fc("F₁₁ = λcos θ", "lam*cos(x*pi/180)", "tension"),
              fc("F₁₂ = −λsin θ", "-lam*sin(x*pi/180)", "compress"),
              fc("det F = λ² (burilishdan mustaqil)", "lam^2", "rule", dashed=True)],
      x=("burilish burchagi θ, °", "komponenta"), x_min="0", x_max="90",
      readouts=[fr("det F", "lam^2", "", "rule"),
                fr("U ning asosiy qiymati", "lam", "", "tension"),
                fr("Burilish deformatsiya berarmi", "0", "", "compress", text="ha|YO'Q")],
      note="Qattiq burilish deformatsiya EMAS — shuning uchun konstitutiv qonun U ga bog'lanadi, F ga emas."),
 ],
 "tmm-05": [
  fig("Asosiy deformatsiyalar va hajmiy o'zgarish",
      "Iz ε_kk hajm o'zgarishini beradi.",
      params=[fp("e1", "ε₁", -5, 5, 2, 0.1, "‰"),
              fp("e2", "ε₂", -5, 5, -0.6, 0.1, "‰")],
      curves=[fc("θ = ε₁+ε₂+ε₃", "e1 + e2 + x", "tension"),
              fc("Hajm o'zgarmas (θ=0)", "0", "rule", dashed=True)],
      x=("ε₃, ‰", "hajmiy deformatsiya θ, ‰"), x_min="-5", x_max="5",
      readouts=[fr("θ (ε₃=−0,6‰)", "e1 + e2 - 0.6", "‰", "tension"),
                fr("Hajm o'zgarmasligi uchun ε₃", "-(e1 + e2)", "‰", "mark"),
                fr("Deviator ε₁'", "e1 - (e1 + e2 - 0.6)/3", "‰", "compress")],
      note="Deviator qismi shaklni, sharsimon qismi esa hajmni o'zgartiradi — bu ajralish plastiklikda asosiy."),
  fig("Moslik shartlari nima uchun kerak",
      "Ixtiyoriy deformatsiya maydoni uzluksiz ko'chishga mos kelmaydi.",
      params=[fp("A", "εxx koeffitsienti", -5, 5, 1, 0.1, ""),
              fp("B", "εyy koeffitsienti", -5, 5, 1, 0.1, "")],
      curves=[fc("∂²εxx/∂y² qismi", "2*A + 0*x", "tension"),
              fc("∂²εyy/∂x² qismi", "2*B + 0*x", "compress"),
              fc("Moslik uchun ayirma", "2*A - 2*B + 0*x", "mark", dashed=True)],
      x=("shartli o'q", "hosila qiymati"), x_min="0", x_max="1",
      readouts=[fr("Moslik qoldig'i", "2*A - 2*B", "", "mark"),
                fr("Mos keladimi", "abs(2*A - 2*B) - 1e-9", "", "tension", text="ha|YO'Q"),
                fr("Kerakli B", "A", "", "compress")],
      note="6 ta deformatsiya komponentasi 3 ta ko'chishdan chiqadi — shuning uchun 3 ta ortiqcha bog'lanish bor."),
 ],
 "tmm-06": [
  fig("Deformatsiya tezligi va vorteks: sof siljish oqimi",
      "Siljish oqimi teng ulushda deformatsiya va aylanishdan iborat.",
      params=[fp("G", "Siljish tezligi γ̇", 0.1, 20, 2, 0.1, "1/s")],
      curves=[fc("v_x = γ̇y", "G*x", "tension"),
              fc("D₁₂ = γ̇/2", "G/2 + 0*x", "compress", dashed=True),
              fc("W₁₂ = −γ̇/2", "-G/2 + 0*x", "mark", dashed=True)],
      x=("y, m", "tezlik, m/s  /  tenzor komponentasi, 1/s"), x_min="0", x_max="1",
      readouts=[fr("Deformatsiya tezligi D₁₂", "G/2", "1/s", "compress"),
                fr("Vorteks W₁₂", "-G/2", "1/s", "mark"),
                fr("Vortiklik ω", "-G", "1/s", "tension")],
      note="Sof siljish — deformatsiya va aylanishning teng aralashmasi; shuning uchun bu oqim vortikdir."),
  fig("Uzayish tezligi va zichlik o'zgarishi",
      "Divergensiya nolga teng bo'lsa oqim siqilmaydi.",
      params=[fp("a", "Cho'zilish tezligi", -2, 2, 0.5, 0.05, "1/s")],
      curves=[fc("div v = a + b", "a + x", "tension"),
              fc("Siqilmas oqim", "0", "rule", dashed=True)],
      x=("ikkinchi o'q tezligi b, 1/s", "div v, 1/s"), x_min="-2", x_max="2",
      readouts=[fr("b (siqilmas oqim uchun)", "-a", "1/s", "mark"),
                fr("div v (b=0)", "a", "1/s", "tension"),
                fr("Zichlik o'zgarishi (b=0)", "-a", "1/s ulush", "compress")],
      note="dρ/dt = −ρ div v — divergensiya musbat bo'lsa zichlik kamayadi (kengayish)."),
 ],
 "tmm-07": [
  fig("Koshi teoremasi: maydon yo'nalishi va kuchlanish vektori",
      "t = σ·n — bir tenzor barcha maydonlarni beradi.",
      params=[fp("sx", "σxx", -200, 200, 100, 5, "MPa"),
              fp("sy", "σyy", -200, 200, 40, 5, "MPa"),
              fp("txy", "σxy", -150, 150, 30, 5, "MPa")],
      curves=[fc("t_n normal komponenta", "sx*cos(x*pi/180)^2 + sy*sin(x*pi/180)^2 + 2*txy*sin(x*pi/180)*cos(x*pi/180)", "tension"),
              fc("t_t urinma komponenta", "(sy-sx)*sin(x*pi/180)*cos(x*pi/180) + txy*(cos(x*pi/180)^2 - sin(x*pi/180)^2)", "compress"),
              fc("Nol", "0", "rule", dashed=True)],
      x=("normal yo'nalishi θ, °", "kuchlanish, MPa"), x_min="0", x_max="180",
      readouts=[fr("t_n (θ=0)", "sx", "MPa", "tension"),
                fr("t_n (θ=90°)", "sy", "MPa", "compress"),
                fr("|t| (θ=45°)", "sqrt(((sx+sy)/2 + txy)^2 + ((sy-sx)/2)^2)", "MPa", "mark")],
      note="Kuchlanish vektori umuman maydonga perpendikulyar emas — faqat asosiy maydonlarda shunday bo'ladi."),
  fig("Tetraedr muvozanati: uchta maydondan to'rtinchisi",
      "Yuzalar nisbati normal kosinuslariga teng.",
      params=[fp("n1", "n₁", 0, 1, 0.577, 0.01, ""),
              fp("n2", "n₂", 0, 1, 0.577, 0.01, "")],
      curves=[fc("n₁²+n₂²+n₃² = 1", "n1^2 + n2^2 + x^2", "tension"),
              fc("Birlik", "1", "rule", dashed=True)],
      x=("n₃", "normalar kvadrati yig'indisi"), x_min="0", x_max="1",
      readouts=[fr("Kerakli n₃", "sqrt(max(0, 1 - n1^2 - n2^2))", "", "mark"),
                fr("Oktaedr maydoni n", "1/sqrt(3)", "", "tension"),
                fr("Joriy yig'indi (n₃=0,577)", "n1^2 + n2^2 + 1/3", "", "compress")],
      note="n = (1,1,1)/√3 — oktaedr maydoni; Mizes kriteriysi aynan shu maydondagi τ ga asoslanadi."),
 ],
 "tmm-08": [
  fig("Kuchlanish invariantlari va deviator",
      "Sharsimon qism bosim, deviator esa shakl o'zgarishini beradi.",
      params=[fp("s1", "σ₁", -300, 300, 150, 5, "MPa"),
              fp("s2", "σ₂", -300, 300, 50, 5, "MPa")],
      curves=[fc("I₁ = σ₁+σ₂+σ₃", "s1 + s2 + x", "tension"),
              fc("O'rtacha kuchlanish", "(s1 + s2 + x)/3", "compress"),
              fc("Nol", "0", "rule", dashed=True)],
      x=("σ₃, MPa", "kuchlanish, MPa"), x_min="-300", x_max="300",
      readouts=[fr("I₁ (σ₃=0)", "s1 + s2", "MPa", "tension"),
                fr("σ_m (σ₃=0)", "(s1 + s2)/3", "MPa", "compress"),
                fr("Mizes (σ₃=0)", "sqrt(0.5*((s1-s2)^2 + s2^2 + s1^2))", "MPa", "mark")],
      note="Deviatorning izi aynan nol — shuning uchun u hajmni emas, faqat shaklni o'zgartiradi."),
  fig("Oktaedr kuchlanishlari",
      "τ_okt Mizes ekvivalenti bilan qat'iy bog'langan.",
      params=[fp("s1", "σ₁", -300, 300, 200, 5, "MPa"),
              fp("s3", "σ₃", -300, 300, 0, 5, "MPa")],
      curves=[fc("τ_okt", "sqrt(2)/3*sqrt(0.5*((s1-x)^2 + (x-s3)^2 + (s3-s1)^2))", "compress"),
              fc("Mizes σ_e", "sqrt(0.5*((s1-x)^2 + (x-s3)^2 + (s3-s1)^2))", "tension")],
      x=("σ₂, MPa", "kuchlanish, MPa"), x_min="-300", x_max="300",
      readouts=[fr("σ_e (σ₂=0)", "sqrt(0.5*(s1^2 + s3^2 + (s3-s1)^2))", "MPa", "tension"),
                fr("τ_okt (σ₂=0)", "sqrt(2)/3*sqrt(0.5*(s1^2 + s3^2 + (s3-s1)^2))", "MPa", "compress"),
                fr("τ_okt/σ_e", "sqrt(2)/3", "", "mark")],
      note="τ_okt = (√2/3)σ_e ≈ 0,471σ_e — bu nisbat har qanday kuchlanish holatida o'zgarmaydi."),
 ],
 "tmm-09": [
  fig("Uzluksizlik tenglamasi: quvur torayganda tezlik oshadi",
      "ρvA = const — massa oqimi saqlanadi.",
      params=[fp("v1", "Kirish tezligi", 0.1, 20, 2, 0.1, "m/s"),
              fp("d1", "Kirish diametri", 10, 300, 100, 5, "mm")],
      curves=[fc("v₂ = v₁(d₁/d₂)²", "v1*(d1/x)^2", "tension"),
              fc("Kirish tezligi", "v1", "rule", dashed=True)],
      x=("chiqish diametri d₂, mm", "chiqish tezligi v₂, m/s"), x_min="10", x_max="300",
      readouts=[fr("v₂ (d₂=d₁/2)", "4*v1", "m/s", "tension"),
                fr("Massa oqimi (suv)", "1000*v1*pi*(d1*1e-3)^2/4", "kg/s", "compress"),
                fr("Diametr 2× kichraysa", "4", "marta", "mark")],
      note="Tezlik diametr KVADRATIGA teskari — shuning uchun torayish oqimni juda tez tezlashtiradi."),
  fig("Siqiluvchan oqim: zichlik va Max soni",
      "M < 0,3 da zichlik o'zgarishini hisobga olmasa ham bo'ladi.",
      params=[fp("g", "Adiabata ko'rsatkichi γ", 1.1, 1.67, 1.4, 0.01, "")],
      curves=[fc("ρ/ρ₀ = (1+(γ−1)M²/2)^(−1/(γ−1))", "(1 + (g-1)*x^2/2)^(-1/(g-1))", "tension"),
              fc("5% chegara", "0.95", "rule", dashed=True)],
      x=("Max soni M", "zichlik nisbati ρ/ρ₀"), x_min="0", x_max="1",
      readouts=[fr("ρ/ρ₀ (M=0,3)", "(1 + (g-1)*0.09/2)^(-1/(g-1))", "", "tension"),
                fr("O'zgarish (M=0,3)", "100*(1 - (1 + (g-1)*0.09/2)^(-1/(g-1)))", "%", "compress"),
                fr("ρ/ρ₀ (M=1)", "(1 + (g-1)/2)^(-1/(g-1))", "", "mark")],
      note="M = 0,3 da zichlik atigi ~4,4% o'zgaradi — mana shundan 'siqilmas oqim' chegarasi kelib chiqqan."),
 ],
 "tmm-10": [
  fig("Koshi harakat tenglamasi: bosim gradiyenti va tezlanish",
      "Bosim pasayishi zarrachani tezlashtiradi.",
      params=[fp("rho", "Zichlik", 1, 2000, 1000, 10, "kg/m³"),
              fp("dp", "Bosim gradiyenti", -50000, 50000, -10000, 500, "Pa/m")],
      curves=[fc("a = −(1/ρ)dp/dx + g", "-dp/rho + 9.81*x", "tension"),
              fc("Faqat bosimdan", "-dp/rho", "rule", dashed=True)],
      x=("og'irlik proyeksiyasi koeffitsienti", "tezlanish a, m/s²"), x_min="-1", x_max="1",
      readouts=[fr("Bosimdan tezlanish", "-dp/rho", "m/s²", "tension"),
                fr("Og'irlik (tik)", "9.81", "m/s²", "compress"),
                fr("Qaysi hukmron", "abs(dp/rho) - 9.81", "", "mark", text="og'irlik|BOSIM")],
      note="Suvda 10 kPa/m bosim gradiyenti og'irlik bilan bir xil tartibdagi tezlanish beradi."),
  fig("Statik holat: bosim chuqurlik bo'yicha",
      "Muvozanatda harakat tenglamasi gidrostatikaga aylanadi.",
      params=[fp("rho", "Zichlik", 500, 14000, 1000, 50, "kg/m³"),
              fp("p0", "Sirt bosimi", 0, 500, 101, 1, "kPa")],
      curves=[fc("p(h) = p₀ + ρgh", "p0 + rho*9.81*x/1000", "tension"),
              fc("Sirt bosimi", "p0", "rule", dashed=True)],
      x=("chuqurlik h, m", "bosim p, kPa"), x_min="0", x_max="100",
      readouts=[fr("p (h=10 m)", "p0 + rho*98.1/1000", "kPa", "tension"),
                fr("Qo'shimcha 1 atm uchun h", "101325/(rho*9.81)", "m", "compress"),
                fr("p (h=100 m)", "p0 + rho*981/1000", "kPa", "mark")],
      note="Suvda har 10,33 m chuqurlik bir atmosfera qo'shadi — g'avvoslik hisoblarining asosi."),
 ],
 "tmm-11": [
  fig("Kuchlanish tenzorining simmetriyasi",
      "σxy ≠ σyx bo'lsa element cheksiz tezlanish oladi.",
      params=[fp("s12", "σ₁₂", -100, 100, 50, 5, "MPa"),
              fp("a", "Element o'lchami", 0.1, 10, 1, 0.1, "mm"),
              fp("rho", "Zichlik", 1000, 12000, 7850, 50, "kg/m³")],
      curves=[fc("Burchak tezlanish ∝ (σ₁₂−σ₂₁)/(ρa²)", "(s12 - x)*1e6/(rho*(a*1e-3)^2)", "tension"),
              fc("Muvozanat (nol)", "0", "rule", dashed=True)],
      x=("σ₂₁, MPa", "burchak tezlanish, 1/s²"), x_min="-100", x_max="100",
      readouts=[fr("σ₂₁ = σ₁₂ da", "0", "1/s²", "rule"),
                fr("1 MPa farqda", "1e6/(rho*(a*1e-3)^2)", "1/s²", "tension"),
                fr("Xulosa", "1", "", "mark", text="simmetriya majburiy|—")],
      note="Element kichrayganda inersiya a⁵, moment esa a³ bo'lib kamayadi — shuning uchun simmetriya qat'iy."),
  fig("Kuchlanish tenzorining mustaqil komponentalari",
      "Simmetriya 9 ta komponentani 6 taga tushiradi.",
      params=[fp("n", "Fazo o'lchami", 2, 3, 3, 1, "")],
      curves=[fc("Simmetrik: n(n+1)/2", "x*(x+1)/2", "tension"),
              fc("Umumiy: n²", "x^2", "compress"),
              fc("Joriy o'lchamdagi simmetrik son", "n*(n + 1)/2", "mark", dashed=True)],
      x=("o'lcham n", "komponentalar soni"), x_min="1", x_max="4",
      readouts=[fr("3D simmetrik", "6", "ta", "tension"),
                fr("3D umumiy", "9", "ta", "compress"),
                fr("2D simmetrik", "3", "ta", "mark")],
      note="6 ta mustaqil komponenta — shuning uchun Mor doirasi va asosiy kuchlanishlar tushunchasi ishlaydi."),
 ],
 "tmm-12": [
  fig("Dissipatsiya: mexanik ishning issiqlikka aylanishi",
      "Yopishqoqlik ishni qaytarilmas ravishda issiqlikka o'tkazadi.",
      params=[fp("mu", "Yopishqoqlik μ", 0.0001, 1, 0.001, 0.0001, "Pa·s"),
              fp("h", "Qatlam qalinligi", 0.1, 20, 1, 0.1, "mm")],
      curves=[fc("Φ = μ(v/h)², W/m³", "mu*(x/(h*1e-3))^2", "tension"),
              fc("1 kW/m³ daraja", "1000", "rule", dashed=True)],
      x=("sirpanish tezligi v, m/s", "dissipatsiya, W/m³"), x_min="0", x_max="10",
      readouts=[fr("Φ (v=1 m/s)", "mu*(1/(h*1e-3))^2", "W/m³", "tension"),
                fr("Φ (v=5 m/s)", "mu*(5/(h*1e-3))^2", "W/m³", "compress"),
                fr("Tezlik 2× bo'lsa", "4", "marta", "mark")],
      note="Dissipatsiya har doim musbat — bu termodinamikaning ikkinchi qonunining mexanikadagi ifodasi."),
  fig("Energiya balansi: issiqlik va mexanik hadlar",
      "Issiqlik o'tkazuvchanlik qalinlikka teskari proporsional.",
      params=[fp("k", "Issiqlik o'tkazuvchanlik", 0.1, 400, 50, 1, "W/(m·K)"),
              fp("dT", "Temperatura farqi", 1, 500, 100, 5, "K")],
      curves=[fc("q = kΔT/L, kW/m²", "k*dT/x/1000", "tension"),
              fc("10 kW/m² daraja", "10", "rule", dashed=True)],
      x=("qalinlik L, m", "issiqlik oqimi q, kW/m²"), x_min="0.001", x_max="0.2",
      readouts=[fr("q (L=10 mm)", "k*dT/0.01/1000", "kW/m²", "tension"),
                fr("q (L=100 mm)", "k*dT/0.1/1000", "kW/m²", "compress"),
                fr("Termik qarshilik (L=10 mm)", "0.01/k", "m²·K/W", "mark")],
      note="Po'latda (k=50) 10 mm qatlam 100 K farqda 500 kW/m² o'tkazadi — juda katta oqim."),
 ],
 "tmm-13": [
  fig("Material simmetriyasi va mustaqil konstantalar soni",
      "Simmetriya oshgani sari kerakli tajribalar soni kamayadi.",
      params=[fp("cls", "Simmetriya sinfi", 1, 5, 5, 1, "")],
      curves=[fc("Konstantalar soni", "21 - 8*(x-1) + 0.5*(x-1)*(x-2)", "tension"),
              fc("Izotrop (2 ta)", "2", "rule", dashed=True),
              fc("Joriy sinf", "21 - 8*(cls - 1) + 0.5*(cls - 1)*(cls - 2)", "mark", dashed=True)],
      x=("simmetriya darajasi", "mustaqil konstantalar"), x_min="1", x_max="5",
      readouts=[fr("Anizotrop", "21", "ta", "tension"),
                fr("Ortotrop", "9", "ta", "compress"),
                fr("Izotrop", "2", "ta", "mark")],
      note="Anizotrop material 21 ta konstanta talab qiladi — kompozitlarni tavsiflash shuning uchun qiyin."),
  fig("Obyektivlik prinsipi: burilishdan mustaqillik",
      "Konstitutiv qonun kuzatuvchi burilishiga bog'liq bo'lmasligi shart.",
      params=[fp("lam", "Cho'zilish λ", 0.5, 2, 1.3, 0.05, ""),
              fp("E", "Modul", 1, 500, 200, 5, "GPa")],
      curves=[fc("Koshi–Grin C₁₁ (burilishdan mustaqil)", "lam^2 + 0*x", "rule", dashed=True),
              fc("F₁₁ (burilishga bog'liq)", "lam*cos(x*pi/180)", "tension")],
      x=("kuzatuvchi burilishi θ, °", "qiymat"), x_min="0", x_max="90",
      readouts=[fr("C₁₁ = λ²", "lam^2", "", "rule"),
                fr("Grin deformatsiyasi E₁₁", "(lam^2 - 1)/2", "", "compress"),
                fr("Kuchlanish (kichik deform.)", "E*(lam - 1)*1000", "MPa", "mark")],
      note="F burilishga bog'liq, C = FᵀF esa yo'q — shuning uchun qonunlar C orqali yoziladi."),
 ],
 "tmm-14": [
  fig("Lame konstantalari va muhandislik doimiylari",
      "λ va μ ni E va ν bilan bog'lash.",
      params=[fp("E", "Modul E", 10, 400, 210, 5, "GPa")],
      curves=[fc("λ = Eν/((1+ν)(1−2ν))", "E*x/((1+x)*(1-2*x))", "tension"),
              fc("μ = G = E/(2(1+ν))", "E/(2*(1+x))", "compress")],
      x=("Puasson koeffitsienti ν", "konstanta, GPa"), x_min="0", x_max="0.45",
      readouts=[fr("λ (ν=0,3)", "E*0.3/(1.3*0.4)", "GPa", "tension"),
                fr("μ (ν=0,3)", "E/2.6", "GPa", "compress"),
                fr("λ/μ (ν=0,3)", "0.3*2.6/(1.3*0.4)", "", "mark")],
      note="ν → 0,5 da λ cheksizga intiladi — sonli usullarda bu 'hajmiy qulflanish' muammosini keltiradi."),
  fig("Tekis deformatsiyada uchinchi kuchlanish",
      "σz = ν(σx+σy) — u nolga teng emas.",
      params=[fp("sx", "σx", -200, 200, 100, 5, "MPa"),
              fp("sy", "σy", -200, 200, 50, 5, "MPa")],
      curves=[fc("σz = ν(σx+σy)", "x*(sx + sy)", "tension"),
              fc("Tekis kuchlanish (σz=0)", "0", "rule", dashed=True)],
      x=("ν", "σz, MPa"), x_min="0", x_max="0.5",
      readouts=[fr("σz (ν=0,3)", "0.3*(sx + sy)", "MPa", "tension"),
                fr("Mizes tekis kuchlanishda", "sqrt(sx^2 - sx*sy + sy^2)", "MPa", "compress"),
                fr("Mizes tekis deformatsiyada", "sqrt(0.5*((sx-sy)^2 + (sy-0.3*(sx+sy))^2 + (0.3*(sx+sy)-sx)^2))", "MPa", "mark")],
      note="Tekis deformatsiyada Mizes ekvivalenti kichikroq chiqadi — qalin detallar shuning uchun 'mustahkamroq' ko'rinadi."),
 ],
 "tmm-15": [
  fig("Navye tenglamasi: to'lqin tezliklari",
      "P-to'lqin S-to'lqindan har doim tezroq.",
      params=[fp("E", "Modul", 10, 400, 210, 5, "GPa"),
              fp("rho", "Zichlik", 1000, 12000, 7850, 50, "kg/m³")],
      curves=[fc("c_P, m/s", "sqrt(E*1e9*(1-x)/(rho*(1+x)*(1-2*x)))", "tension"),
              fc("c_S, m/s", "sqrt(E*1e9/(2*rho*(1+x)))", "compress")],
      x=("ν", "to'lqin tezligi, m/s"), x_min="0", x_max="0.45",
      readouts=[fr("c_P (ν=0,3)", "sqrt(E*1e9*0.7/(rho*1.3*0.4))", "m/s", "tension"),
                fr("c_S (ν=0,3)", "sqrt(E*1e9/(2*rho*1.3))", "m/s", "compress"),
                fr("c_P/c_S", "sqrt(2*0.7/(0.4))/1", "", "mark")],
      note="Po'latda c_P ≈ 5900 m/s, c_S ≈ 3200 m/s — seysmologiya va ultratovush nazoratining asosi."),
  fig("Chegaraviy shartlar turlari",
      "Ko'chish va kuchlanish shartlari bir-birini to'ldiradi.",
      params=[fp("F", "Yuk", 1, 200, 50, 1, "kN"),
              fp("k", "Elastik tayanch bikrligi", 0.1, 100, 10, 0.1, "MN/m")],
      curves=[fc("Ko'chish δ = F/(k+x), mm", "F/(k*1000 + x*1000)*1000", "tension"),
              fc("Bikr tayanch (δ→0)", "0", "rule", dashed=True)],
      x=("konstruksiya bikrligi, MN/m", "ko'chish, mm"), x_min="0.1", x_max="100",
      readouts=[fr("δ (konstruksiya 50 MN/m)", "F/(k*1000 + 50000)*1000", "mm", "tension"),
                fr("Erkin tayanch (k=0)", "F/50000*1000", "mm", "compress"),
                fr("Tayanch ulushi", "100*k/(k + 50)", "%", "mark")],
      note="Real tayanch na mutlaqo bikr, na erkin — elastik shart orqali modellashtiriladi."),
 ],
 "tmm-16": [
  fig("Tekis kuchlanish va tekis deformatsiya: qachon qaysi biri",
      "Qalinlik nisbati modelni tanlaydi.",
      params=[fp("sx", "σx", -200, 200, 120, 5, "MPa"),
              fp("E", "Modul", 10, 400, 210, 5, "GPa")],
      curves=[fc("εz tekis kuchlanishda, ‰", "-0.3*sx/(E*1000)*1000 + 0*x", "tension"),
              fc("εz tekis deformatsiyada", "0", "rule", dashed=True)],
      x=("qalinlik/kenglik nisbati", "εz, ‰"), x_min="0.01", x_max="2",
      readouts=[fr("εz (yupqa plastina)", "-0.3*sx/(E*1000)*1000", "‰", "tension"),
                fr("εz (qalin jism)", "0", "‰", "rule"),
                fr("σz (qalin jism)", "0.3*sx", "MPa", "compress")],
      note="Yupqa plastina — tekis kuchlanish (σz=0); uzun qalin jism — tekis deformatsiya (εz=0)."),
  fig("Qalin devorli quvur: Lame yechimi",
      "Ichki bosim radius bo'ylab kuchlanish beradi.",
      params=[fp("p", "Ichki bosim", 1, 100, 20, 1, "MPa"),
              fp("a", "Ichki radius", 10, 100, 50, 1, "mm"),
              fp("b", "Tashqi radius", 20, 250, 100, 1, "mm")],
      curves=[fc("σθ (halqasimon)", "p*a^2/(b^2-a^2)*(1 + b^2/x^2)", "tension"),
              fc("σr (radial)", "p*a^2/(b^2-a^2)*(1 - b^2/x^2)", "compress"),
              fc("Nol", "0", "rule", dashed=True)],
      x=("radius r, mm", "kuchlanish, MPa"), x_min="a", x_max="b",
      readouts=[fr("σθ ichkarida", "p*a^2/(b^2-a^2)*(1 + b^2/a^2)", "MPa", "tension"),
                fr("σθ tashqarida", "2*p*a^2/(b^2-a^2)", "MPa", "compress"),
                fr("σr ichkarida", "-p", "MPa", "mark")],
      note="Maksimal halqasimon kuchlanish ICHKI sirtda bo'ladi — shuning uchun darzlar ichkaridan boshlanadi."),
 ],
 "tmm-17": [
  fig("Eyri funksiyasi: bigarmonik shart",
      "Ixtiyoriy funksiya emas, faqat ∇⁴φ = 0 yechim beradi.",
      params=[fp("A", "x⁴ koeffitsienti", -5, 5, 1, 0.1, ""),
              fp("B", "x²y² koeffitsienti", -5, 5, -3, 0.1, "")],
      curves=[fc("∇⁴φ = 24A + 8B + 24C", "24*A + 8*B + 24*x", "tension"),
              fc("Bigarmonik shart", "0", "rule", dashed=True)],
      x=("y⁴ koeffitsienti C", "∇⁴φ"), x_min="-5", x_max="5",
      readouts=[fr("Kerakli C", "-(24*A + 8*B)/24", "", "mark"),
                fr("Joriy qoldiq (C=1)", "24*A + 8*B + 24", "", "tension"),
                fr("Shart bajarilganmi (C=1)", "abs(24*A + 8*B + 24) - 1e-9", "", "compress", text="ha|YO'Q")],
      note="Bigarmonik shart moslik tenglamasidan kelib chiqadi — u yechimni fizik jihatdan mumkin qiladi."),
  fig("Konsol balka: Eyri yechimi va elementar nazariya",
      "Aniq yechim Juravskiy formulasi bilan mos tushadi.",
      params=[fp("F", "Kuch", 1, 100, 10, 1, "kN"),
              fp("h", "Balandlik", 5, 60, 20, 1, "sm"),
              fp("b", "Kenglik", 2, 30, 10, 1, "sm")],
      curves=[fc("τ(y) Eyri yechimi", "1.5*F*1000/(b*h*1e-4)*(1 - 4*x^2/h^2)/1e6", "compress"),
              fc("O'rtacha", "F*1000/(b*h*1e-4)/1e6", "rule", dashed=True)],
      x=("y, sm", "τ, MPa"), x_min="-h/2", x_max="h/2",
      readouts=[fr("τ_max", "1.5*F*1000/(b*h*1e-4)/1e6", "MPa", "compress"),
                fr("σ_max (L=1 m)", "6*F*1000/(b*1e-2*(h*1e-2)^2)/1e6", "MPa", "tension"),
                fr("σ/τ (L=1 m)", "4*100/h", "", "mark")],
      note="Eyri yechimi elementar nazariyani tasdiqlaydi — bu klassik natijalarning qat'iy asosi."),
 ],
 "tmm-18": [
  fig("Sen-Venan buralishi: kesim shaklining ta'siri",
      "Doiradan tashqari kesimlarda deplanatsiya paydo bo'ladi.",
      params=[fp("T", "Moment", 10, 2000, 500, 10, "N·m"),
              fp("a", "Kvadrat tomoni", 10, 100, 40, 1, "mm")],
      curves=[fc("τ_max kvadrat: T/(0,208a³)", "T/(0.208*(x*1e-3)^3)/1e6", "tension"),
              fc("Teng yuzali doira", "16*T/(pi*(2*x*1e-3/sqrt(pi))^3)/1e6", "compress"),
              fc("Joriy tomon: kvadrat", "T/(0.208*(a*1e-3)^3)/1e6", "mark", dashed=True)],
      x=("kvadrat tomoni a, mm", "τ_max, MPa"), x_min="10", x_max="100",
      readouts=[fr("Kvadrat (a=40)", "T/(0.208*(40e-3)^3)/1e6", "MPa", "tension"),
                fr("Teng yuzali doira", "16*T/(pi*(80e-3/sqrt(pi))^3)/1e6", "MPa", "compress"),
                fr("Doira afzalligi", "100*(1 - (16/(pi*(2/sqrt(pi))^3))/(1/0.208))", "%", "mark")],
      note="Buralishda doira eng samarali shakl — faqat unda kesim tekis qoladi (deplanatsiya yo'q)."),
  fig("Yupqa devorli kesim: yopiq va ochiq profil",
      "Kesimni kesish buralish bikrligini yuzlab barobar kamaytiradi.",
      params=[fp("R", "O'rtacha radius", 10, 150, 50, 1, "mm"),
              fp("t", "Devor qalinligi", 0.5, 10, 2, 0.1, "mm")],
      curves=[fc("Yopiq: I_t = 2πR³t", "2*pi*(R*1e-3)^3*x*1e-3*1e12", "tension"),
              fc("Ochiq: I_t = 2πRt³/3", "2*pi*R*1e-3*(x*1e-3)^3/3*1e12", "compress"),
              fc("Joriy qalinlik: yopiq", "2*pi*(R*1e-3)^3*t*1e-3*1e12", "mark", dashed=True)],
      x=("qalinlik t, mm", "I_t, mm⁴"), x_min="0.5", x_max="10",
      readouts=[fr("Yopiq (t=2 mm)", "2*pi*(R*1e-3)^3*2e-3*1e12", "mm⁴", "tension"),
                fr("Ochiq (t=2 mm)", "2*pi*R*1e-3*(2e-3)^3/3*1e12", "mm⁴", "compress"),
                fr("Nisbat", "3*(R/2)^2", "marta", "mark")],
      note="R/t = 25 da yopiq profil ochiqdan 1875 marta bikr — avtomobil kuzovi shuning uchun yopiq."),
 ],
 "tmm-19": [
  fig("Minimal potensial energiya prinsipi",
      "Haqiqiy yechim energiyani minimallashtiradi.",
      params=[fp("EI", "Bikrlik", 100, 20000, 3000, 100, "kN·m²"),
              fp("q", "Yuk", 1, 60, 10, 1, "kN/m"),
              fp("L", "Oraliq", 1, 10, 4, 0.5, "m")],
      curves=[fc("П(a) = U − W, J", "(EI*pi^4/(4*L^3)*x^2 - 2*q*L/pi*x)*1000", "tension"),
              fc("Minimum darajasi", "-(q*L/pi)^2/(EI*pi^4/(4*L^3))*1000", "rule", dashed=True)],
      x=("amplituda a, m", "potensial energiya П, J"), x_min="0", x_max="0.05",
      readouts=[fr("Optimal amplituda", "4*q*L^4/(EI*pi^5)", "m", "mark"),
                fr("Aniq yechim 5qL⁴/(384EI)", "5*q*L^4/(384*EI)", "m", "compress"),
                fr("Xato", "100*abs(4/pi^5 - 5/384)/(5/384)", "%", "tension")],
      note="Bitta sinus funksiyasi bilan olingan Ritz yechimi aniq javobdan atigi ~0,4% farq qiladi."),
  fig("Mumkin bo'lgan ko'chishlar prinsipi",
      "Virtual ish nolga teng bo'lsa tizim muvozanatda.",
      params=[fp("F", "Kuch", 1, 100, 30, 1, "kN"),
              fp("L", "Richag uzunligi", 0.2, 5, 1, 0.1, "m")],
      curves=[fc("Virtual ish δA = Fδ − Rx·δ/L", "F - x/L", "tension"),
              fc("Muvozanat", "0", "rule", dashed=True)],
      x=("reaksiya momenti R, kN·m", "virtual ish koeffitsienti, kN"), x_min="0", x_max="100",
      readouts=[fr("Muvozanat R", "F*L", "kN·m", "mark"),
                fr("Joriy qoldiq (R=30)", "F - 30/L", "kN", "tension"),
                fr("Muvozanatdami (R=30)", "abs(F - 30/L) - 1e-9", "", "compress", text="ha|YO'Q")],
      note="Virtual ish usuli reaksiyalarni aniqlashda ko'pincha muvozanat tenglamalaridan qisqaroq yo'l beradi."),
 ],
 "tmm-20": [
  fig("P- va S-to'lqinlarning kelish vaqti farqi",
      "Seysmologiyada markazgacha masofa shu farqdan topiladi.",
      params=[fp("cp", "P-to'lqin tezligi", 3000, 9000, 6000, 100, "m/s"),
              fp("cs", "S-to'lqin tezligi", 1500, 5000, 3500, 100, "m/s")],
      curves=[fc("Δt = d(1/c_S − 1/c_P), s", "x*1000*(1/cs - 1/cp)", "tension"),
              fc("10 s daraja", "10", "rule", dashed=True)],
      x=("masofa d, km", "vaqt farqi Δt, s"), x_min="0", x_max="500",
      readouts=[fr("Δt (d=100 km)", "100000*(1/cs - 1/cp)", "s", "tension"),
                fr("Δt=10 s ga mos d", "10/(1/cs - 1/cp)/1000", "km", "mark"),
                fr("c_P/c_S", "cp/cs", "", "compress")],
      note="Uchta stansiyadagi Δt qiymati zilzila o'chog'ini uch o'lchamda aniqlashga yetadi."),
  fig("Reley yuza to'lqini",
      "Yuza to'lqini S-to'lqindan biroz sekinroq tarqaladi.",
      params=[fp("cs", "S-to'lqin tezligi", 1500, 5000, 3200, 50, "m/s")],
      curves=[fc("c_R ≈ c_S(0,87+1,12ν)/(1+ν)", "cs*(0.87 + 1.12*x)/(1 + x)", "tension"),
              fc("c_S darajasi", "cs", "rule", dashed=True)],
      x=("ν", "c_R, m/s"), x_min="0", x_max="0.5",
      readouts=[fr("c_R (ν=0,25)", "cs*(0.87 + 0.28)/1.25", "m/s", "tension"),
                fr("c_R/c_S (ν=0,25)", "(0.87 + 0.28)/1.25", "", "mark"),
                fr("Chuqurlikda so'nish (1λ)", "4.3", "%", "compress")],
      note="Reley to'lqini bir to'lqin uzunligi chuqurlikda amplitudasining ~96% ini yo'qotadi — u yuza hodisasi."),
 ],
 "tmm-21": [
  fig("Mizes va Treska kriteriylari tekis kuchlanishda",
      "Ikki kriteriy farqi eng ko'pi bilan 15,5% ni tashkil qiladi.",
      params=[fp("sy", "Oqish chegarasi σᵧ", 100, 800, 250, 10, "MPa")],
      curves=[fc("Mizes: σ₂ chegarasi", "sy*(x/(2*sy) + sqrt(1 - 3*x^2/(4*sy^2)))", "tension"),
              fc("Treska (σ₁,σ₂ bir ishorali)", "sy", "compress", dashed=True),
              fc("Oqish chegarasi", "sy", "rule", dashed=True)],
      x=("σ₁, MPa", "ruxsat etilgan σ₂, MPa"), x_min="0", x_max="sy",
      readouts=[fr("Mizes (σ₁=σᵧ)", "sy*(0.5 + sqrt(1 - 0.75))", "MPa", "tension"),
                fr("Sof siljishda Mizes", "sy/sqrt(3)", "MPa", "compress"),
                fr("Sof siljishda Treska", "sy/2", "MPa", "mark")],
      note="Eng katta farq sof siljishda: Mizes 0,577σᵧ, Treska esa 0,5σᵧ beradi."),
  fig("Oqish sirtining kuchlanish fazosidagi geometriyasi",
      "Gidrostatik o'q bo'ylab oqish yuzaga kelmaydi.",
      params=[fp("sy", "σᵧ", 100, 800, 300, 10, "MPa"),
              fp("p", "Gidrostatik bosim", -500, 500, 0, 10, "MPa")],
      curves=[fc("Mizes ekvivalenti (bosimdan mustaqil)", "abs(x)", "tension"),
              fc("σᵧ", "sy", "rule", dashed=True)],
      x=("deviator kattaligi, MPa", "σ_ekv, MPa"), x_min="-500", x_max="500",
      readouts=[fr("σ_ekv bosimdan o'zgaradimi", "0", "", "compress", text="yo'q|ha"),
                fr("Silindr radiusi", "sy*sqrt(2/3)", "MPa", "tension"),
                fr("Joriy bosim", "p", "MPa", "mark")],
      note="Mizes sirti gidrostatik o'q atrofidagi silindr — metallar bosimda oqmaydi, bu tajribada tasdiqlangan."),
 ],
 "tmm-22": [
  fig("Izotrop mustahkamlanish: oqish chegarasining o'sishi",
      "Plastik deformatsiya materialni mustahkamlaydi.",
      params=[fp("sy", "Boshlang'ich σᵧ", 100, 600, 250, 10, "MPa"),
              fp("H", "Mustahkamlanish moduli", 100, 5000, 1000, 50, "MPa")],
      curves=[fc("σ = σᵧ + Hε_p", "sy + H*x/100", "tension"),
              fc("Ideal plastik (H=0)", "sy", "rule", dashed=True)],
      x=("plastik deformatsiya ε_p, %", "oqish kuchlanishi, MPa"), x_min="0", x_max="5",
      readouts=[fr("σ (ε_p=1%)", "sy + H/100", "MPa", "tension"),
                fr("σ (ε_p=5%)", "sy + H*5/100", "MPa", "compress"),
                fr("Mustahkamlanish", "100*H*5/100/sy", "%", "mark")],
      note="H = 0 ideal plastiklik; real po'latda H ≈ E/100 tartibida bo'ladi."),
  fig("Bauschinger effekti: kinematik mustahkamlanish",
      "Cho'zilishdan keyin siqilishda oqish ertaroq boshlanadi.",
      params=[fp("sy", "Boshlang'ich σᵧ", 100, 600, 250, 10, "MPa"),
              fp("H", "Kinematik modul", 100, 5000, 1000, 50, "MPa")],
      curves=[fc("Cho'zilishda oqish", "sy + H*x/100", "tension"),
              fc("Siqilishda oqish (kinematik)", "-(sy - H*x/100)", "compress"),
              fc("Siqilishda (izotrop)", "-(sy + H*x/100)", "mark", dashed=True)],
      x=("oldingi plastik deformatsiya, %", "oqish kuchlanishi, MPa"), x_min="0", x_max="5",
      readouts=[fr("Cho'zilishda (ε_p=2%)", "sy + H*2/100", "MPa", "tension"),
                fr("Siqilishda (kinematik)", "-(sy - H*2/100)", "MPa", "compress"),
                fr("Elastik oraliq", "2*sy", "MPa", "rule")],
      note="Kinematik modelda elastik oraliq 2σᵧ bo'lib qoladi, faqat markazi siljiydi — siklik yuklashda shu muhim."),
 ],
 "tmm-23": [
  fig("Maksvell modeli: kuchlanish relaksatsiyasi",
      "Doimiy deformatsiyada kuchlanish eksponensial so'nadi.",
      params=[fp("s0", "Boshlang'ich kuchlanish", 1, 200, 50, 1, "MPa"),
              fp("tau", "Relaksatsiya vaqti", 0.5, 500, 20, 0.5, "s")],
      curves=[fc("σ(t) = σ₀e^{−t/τ}", "s0*exp(-x/tau)", "tension"),
              fc("37% darajasi", "s0*exp(-1)", "rule", dashed=True)],
      x=("vaqt t, s", "σ, MPa"), x_min="0", x_max="100",
      readouts=[fr("σ (t=τ)", "s0*exp(-1)", "MPa", "tension"),
                fr("σ (t=3τ)", "s0*exp(-3)", "MPa", "compress"),
                fr("Yarim so'nish vaqti", "tau*log(2)", "s", "mark")],
      note="t = τ da kuchlanish 37% ga tushadi; 3τ dan keyin atigi 5% qoladi."),
  fig("Kelvin–Foygt modeli: sudralish (kreep)",
      "Doimiy kuchlanishda deformatsiya asta-sekin o'sadi.",
      params=[fp("s0", "Kuchlanish", 1, 200, 30, 1, "MPa"),
              fp("E", "Moduli", 0.1, 50, 3, 0.1, "GPa"),
              fp("tau", "Kechikish vaqti", 1, 1000, 50, 1, "s")],
      curves=[fc("ε(t) = (σ/E)(1 − e^{−t/τ}), ‰", "s0/(E*1000)*(1 - exp(-x/tau))*1000", "tension"),
              fc("Chegaraviy deformatsiya", "s0/(E*1000)*1000", "rule", dashed=True)],
      x=("vaqt t, s", "ε, ‰"), x_min="0", x_max="300",
      readouts=[fr("ε (t=τ)", "s0/(E*1000)*(1 - exp(-1))*1000", "‰", "tension"),
                fr("Chegaraviy ε", "s0/(E*1000)*1000", "‰", "rule"),
                fr("90% ga yetish vaqti", "tau*log(10)", "s", "mark")],
      note="Kelvin–Foygt modeli relaksatsiyani ko'rsatmaydi; Maksvell esa chegaraviy deformatsiya bermaydi — shuning uchun ular birlashtiriladi."),
 ],
 "tmm-24": [
  fig("Kuchlanish intensivligi koeffitsienti va yoriq uzunligi",
      "K oshib K_Ic ga yetganda yoriq beqaror tarqaladi.",
      params=[fp("s", "Nominal kuchlanish", 10, 500, 100, 5, "MPa"),
              fp("Kic", "Chidamlilik K_Ic", 10, 200, 50, 1, "MPa·√m")],
      curves=[fc("K = σ√(πa)", "s*sqrt(pi*x*1e-3)", "tension"),
              fc("K_Ic", "Kic", "rule", dashed=True)],
      x=("yoriq uzunligi a, mm", "K_I, MPa·√m"), x_min="0.1", x_max="100",
      readouts=[fr("Kritik uzunlik a_kr", "Kic^2/(pi*s^2)*1000", "mm", "mark"),
                fr("K (a=10 mm)", "s*sqrt(pi*0.01)", "MPa·√m", "tension"),
                fr("Zaxira (a=10 mm)", "Kic/(s*sqrt(pi*0.01))", "marta", "compress")],
      note="Kritik uzunlik kuchlanish KVADRATIGA teskari — yukni 2 barobar kamaytirish ruxsat etilgan yoriqni 4 barobar oshiradi."),
  fig("Griffits energetik mezoni",
      "Yoriq o'sishi energiya bo'shatsa, jarayon o'z-o'zidan davom etadi.",
      params=[fp("E", "Modul", 10, 400, 210, 5, "GPa"),
              fp("g", "Sirt energiyasi", 1, 1000, 100, 1, "J/m²")],
      curves=[fc("Kritik kuchlanish σ_kr", "sqrt(2*E*1e9*g/(pi*x*1e-3))/1e6", "tension"),
              fc("Oqish chegarasi 250 MPa", "250", "rule", dashed=True)],
      x=("yoriq uzunligi a, mm", "σ_kr, MPa"), x_min="0.01", x_max="20",
      readouts=[fr("σ_kr (a=1 mm)", "sqrt(2*E*1e9*g/(pi*1e-3))/1e6", "MPa", "tension"),
                fr("σ_kr (a=10 mm)", "sqrt(2*E*1e9*g/(pi*1e-2))/1e6", "MPa", "compress"),
                fr("G_c (energiya tezligi)", "2*g", "J/m²", "mark")],
      note="Shishaning nazariy mustahkamligi ~10 GPa, amaliy esa ~50 MPa — farq mikroyoriqlar hisobiga."),
 ],
 "tmm-25": [
  fig("Gidrostatik bosim va suzish",
      "Arximed kuchi siqilgan hajmga proporsional.",
      params=[fp("rho", "Suyuqlik zichligi", 600, 13600, 1000, 50, "kg/m³"),
              fp("V", "Jism hajmi", 0.001, 10, 1, 0.001, "m³")],
      curves=[fc("Arximed kuchi, kN", "rho*9.81*V*x/1000", "tension"),
              fc("Jism og'irligi (ρ=700)", "700*9.81*V/1000", "rule", dashed=True)],
      x=("botgan hajm ulushi", "kuch, kN"), x_min="0", x_max="1",
      readouts=[fr("To'liq botganda", "rho*9.81*V/1000", "kN", "tension"),
                fr("Muvozanat ulushi (ρ_j=700)", "700/rho", "", "mark"),
                fr("Suzadimi", "700/rho - 1", "", "compress", text="ha|YO'Q")],
      note="Suzish ulushi zichliklar nisbatiga teng: muzning 90% i suv ostida qoladi."),
  fig("Suzish barqarorligi: metasentrik balandlik",
      "GM musbat bo'lsa kema o'zini tiklaydi.",
      params=[fp("d", "Cho'kish chuqurligi", 0.5, 15, 3, 0.1, "m"),
             fp("B", "Kema kengligi", 2, 40, 10, 0.5, "m"),
             fp("KG", "Og'irlik markazi balandligi", 0.5, 20, 4, 0.1, "m")],
      curves=[fc("GM = B²/(12d) + d/2 − KG", "x^2/(12*d) + d/2 - KG", "tension"),
              fc("Barqarorlik chegarasi", "0", "rule", dashed=True)],
      x=("kenglik B, m", "metasentrik balandlik GM, m"), x_min="2", x_max="40",
      readouts=[fr("GM (joriy)", "B^2/(12*d) + d/2 - KG", "m", "tension"),
                fr("Barqarormi", "B^2/(12*d) + d/2 - KG", "", "mark", text="YO'Q|ha"),
                fr("Kerakli minimal B", "sqrt(12*d*(KG - d/2))", "m", "compress")],
      note="Kenglik kvadrat bo'lib kiradi — shuning uchun keng kemalar (katamaran) ancha barqaror."),
 ],
 "tmm-26": [
  fig("Bernulli tenglamasi: tezlik va bosim almashinuvi",
      "Tezlik oshsa bosim tushadi.",
      params=[fp("p0", "To'liq bosim", 100, 1000, 300, 5, "kPa"),
              fp("rho", "Zichlik", 1, 2000, 1000, 10, "kg/m³")],
      curves=[fc("p = p₀ − ρv²/2, kPa", "p0 - rho*x^2/2/1000", "tension"),
              fc("Nol bosim (kavitatsiya)", "0", "rule", dashed=True)],
      x=("tezlik v, m/s", "statik bosim p, kPa"), x_min="0", x_max="30",
      readouts=[fr("p (v=10 m/s)", "p0 - rho*50/1000", "kPa", "tension"),
                fr("Dinamik bosim (v=10)", "rho*50/1000", "kPa", "compress"),
                fr("Kavitatsiya tezligi", "sqrt(2*p0*1000/rho)", "m/s", "mark")],
      note="Suvda 300 kPa da kavitatsiya ~24,5 m/s da boshlanadi — nasos parragi shuning uchun yemiriladi."),
  fig("Torrichelli formulasi: teshikdan oqish",
      "Oqish tezligi erkin tushish tezligiga teng.",
      params=[fp("Cd", "Oqim koeffitsienti", 0.5, 1, 0.62, 0.01, ""),
              fp("d", "Teshik diametri", 1, 100, 20, 1, "mm")],
      curves=[fc("v = √(2gh), m/s", "sqrt(2*9.81*x)", "tension"),
              fc("Haqiqiy sarf Q, l/s", "Cd*pi*(d*1e-3)^2/4*sqrt(2*9.81*x)*1000", "compress")],
      x=("suv balandligi h, m", "v, m/s  /  Q, l/s"), x_min="0", x_max="10",
      readouts=[fr("v (h=2 m)", "sqrt(2*9.81*2)", "m/s", "tension"),
                fr("Q (h=2 m)", "Cd*pi*(d*1e-3)^2/4*sqrt(2*9.81*2)*1000", "l/s", "compress"),
                fr("Balandlik 4× oshsa v", "2", "marta", "mark")],
      note="Tezlik balandlikning KVADRAT ILDIZIGA bog'liq — bak yarmigacha bo'shaganda sarf atigi 29% kamayadi."),
 ],
 "tmm-27": [
  fig("Nyuton gipotezasi: urinma kuchlanish va tezlik gradiyenti",
      "Yopishqoqlik ikkalasini chiziqli bog'laydi.",
      params=[fp("mu", "Dinamik yopishqoqlik μ", 0.0001, 2, 0.001, 0.0001, "Pa·s"),
              fp("h", "Tirqish", 0.01, 10, 0.5, 0.01, "mm")],
      curves=[fc("τ = μv/h, Pa", "mu*x/(h*1e-3)", "tension"),
              fc("Havo (μ=1,8e−5) uchun", "1.8e-5*x/(h*1e-3)", "compress", dashed=True)],
      x=("plastina tezligi v, m/s", "τ, Pa"), x_min="0", x_max="5",
      readouts=[fr("τ (v=1 m/s)", "mu/(h*1e-3)", "Pa", "tension"),
                fr("Ishqalanish kuchi (1 m²)", "mu/(h*1e-3)", "N", "compress"),
                fr("Quvvat (v=1 m/s, 1 m²)", "mu/(h*1e-3)", "W", "mark")],
      note="Podshipnik tirqishi 2 barobar kamaysa ishqalanish 2 barobar oshadi — moylash qalinligi kritik."),
  fig("Kinematik va dinamik yopishqoqlik",
      "ν = μ/ρ — havoda kinematik yopishqoqlik suvdan katta.",
      params=[fp("mu", "Dinamik yopishqoqlik", 1e-5, 1, 0.001, 1e-5, "Pa·s")],
      curves=[fc("ν = μ/ρ, mm²/s", "mu/x*1e6", "tension"),
              fc("Suv darajasi (1 mm²/s)", "1", "rule", dashed=True)],
      x=("zichlik ρ, kg/m³", "ν, mm²/s"), x_min="0.5", x_max="2000",
      readouts=[fr("ν (suv, ρ=1000)", "mu/1000*1e6", "mm²/s", "tension"),
                fr("ν (havo, ρ=1,2)", "mu/1.2*1e6", "mm²/s", "compress"),
                fr("Reynolds (v=1, L=0,1)", "0.1*1000/mu", "", "mark")],
      note="Havoning ν si suvnikidan ~15 marta katta — shuning uchun havoda chegaraviy qatlam qalinroq."),
 ],
 "tmm-28": [
  fig("Puazeyl oqimi: parabolik tezlik profili",
      "Devorda nol, markazda maksimal.",
      params=[fp("dp", "Bosim yo'qotish", 100, 100000, 5000, 100, "Pa/m"),
              fp("mu", "Yopishqoqlik", 0.0001, 1, 0.001, 0.0001, "Pa·s"),
              fp("R", "Quvur radiusi", 1, 100, 10, 0.5, "mm")],
      curves=[fc("v(r) = (Δp/4μL)(R²−r²)", "dp/(4*mu)*((R*1e-3)^2 - (x*1e-3)^2)", "tension"),
              fc("O'rtacha tezlik", "dp*(R*1e-3)^2/(8*mu)", "rule", dashed=True)],
      x=("radius r, mm", "tezlik v, m/s"), x_min="-R", x_max="R",
      readouts=[fr("v_max (markazda)", "dp*(R*1e-3)^2/(4*mu)", "m/s", "tension"),
                fr("O'rtacha v", "dp*(R*1e-3)^2/(8*mu)", "m/s", "rule"),
                fr("Sarf Q", "pi*dp*(R*1e-3)^4/(8*mu)*1000", "l/s", "compress")],
      note="Sarf radiusning TO'RTINCHI darajasiga proporsional — diametr 20% kamaysa sarf yarmiga tushadi."),
  fig("Kuett oqimi: chiziqli profil",
      "Bosim gradiyentisiz sof siljish oqimi.",
      params=[fp("U", "Yuqori devor tezligi", 0.1, 20, 2, 0.1, "m/s"),
              fp("h", "Tirqish", 0.1, 20, 2, 0.1, "mm"),
              fp("mu", "Yopishqoqlik", 0.0001, 2, 0.05, 0.0001, "Pa·s")],
      curves=[fc("v(y) = Uy/h", "U*x/h", "tension"),
              fc("O'rtacha tezlik", "U/2", "rule", dashed=True)],
      x=("y, mm", "tezlik v, m/s"), x_min="0", x_max="h",
      readouts=[fr("τ devorda", "mu*U/(h*1e-3)", "Pa", "compress"),
                fr("O'rtacha tezlik", "U/2", "m/s", "rule"),
                fr("Solishtirma quvvat", "mu*U^2/(h*1e-3)", "W/m²", "mark")],
      note="Kuett oqimi podshipnik va viskozimetr ishining asosi — profil aynan chiziqli."),
 ],
 "tmm-29": [
  fig("Reynolds soni va oqim rejimi",
      "2300 atrofida laminar rejim turbulentga o'tadi.",
      params=[fp("nu", "Kinematik yopishqoqlik", 1e-7, 1e-4, 1e-6, 1e-7, "m²/s"),
              fp("d", "Quvur diametri", 1, 500, 50, 1, "mm")],
      curves=[fc("Re = vd/ν", "x*d*1e-3/nu", "tension"),
              fc("Re = 2300 (kritik)", "2300", "rule", dashed=True),
              fc("Re = 4000 (turbulent)", "4000", "compress", dashed=True)],
      x=("tezlik v, m/s", "Reynolds soni"), x_min="0", x_max="5",
      readouts=[fr("Re (v=1 m/s)", "d*1e-3/nu", "", "tension"),
                fr("Kritik tezlik", "2300*nu/(d*1e-3)", "m/s", "mark"),
                fr("Rejim (v=1)", "d*1e-3/nu - 2300", "", "compress", text="laminar|TURBULENT")],
      note="Suvda 50 mm quvurda kritik tezlik atigi 4,6 sm/s — amaliy oqimlar deyarli har doim turbulent."),
  fig("Chegaraviy qatlam qalinligi",
      "Laminar qatlam masofa kvadrat ildizi bo'yicha o'sadi.",
      params=[fp("U", "Oqim tezligi", 0.5, 50, 10, 0.5, "m/s"),
              fp("nu", "Kinematik yopishqoqlik", 1e-7, 1e-4, 1.5e-5, 1e-7, "m²/s")],
      curves=[fc("δ = 5√(νx/U), mm", "5*sqrt(nu*x/U)*1000", "tension"),
              fc("Turbulent: 0,37x/Re^0,2", "0.37*x/(U*x/nu)^0.2*1000", "compress")],
      x=("masofa x, m", "qatlam qalinligi δ, mm"), x_min="0.01", x_max="2",
      readouts=[fr("δ_lam (x=1 m)", "5*sqrt(nu/U)*1000", "mm", "tension"),
                fr("δ_turb (x=1 m)", "0.37/(U/nu)^0.2*1000", "mm", "compress"),
                fr("O'tish nuqtasi (Re=5·10⁵)", "5e5*nu/U", "m", "mark")],
      note="Turbulent qatlam ancha qalin — shuning uchun u ko'proq ishqalanish, lekin kamroq ajralish beradi."),
 ],
 "tmm-30": [
  fig("Reynolds kuchlanishlari va turbulent yopishqoqlik",
      "Turbulent aralashish molekulyar yopishqoqlikdan minglab barobar kuchli.",
      params=[fp("u1", "Tebranish tezligi u'", 0.001, 2, 0.1, 0.001, "m/s"),
             fp("nu", "Molekulyar ν", 1e-7, 1e-4, 1e-6, 1e-7, "m²/s")],
      curves=[fc("ν_t = u'ℓ, m²/s", "u1*x*1e-3", "tension"),
              fc("Molekulyar ν", "nu", "rule", dashed=True)],
      x=("aralashish uzunligi ℓ, mm", "ν_t, m²/s"), x_min="0.1", x_max="100",
      readouts=[fr("ν_t (ℓ=10 mm)", "u1*1e-2", "m²/s", "tension"),
                fr("ν_t/ν", "u1*1e-2/nu", "marta", "mark"),
                fr("Reynolds kuchlanishi", "1000*u1^2", "Pa", "compress")],
      note="ν_t/ν ~10³…10⁵ — turbulent aralashish issiqlik va impulsni shuncha marta tez tashiydi."),
  fig("Devor qonuni: logarifmik profil",
      "Turbulent oqimda tezlik logarifmik o'sadi.",
      params=[fp("ut", "Dinamik tezlik u*", 0.01, 2, 0.2, 0.01, "m/s"),
              fp("nu", "Kinematik ν", 1e-7, 1e-4, 1e-6, 1e-7, "m²/s")],
      curves=[fc("Logarifmik soha u = u*(2,5 ln y⁺ + 5,5), m/s", "ut*(2.5*log(10^x*1e-3*ut/nu) + 5.5)", "tension"),
              fc("Yopishqoq osti qatlam u = u*y⁺", "ut*(10^x*1e-3*ut/nu)", "compress", dashed=True)],
      x=("lg(devordan masofa y, mm)", "tezlik u, m/s"), x_min="-2", x_max="1.5",
      readouts=[fr("u⁺ (y⁺=100)", "2.5*log(100) + 5.5", "", "tension"),
                fr("Qatlamlar kesishishi y⁺", "11.6", "", "mark"),
                fr("y (y⁺=30)", "30*nu/ut*1000", "mm", "compress")],
      note="y⁺ < 5 yopishqoq osti qatlam, y⁺ > 30 logarifmik soha — turbulentlik modellari aynan shu bo'linishga tayanadi."),
 ],
}
